In [32]:
import pandas as pd

In [33]:
topics = pd.read_excel('data/topics.xlsx')
projects = pd.read_excel('data/project.xlsx')
euroscivoc = pd.read_excel('data/euroSciVoc.xlsx')
orgs = pd.read_excel('data/organization.xlsx')

E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [36]:
projects['startDate']= pd.to_datetime(projects['startDate'],errors = 'coerce')
projects['endDate']= pd.to_datetime(projects['endDate'],errors = 'coerce')
projects.info()

from datetime import datetime
filterdate = datetime(2025,9,24)
projects_fil = projects[projects['startDate']>=filterdate]
projects_fil = projects_fil[projects_fil['endDate']<=datetime(2033,9,25)]
projects_fil

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19706 entries, 0 to 19705
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  19706 non-null  int64
 1   acronym             19706 non-null  object
 2   status              19706 non-null  object
 3   title               19706 non-null  object
 4   startDate           19706 non-null  datetime64[ns]
 5   endDate             19706 non-null  datetime64[ns]
 6   totalCost           19706 non-null  object
 7   ecMaxContribution   19706 non-null  object
 8   legalBasis          19706 non-null  object
 9   topics              19706 non-null  object
 10  ecSignatureDate     19704 non-null  object
 11  frameworkProgramme  19706 non-null  object
 12  masterCall          19706 non-null  object
 13  subCall             19706 non-null  object
 14  fundingScheme       19706 non-null  object
 15  objective           19706 non-null  object
 16  contentUpdateDate   19706 non-null  object
 17  rcn                 19706 non-null  int64
 18  grantDoi            19518 non-null  object
 19  keywords            17923 non-null  object
dtypes: datetime64[ns](2), int64(2), object(16)
memory usage: 3.0+ MB

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
0,101261720,REACH-UPPA,SIGNED,Research Excellence And Career Hub at Universi...,2026-10-01,2031-09-30,0,2256000,HORIZON.1.2,HORIZON-MSCA-2025-COFUND-01-01,2026-02-11,HORIZON,HORIZON-MSCA-2025-COFUND-01,HORIZON-MSCA-2025-COFUND-01,HORIZON-TMA-MSCA-Cofund-P,The Research Excellence And Career Hub at Univ...,2026-02-20 13:20:03,284247,10.3030/101261720,"multidisciplinary, tailored training programme"
1,101286935,BrightMind,SIGNED,BrightMind: An Integrated Hardware-Software Pl...,2026-09-01,2028-02-29,0,150000,HORIZON.1.1,ERC-2025-POC,2026-02-11,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,Fluorescence laser-scanning microscopy (LSM) i...,2026-02-15 21:38:58,284265,10.3030/101286935,"Photon-Resolved Microscopy, SPAD Array Detecto..."
2,101231746,RESADL,SIGNED,Reimagining Schools Through a Post-Disaster Lens,2026-09-01,2031-08-31,1977855,1977855,HORIZON.1.1,ERC-2025-COG,2026-02-09,HORIZON,ERC-2025-COG,ERC-2025-COG,HORIZON-ERC,Reimagining Schools through a Post-Disaster Le...,2026-02-15 21:38:58,284255,10.3030/101231746,NaN
3,101257710,GREENDIGO,SIGNED,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",2026-02-23 17:36:55,281931,10.3030/101257710,"enzymatic dyeing, biocatalysis, textile biotec..."
4,101229615,BALANG,SIGNED,Language in Balance: an Imprint of Brain Elect...,2027-01-01,2031-12-31,1994918,1994918,HORIZON.1.1,ERC-2025-COG,2026-02-03,HORIZON,ERC-2025-COG,ERC-2025-COG,HORIZON-ERC,It has long been recognised that the brain fun...,2026-02-23 16:17:51,284233,10.3030/101229615,"Periodic / aperiodic brain activity, Informati..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18747,101236610,NFFC,SIGNED,New Frontiers for Computability,2026-01-01,2029-12-31,0,435870,HORIZON.1.2,HORIZON-MSCA-2024-SE-01-01,2025-09-05,HORIZON,HORIZON-MSCA-2024-SE-01,HORIZON-MSCA-2024-SE-01,HORIZON-TMA-MSCA-SE,Recent advances in computability theory have u...,2025-10-02 10:27:12,276234,10.3030/101236610,NaN
19420,101201020,BRICMEM,SIGNED,Brain-inspired Computational Memory,2026-01-01,2030-12-31,0,2493073,HORIZON.1.1,ERC-2024-ADG,2025-10-31,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,Deep neural networks (DNNs) have transformed t...,2025-11-14 12:36:44,278545,10.3030/101201020,"In-memory computing, brain-inspired computing,..."
19615,101204257,CROSSING,SIGNED,Nigerian Practices of Male-to-Female Cross-Dre...,2025-11-01,2027-10-31,0,"230184,72",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-03-27,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,This research examines how selected Nigerian y...,2025-04-07 11:38:29,269960,10.3030/101204257,"Cross-dressing, performance, Nigeria, digital ..."
19677,101169737,SLEEPAWAY,SIGNED,Forgetting unwanted memories in sleep,2025-10-01,2030-09-30,1999769,1999769,HORIZON.1.1,ERC-2024-COG,2025-02-10,HORIZON,ERC-2024-COG,ERC-2024-COG,HORIZON-ERC,What we remember and forget lies at the core o...,2025-06-10 18:32:38,268819,10.3030/101169737,Forgetting Sleep
19692,101244209,DeRoCo,SIGNED,REVOLUTIONIZING TELECOM SECURITY AND RELIABILI...,2026-07-01,2028-06-30,0,"181423,68",HORIZON.4.1,HORIZON-WIDERA-2024-TALENTS-02-01,2025-07-07,HORIZON,HORIZON-WIDERA-2024-TALENTS-02,HORIZON-WIDERA-2024-TALENTS-02,HORIZON-TMA-MSCA-PF-EF,Privacy infringment is one of the most prevale...,2025-08-18 13:48:15,274569,NaN,"Speaker De-Identification, Speech Inpainting"

In [37]:
projectIDs = projects_fil['id'].tolist()

In [38]:
orgs

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101261720,REACH-UPPA,999547074,FR45180089047,INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE...,INRIA,False,REC,DOMAINE DE VOLUCEAU ROCQUENCOURT,78153,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1906120,4,associatedPartner,NaN,0.00,0,False,NaN
1,101261720,REACH-UPPA,999548044,ESG43619550,FUNDACIO INSTITUT CATALA D'INVESTIGACIO QUIMICA,ICIQ-CERCA,False,REC,AVENIDA PAISSOS CATALANS 16,43007,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1922222,6,associatedPartner,NaN,0.00,0,False,NaN
2,101261720,REACH-UPPA,999976105,BE0325777171,UNIVERSITE DE LIEGE,ULIEGE,False,HES,PLACE DU 20 AOUT 7,4000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1906589,22,associatedPartner,NaN,0.00,0,False,NaN
3,101261720,REACH-UPPA,876001375,NaN,Oninn Centro de Inovações,Oninn,False,REC,"avenida jose candido da silveira, 2000",31035536,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1995010,25,associatedPartner,NaN,0.00,0,False,NaN
4,101261720,REACH-UPPA,999898214,ESQ5018001G,UNIVERSIDAD DE ZARAGOZA,UNIVERSIDAD DE ZARAGOZA,False,HES,CALLE PEDRO CERBUNA 12,50009,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1905937,29,associatedPartner,NaN,0.00,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121718,101103706,BatteReverse,885436274,EL996687200,FRONTIER KENTRO KAINOTOMIAS AMKE,NaN,False,REC,LASKARATOU 5,111 41,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-03 16:44:20,1979268,6,thirdParty,0.00,187468.75,0,False,NaN
121719,101103706,BatteReverse,897707744,ESB67513630,EIT KIC URBAN MOBILITY SL,NaN,True,PRC,"CALLE PAMPLONA 104, 3",08018,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-03 16:44:20,1967320,5,participant,62351.25,62351.25,"62351,25",True,NaN
121720,101103706,BatteReverse,897528779,FR76850572231,TES SUSTAINABLE BATTERY SOLUTION FRANCE,TES SBS France,False,PRC,RUE DE LA METALLURGIE,38420,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-03 16:44:20,1967433,3,participant,736500.00,736500.00,736500,False,NaN
121721,101103706,BatteReverse,928030235,ESG66210345,FUNDACIO EURECAT,EURECAT,False,REC,AVENIDA UNIVERSITAT AUTONOMA 23,08290,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-03 16:44:20,2284307,2,participant,910305.00,910305.00,910305,False,NaN
121722,101103706,BatteReverse,998806479,ESB62822010,BAX INNOVATION CONSULTING SL,Bax & Company,True,PRC,"CALLE CASP 116-118, 5",08013,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-03 16:44:20,1915903,8,participant,281157.50,281157.50,"281157,5",False,NaN

In [39]:
orgsinproj = orgs[orgs['projectID'].isin(projectIDs)]
orgsinproj

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101261720,REACH-UPPA,999547074,FR45180089047,INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE...,INRIA,False,REC,DOMAINE DE VOLUCEAU ROCQUENCOURT,78153,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1906120,4,associatedPartner,NaN,0.00,0,False,NaN
1,101261720,REACH-UPPA,999548044,ESG43619550,FUNDACIO INSTITUT CATALA D'INVESTIGACIO QUIMICA,ICIQ-CERCA,False,REC,AVENIDA PAISSOS CATALANS 16,43007,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1922222,6,associatedPartner,NaN,0.00,0,False,NaN
2,101261720,REACH-UPPA,999976105,BE0325777171,UNIVERSITE DE LIEGE,ULIEGE,False,HES,PLACE DU 20 AOUT 7,4000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1906589,22,associatedPartner,NaN,0.00,0,False,NaN
3,101261720,REACH-UPPA,876001375,NaN,Oninn Centro de Inovações,Oninn,False,REC,"avenida jose candido da silveira, 2000",31035536,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1995010,25,associatedPartner,NaN,0.00,0,False,NaN
4,101261720,REACH-UPPA,999898214,ESQ5018001G,UNIVERSIDAD DE ZARAGOZA,UNIVERSIDAD DE ZARAGOZA,False,HES,CALLE PEDRO CERBUNA 12,50009,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-20 13:20:03,1905937,29,associatedPartner,NaN,0.00,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120426,101201020,BRICMEM,999987648,DE811225433,RUPRECHT-KARLS-UNIVERSITAET HEIDELBERG,UHEI,False,HES,SEMINARSTRASSE 2,69117,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-14 12:36:44,1907466,1,coordinator,2493073.00,2493073.00,0,False,NaN
121402,101204257,CROSSING,999873188,ATU57511277,UNIVERSITAET GRAZ,UNI GRAZ,False,HES,UNIVERSITATSPLATZ 3,8010,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-04-07 11:38:29,1906994,1,coordinator,230184.72,230184.72,0,False,NaN
121616,101169737,SLEEPAWAY,999978336,GB647205541,UNIVERSITY OF YORK,UNIVERSITY OF YORK,False,HES,HESLINGTON,YO10 5DD,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-06-10 18:32:38,1905740,1,coordinator,1999769.00,1999769.00,1999769,False,NaN
121675,101244209,DeRoCo,999562788,EL999723442,ATHINA-EREVNITIKO KENTRO KAINOTOMIAS STIS TECH...,ATHENA - RESEARCH AND INNOVATION CENTER,False,REC,ARTEMIDOS 6 KAI EPIDAVROU,151 25,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:15,1909986,1,coordinator,181423.68,181423.68,0,False,NaN
121676,101244209,DeRoCo,997186288,NaN,TECHNISCHE HOCHSCHULE ASCHAFFENBURG,UNIVERSITY OF APPLIED SCIENCES ASCHAFFENBURG,False,HES,WUERZBURGER STRASSE 45,63743,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:15,2946623,2,associatedPartner,NaN,0.00,0,False,NaN

In [40]:
print (orgsinproj['country'].unique())

['FR' 'ES' 'BE' 'BR' 'AR' 'DE' 'US' 'NO' 'IT' 'UK' 'CA' 'AU' 'PT' 'NL'
 'PL' 'HR' 'DK' 'FI' 'EL' 'SI' 'CH' 'LT' 'CZ' 'IL' 'JM' 'FJ' 'MT' 'KM'
 'AT' 'CY' 'BG' 'IE' 'SE' 'CN' 'CO' 'LU' 'RO' 'TR' 'SK' 'UA' 'HU' 'MD'
 'EE' 'TN' 'MA' 'IS' 'ZA' 'KE' 'MW' 'UG' 'GH' 'VN' 'KZ' 'PH' 'PG' 'LK'
 'NP' 'KG' 'LV' 'PK' 'AL' 'MV' 'LA' 'BA' 'ZM' 'PE' 'CL' 'SG' 'EG' 'NG'
 'IN' 'RS' 'MY' 'PY' 'NZ' 'SN' 'MK' 'JP' 'GE' 'BJ' 'CM' 'TG' 'CF' 'JO'
 'TH' 'HK' 'MG' 'MX' 'GL' 'ET' 'BF' 'DJ' 'ME' 'ZW' 'CI' 'BW' 'MU' 'KR'
 'AW' 'AM' 'TZ' 'GU' 'MP' 'MZ' nan 'CU' 'UZ' 'TM' 'TJ' 'ID' 'EC' 'LB' 'ST'
 'DO' 'CR' 'CV' 'CD' 'UY' 'SZ' 'DZ' 'GA' 'BO' 'TW' 'SA' 'ML' 'CG']

In [41]:
projectsIDS_with_widening = orgsinproj[orgsinproj['country'].isin(['EL','BG','HR','CZ','EE','HU','LV','LT','MT','PL','PT','RO','SK','SI',
                                                                   'AL','BA','AM','FO','GE','XK','MD','ME','MK','RS','TN','TR','UA','MA',
                                                                   'GP','GF','MQ','YT','CY'])]
projectsIDS_with_widening= projectsIDS_with_widening['projectID'].tolist()

In [42]:
projects_no_widening = projects_fil[~projects_fil['id'].isin(projectsIDS_with_widening)]
projects_no_widening

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
1,101286935,BrightMind,SIGNED,BrightMind: An Integrated Hardware-Software Pl...,2026-09-01,2028-02-29,0,150000,HORIZON.1.1,ERC-2025-POC,2026-02-11,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,Fluorescence laser-scanning microscopy (LSM) i...,2026-02-15 21:38:58,284265,10.3030/101286935,"Photon-Resolved Microscopy, SPAD Array Detecto..."
3,101257710,GREENDIGO,SIGNED,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",2026-02-23 17:36:55,281931,10.3030/101257710,"enzymatic dyeing, biocatalysis, textile biotec..."
4,101229615,BALANG,SIGNED,Language in Balance: an Imprint of Brain Elect...,2027-01-01,2031-12-31,1994918,1994918,HORIZON.1.1,ERC-2025-COG,2026-02-03,HORIZON,ERC-2025-COG,ERC-2025-COG,HORIZON-ERC,It has long been recognised that the brain fun...,2026-02-23 16:17:51,284233,10.3030/101229615,"Periodic / aperiodic brain activity, Informati..."
5,101247638,DeepEnergy,SIGNED,Evaluation of the biotechnological interest of...,2026-03-01,2027-08-31,0,150000,HORIZON.1.1,ERC-2025-POC,2026-02-11,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,The biotechnological production of hydrogen (H...,2026-02-15 21:38:58,284249,10.3030/101247638,NaN
6,101224126,CoEvolve,SIGNED,Co-evolutionary dynamics of viral pathogens a...,2026-06-01,2032-05-31,9999997,9999997,HORIZON.1.1,ERC-2025-SyG,2026-02-04,HORIZON,ERC-2025-SyG,ERC-2025-SyG,HORIZON-ERC-SYG,"Vertebrates, like ourselves, use adaptive immu...",2026-02-23 16:58:59,284230,10.3030/101224126,"evolution experiments, computational models, i..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18568,101209575,SPIDYM,SIGNED,Quantum Spin Dynamics in Cobalt-based Single M...,2026-07-01,2028-06-30,0,"217965,12",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-03-10,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,"In the field of molecular magnetism, research ...",2025-08-18 13:49:14,269301,10.3030/101209575,"Single molecule magnets (SMM), Cobalt-based SM..."
18569,101207264,ICING,SIGNED,Improving Cement-based Infrastructure from Nan...,2026-04-01,2028-03-31,0,"242260,56",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-03-19,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,This project addresses the pressing need for s...,2025-03-31 12:06:16,269798,10.3030/101207264,"Atomistic simulations, Cementitious materials..."
19420,101201020,BRICMEM,SIGNED,Brain-inspired Computational Memory,2026-01-01,2030-12-31,0,2493073,HORIZON.1.1,ERC-2024-ADG,2025-10-31,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,Deep neural networks (DNNs) have transformed t...,2025-11-14 12:36:44,278545,10.3030/101201020,"In-memory computing, brain-inspired computing,..."
19615,101204257,CROSSING,SIGNED,Nigerian Practices of Male-to-Female Cross-Dre...,2025-11-01,2027-10-31,0,"230184,72",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-03-27,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,This research examines how selected Nigerian y...,2025-04-07 11:38:29,269960,10.3030/101204257,"Cross-dressing, performance, Nigeria, digital ..."
19677,101169737,SLEEPAWAY,SIGNED,Forgetting unwanted memories in sleep,2025-10-01,2030-09-30,1999769,1999769,HORIZON.1.1,ERC-2024-COG,2025-02-10,HORIZON,ERC-2024-COG,ERC-2024-COG,HORIZON-ERC,What we remember and forget lies at the core o...,2025-06-10 18:32:38,268819,10.3030/101169737,Forgetting Sleep

In [43]:
orgs_no_widening = orgs[orgs['projectID'].isin(projects_no_widening['id'].tolist())]
orgs_no_widening

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
45,101286935,BrightMind,999596447,IT09198791007,FONDAZIONE ISTITUTO ITALIANO DI TECNOLOGIA,IIT,False,REC,VIA MOREGO 30,16163,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-15 21:38:58,1908748,1,coordinator,150000.00,150000.00,0,False,NaN
47,101257710,GREENDIGO,871776346,DK44981068,NordicBlue,NordicBlue ApS,True,PRC,Bakken 21,3050,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1994752,3,participant,1443808.75,1443808.75,"1443808,75",False,NaN
48,101257710,GREENDIGO,896476232,NL003125251B98,NEAGU ALEXANDRU-VALENTIN,BEE GRANTED,True,PRC,THORBECKEWEG 27,3732 BH,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1987817,4,participant,90220.00,90220.00,90220,False,NaN
49,101257710,GREENDIGO,991256096,FI22283574,AALTO KORKEAKOULUSAATIO SR,AALTO,False,HES,OTAKAARI 1,02150,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1906096,2,participant,841681.21,841681.21,"841681,21",False,NaN
50,101257710,GREENDIGO,999897341,IT00816350276,UNIVERSITA CA' FOSCARI VENEZIA,UNIVE,False,HES,DORSODURO 3246,30123,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1909514,1,coordinator,623435.04,623435.04,"623435,04",False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116734,101209575,SPIDYM,999974747,DE147794196,UNIVERSITY OF STUTTGART,USTUTT,False,HES,KEPLERSTRASSE 7,70174,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:49:14,1905614,1,coordinator,217965.12,217965.12,0,False,NaN
116735,101207264,ICING,999997930,FR40180089013,CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE CNRS,CNRS,False,REC,RUE MICHEL ANGE 3,75794,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-03-31 12:06:16,1905572,1,coordinator,242260.56,242260.56,0,False,NaN
120426,101201020,BRICMEM,999987648,DE811225433,RUPRECHT-KARLS-UNIVERSITAET HEIDELBERG,UHEI,False,HES,SEMINARSTRASSE 2,69117,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-14 12:36:44,1907466,1,coordinator,2493073.00,2493073.00,0,False,NaN
121402,101204257,CROSSING,999873188,ATU57511277,UNIVERSITAET GRAZ,UNI GRAZ,False,HES,UNIVERSITATSPLATZ 3,8010,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-04-07 11:38:29,1906994,1,coordinator,230184.72,230184.72,0,False,NaN
121616,101169737,SLEEPAWAY,999978336,GB647205541,UNIVERSITY OF YORK,UNIVERSITY OF YORK,False,HES,HESLINGTON,YO10 5DD,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-06-10 18:32:38,1905740,1,coordinator,1999769.00,1999769.00,1999769,False,NaN

In [44]:
euroscivoc

,projectID,euroSciVocCode,euroSciVocPath,euroSciVocTitle,euroSciVocDescription
0,101286935,/23/47/307,/natural sciences/computer and information sci...,software,NaN
1,101286935,/23/43/251/48354418,/natural sciences/physical sciences/optics/mic...,microscopy,NaN
2,101286935,/23/43/261/791/1541,/natural sciences/physical sciences/theoretica...,photons,NaN
3,101231746,/23/45/291/901,/natural sciences/earth and related environmen...,seismology,NaN
4,101257710,/23/53/365/78089026,/natural sciences/chemical sciences/inorganic ...,alkali metals,NaN
...,...,...,...,...,...
41998,101141366,/23/43/251/48354418,/natural sciences/physical sciences/optics/mic...,microscopy,NaN
41999,101141366,/23/43/251/745,/natural sciences/physical sciences/optics/las...,laser physics,NaN
42000,101141366,/23/43/251/1077,/natural sciences/physical sciences/optics/spe...,spectroscopy,NaN
42001,101141906,/31/113/613,/humanities/history and archaeology/history,history,NaN
42002,101141906,/31/109,/humanities/arts,arts,NaN

In [45]:
euroscivoc_proj_no_widening = euroscivoc[euroscivoc['projectID'].isin(projects_no_widening['id'].tolist())]

In [46]:
euroscivoc_proj_no_widening['euroSciVocTitle'].unique()

array(['software', 'microscopy', 'photons', 'alkali metals', 'textiles',
       'pollution', 'enzymes', 'acoustics', 'bacteriology', 'coal',
       'lipids', 'virology', 'evolutionary biology', 'influenza',
       'coronaviruses', 'vaccines', 'partial differential equations',
       'oceanography', 'planets', 'optical sensors', 'automation',
       'recycling', 'electrolysis', 'catalysis', 'colors', 'history',
       'quantum computers', 'superconductivity', 'ontology', 'pandemics',
       'anthropology', 'animal husbandry', 'zoonosis', 'fermentation',
       'biomolecules', 'nano-materials', 'irrigation',
       'climate change adaptation', 'remote sensing',
       'earth and related environmental sciences', 'radio frequency',
       'nanocrystals', 'sensors', 'proteins', 'biophysics',
       'artificial intelligence', 'mental processes',
       'cognitive neuroscience', 'computational neuroscience',
       'electrocatalysis', 'DNA', 'genomes', 'energy conversion',
       'proteomics', 'cardiovascular diseases', 'physiology',
       'meteorites', 'mineralogy', 'religions', 'ecosystems', 'fisheries',
       'governance', 'agriculture', 'law', 'invertebrate zoology',
       'graphene', 'coating and films', 'laser physics', 'mutation',
       'nucleotides', 'RNA', 'fibers', 'heuristic programming',
       'nanophotonics', 'ecology', 'bioeconomy', 'metalloids',
       'biogeochemistry', 'wastewater treatment processes', 'nutrition',
       'surgery', 'applied mechanics', 'tissue engineering',
       'polymer sciences', 'biomaterials', 'human migrations',
       'post-colonial theories', 'aircraft', 'radio technology',
       'spintronics', 'oncology', 'entomology', 'pathology', 'melanoma',
       'transcriptomes', 'homeostasis', 'carbohydrates',
       'biological interactions', 'mammalogy', 'employment',
       'neurobiology', 'alzheimer', 'pharmaceutical drugs', 'obstetrics',
       'embryology', 'photocatalysis', 'energy and fuels', 'botany',
       'democracy', 'photochemistry', 'pathophysiology', 'immunology',
       'parkinson', 'thermodynamics', 'robotics', 'corruption',
       'bureaucracy', 'epistemology', 'macroeconomics',
       'modern philosophy', 'modern and contemporary art',
       'particle physics', 'dark matter', 'glaucoma', 'toxicology',
       'malaria', 'mortality', 'drones', 'virtual reality',
       'quantum physics', 'quantum gases', 'optoelectronics',
       'ophthalmology', 'organ on a chip', 'implants',
       'super resolution microscopy', 'antibiotics', 'semiconductivity',
       'nanoelectronics', 'HIV', 'composites', 'metallurgy',
       'physical chemistry', 'archaeology', 'neutrinos',
       'particle accelerator', 'gluons', 'quarks', 'supercomputers',
       'armed conflicts', 'cavity optomechanics', 'immunotherapy',
       'liver cancer', 'cardiac arrhythmia', 'alkaline earth metals',
       'ancient history', 'essays', 'history of literature', 'dramaturgy',
       'additive manufacturing', 'ultrasound', 'geometry', 'genetics',
       'cell signaling', 'molecular and chemical physics', 'linguistics',
       'spectroscopy', 'revolutions', 'satellite technology',
       'plasma physics', 'entrepreneurship', 'civil society',
       'nano-processes', 'organic reactions',
       'bulk nanostructured materials', 'social biomedical sciences',
       'speech-language pathology', 'psychiatry', 'knowledge engineering',
       'business and management', 'contemporary history', 'sexual health',
       'elections', 'cinematography', 'penology', 'didactics',
       'social inequalities', 'urban studies', 'lab on a chip',
       'biochemistry', 'transplantation', 'multiphysics', 'combinatorics',
       'ideologies', 'analytical chemistry', 'biosensors',
       'electrochemistry', 'spacecraft', 'cereals', 'sustainable economy',
       'computer processors', 'lung cancer', 'gamma-ray astronomy',
       'astrophysics', 'cell biology', 'leptons', 'fermions',
       'physical cosmology', 'tuberculosis', 'molecular neuroscience',
       'psychology', 'transition metals', 'census', 'climatic changes',
       'epilepsy', 'anatomy and morphology', 'fluid dynamics',
       'stellar astronomy', 'theoretical physics', 'arteriosclerosis',
       'dementia', 'epigenetics', 'physical anthropology', 'radar',
       'fourier analysis', 'epigenomes', 'chromosomes',
       'aliphatic compounds', 'mycology', 'internet', 'cryptography',
       'topology', 'physical oceanography', 'pharmacokinetics',
       'solar astronomy', 'ethical principles', 'arts', 'globalization',
       'seismology', 'natural satellites', 'developmental biology',
       'nanotechnology', 'internet of things', 'tribology', 'databases',
       'vascular diseases', 'philosophy', 'nongovernmental organizations',
       'climatology', 'social anthropology',
       'cultural and economic geography', 'medical biotechnology',
       'physical geography', 'data processing', 'quantum optics',
       'biocatalysis', 'crystallography', 'microfluidics', 'immunisation',
       'palaeontology', 'microbiology', 'deep learning',
       'grains and oilseeds', 'motion analysis', 'vegetable growing',
       'hydrocarbons', 'speleology', 'laboratory samples analysis',
       'obesity', 'glaciology', 'amorphous semiconductors', 'cartography',
       'nanomedicine', 'kidney diseases', 'visual arts',
       'monetary and finances', 'mathematical model', 'physiotherapy',
       'algebra', 'schizophrenia', 'animal feed', 'mathematical physics',
       'astronomy', 'nuclear engineering', 'chemical sciences',
       'media and communications', 'statistics and probability',
       'machine learning', 'biosphera', 'metaphysics',
       'organometallic chemistry', 'stroke',
       'geographic information systems', 'dermatology', 'big data',
       'data mining', 'diagnostic imaging', 'photovoltaic',
       'combined heat and power', 'epidemiology', 'terrorism',
       'ecological restoration', 'bioarchaeology', 'public health',
       'numerical analysis', 'transportation engineering', 'biosensing',
       'graph theory', 'journalism', 'inorganic compounds',
       'post-transition metals', 'diabetes',
       'science and technology studies', 'thermodynamic engineering',
       'computational intelligence', 'mobile phones', 'sociology',
       'parasitology', 'magnetic resonance imaging', 'amorphous solids',
       'mathematical analysis', 'piezoelectrics', 'nursing', 'leukemia',
       'christianity', 'comparative morphology',
       'chemical process engineering', 'postnatal care',
       'synthetic biology', 'quasiparticles', 'personalized medicine',
       'bladder cancer', 'geophysics', 'general language studies',
       'psycholinguistics', 'productivity', 'taxation',
       'quantum field theory', 'planetary geology', 'structural biology',
       'digital humanities', 'fodder', 'domestic animals',
       'marine biology', 'behavioural ecology', 'molecular biology',
       'ethnology', 'atmospheric sciences', 'rotorcraft', 'antivirals',
       'ethnoarchaeology', 'dynamical systems',
       'computational fluid dynamics', 'political economy', 'fertility',
       'demography', 'geochemistry', 'colorectal cancer',
       'microeconomics', 'pedagogy', 'unemployment', 'astrochemistry',
       'food technology', 'calorimetry', 'asthma', 'alcohols',
       'criminology', 'other social sciences', 'business models',
       'desalination', 'distillation', 'manufacturing engineering',
       'fuel cells', 'gender inequality', 'condensed matter physics',
       'computational science', 'noble gases', 'mobile network',
       'electrodialysis', 'multidrug resistance', 'musicology',
       'volcanology', 'atomic physics', 'giant planets', 'exoplanetology',
       'islam', 'teleology', 'stem cells', 'electric energy',
       'medical engineering', 'neurology', 'human trafficking',
       'public policies', 'political communication', 'public services',
       'social issues', 'thermochemistry', 'gastroenterology',
       'mathematical logic', 'polyurethane', 'biomass energy',
       'renewable energy', 'separation technologies',
       'carbon capture engineering', 'cardiology', 'computer hardware',
       'edge artificial intelligence', 'quantum chemistry',
       'sustainable agriculture', 'fruit growing', 'ethics',
       'social geography', 'diagnostic technologies', 'petroleum',
       'biomass', 'materials engineering', 'inflammatory bowel disease',
       'computer security', 'medieval history', 'prehistory',
       'arboriculture', 'forestry', 'radiology', 'molecular genetics',
       'eukaryotic genomes', 'phycology', 'arithmetics',
       'hydrogen energy', 'bioreactors', 'economics', 'ceramics',
       'autonomous vehicles', 'supernova', 'glacial geology',
       'library sciences', 'data protection', 'data exchange',
       'electromagnetism and electronics', 'telecommunications networks',
       'bioprocessing technologies', 'plant breeding',
       'signal processing', 'optical networks', 'smart sensors',
       'social psychology', 'duchenne muscular dystrophy',
       'medical genetics', 'nuclear medicine', 'software applications',
       'electrical engineering', 'gene therapy', 'rheumatology',
       'economic impact of epidemics', 'literature studies',
       'art history', 'hybrid energy', 'logarithmic functions',
       'optical astronomy', 'galactic astronomy', 'autonomous robots',
       'waste treatment processes', 'international law', 'human rights',
       'educational sciences', 'nanocomposites',
       'organic amorphous solids', 'histology', 'breast cancer',
       'geotechnics', 'geothermal energy', 'innovation management',
       'wind energy', 'social developments', 'electron microscopy',
       'prostate cancer', 'critical care medicine',
       'languages and literature', 'hydrometeorology', 'aldehydes',
       'polylactic acid', 'phonology', 'phonetics', 'plate tectonics',
       'women’s studies', 'human rights violations',
       'analogue electronics', 'exposomes', 'synthetic dyes',
       'ergonomics', 'radiochemistry', 'radiation chemistry',
       'racial inequality', 'synthetic fuels', 'WiFi', 'endocrinology',
       'algebraic geometry', 'ornithology', 'functional morphology',
       'agricultural biotechnology', 'amines', 'hepatology',
       'microbiomes', 'food packaging', 'horticulture',
       'climatic change mitigation', 'applied mathematics',
       'family planning', 'family studies', 'black holes', 'cetology',
       'heredity', 'cognitive psychology', 'optics', 'eastern religions',
       'cells technologies', 'sedimentology', 'agroecology', 'biofuels',
       'isotope geochemistry', 'antibiotic resistance', 'paleoecology',
       'modern history', 'structural health monitoring',
       'pharmacology and pharmacy', 'hydrology', 'remanufacturing',
       'foreign policy', 'environmental law', 'development economics',
       'development studies', 'halogens', 'environmental governance',
       'microelectronics', 'computer and information sciences',
       'generative artificial intelligence', 'biodiversity conservation',
       'multiple sclerosis', 'pneumology', 'flood risk management',
       'judaism', 'geology', 'econometrics', 'galaxy evolution',
       'electric power transmission', 'sustainable building',
       'solar energy', 'subtractive manufacturing', 'system software',
       'zoology', 'biocomposites', 'primatology', 'paleoclimatology',
       'molecular spintronics', 'global navigation satellite system',
       'geochronology', 'metabolomes', 'ethical theories',
       'aeronautical engineering', 'video games', 'control systems',
       'soft robotics', 'dairy', 'microtechnology', 'psychoanalysis',
       'medieval philosophy', 'transport', 'data science',
       'simulation software', 'z bosons', 'higgs bosons',
       'heat engineering', 'asteroids', 'political philosophy',
       'habitat conservation', 'air pollution engineering', 'paediatrics',
       'nonlinear optics', 'age inequality', 'ethnolichenology',
       'ethnomusicology', 'meteorology', 'reinforcement learning',
       'molecular evolution', 'reproductive medicine',
       'soft matter physics', 'supervised learning', 'crisis management',
       'pandemic risks', 'contemporary philosophy', 'super-Earths',
       'data networks'], dtype=object)

In [47]:
scivocpathlist = euroscivoc_proj_no_widening['euroSciVocPath'].tolist()

In [48]:
paths = ",".join(scivocpathlist)
print (paths)

/natural sciences/computer and information sciences/software,/natural sciences/physical sciences/optics/microscopy,/natural sciences/physical sciences/theoretical physics/particle physics/photons,/natural sciences/chemical sciences/inorganic chemistry/alkali metals,/engineering and technology/materials engineering/textiles,/natural sciences/earth and related environmental sciences/environmental sciences/pollution,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/physical sciences/acoustics,/natural sciences/biological sciences/microbiology/bacteriology,/engineering and technology/environmental engineering/energy and fuels/fossil energy/coal,/natural sciences/biological sciences/biochemistry/biomolecules/lipids,/natural sciences/biological sciences/microbiology/virology,/natural sciences/biological sciences/evolutionary biology,/medical and health sciences/health sciences/infectious diseases/RNA viruses/influenza,/medical and health sciences/health sciences/infectious diseases/RNA viruses/coronaviruses,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/vaccines,/natural sciences/mathematics/pure mathematics/mathematical analysis/differential equations/partial differential equations,/natural sciences/earth and related environmental sciences/oceanography,/natural sciences/physical sciences/astronomy/planetary sciences/planets,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/optical sensors,/social sciences/sociology/industrial relations/automation,/engineering and technology/environmental engineering/waste management/waste treatment processes/recycling,/natural sciences/chemical sciences/electrochemistry/electrolysis,/natural sciences/chemical sciences/catalysis,/natural sciences/computer and information sciences/software,/engineering and technology/materials engineering/colors,/humanities/history and archaeology/history,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/quantum computers,/natural sciences/physical sciences/electromagnetism and electronics/superconductivity,/natural sciences/computer and information sciences/knowledge engineering/ontology,/medical and health sciences/health sciences/public health/epidemiology/pandemics,/social sciences/sociology/anthropology,/agricultural sciences/animal and dairy science/domestic animals/animal husbandry,/medical and health sciences/health sciences/public health/epidemiology/zoonosis,/engineering and technology/industrial biotechnology/bioprocessing technologies/fermentation,/natural sciences/biological sciences/biochemistry/biomolecules,/natural sciences/physical sciences/optics/microscopy,/engineering and technology/materials engineering/textiles,/engineering and technology/nanotechnology/nano-materials,/engineering and technology/civil engineering/water engineering/irrigation,/engineering and technology/environmental engineering/ecosystem-based management/climate change adaptation,/natural sciences/physical sciences/astronomy/planetary sciences/planets,/engineering and technology/environmental engineering/remote sensing,/natural sciences/earth and related environmental sciences,/engineering and technology/electrical engineering, electronic engineering, information engineering/information engineering/telecommunications/radio technology/radio frequency,/engineering and technology/nanotechnology/nano-materials/nanocrystals,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/physical sciences/theoretical physics/particle physics/photons,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/biological sciences/biophysics,/natural sciences/computer and information sciences/artificial intelligence,/social sciences/psychology/cognitive psychology/mental processes,/natural sciences/biological sciences/neurobiology/cognitive neuroscience,/natural sciences/biological sciences/neurobiology/computational neuroscience,/natural sciences/physical sciences/optics/microscopy,/engineering and technology/nanotechnology/nano-materials,/natural sciences/chemical sciences/catalysis/electrocatalysis,/natural sciences/biological sciences/microbiology/virology,/natural sciences/biological sciences/genetics/DNA,/natural sciences/biological sciences/genetics/genomes,/engineering and technology/environmental engineering/energy and fuels/energy conversion,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/natural sciences/physical sciences/optics/microscopy,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases,/medical and health sciences/basic medicine/physiology,/humanities/history and archaeology/history,/natural sciences/physical sciences/astronomy/planetary sciences/meteorites,/natural sciences/earth and related environmental sciences/geology/mineralogy,/humanities/philosophy, ethics and religion/religions,/natural sciences/biological sciences/ecology/ecosystems,/natural sciences/chemical sciences/electrochemistry/electrolysis,/agricultural sciences/agriculture, forestry, and fisheries/fisheries,/social sciences/sociology/governance,/social sciences/sociology/anthropology,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/social sciences/law,/humanities/history and archaeology/history,/natural sciences/biological sciences/ecology/ecosystems,/natural sciences/biological sciences/zoology/invertebrate zoology,/engineering and technology/nanotechnology/nano-materials/two-dimensional nanostructures/graphene,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/optical sensors,/engineering and technology/materials engineering/coating and films,/natural sciences/physical sciences/optics/laser physics,/natural sciences/biological sciences/genetics/mutation,/natural sciences/biological sciences/genetics/nucleotides,/natural sciences/biological sciences/genetics/RNA,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/engineering and technology/materials engineering/fibers,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/computer and information sciences/software,/natural sciences/computer and information sciences/artificial intelligence/heuristic programming,/engineering and technology/nanotechnology/nanophotonics,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/biological sciences/genetics/mutation,/natural sciences/biological sciences/ecology,/social sciences/economics and business/economics/bioeconomy,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/natural sciences/earth and related environmental sciences/oceanography,/natural sciences/earth and related environmental sciences/geochemistry/biogeochemistry,/engineering and technology/environmental engineering/water treatment processes/wastewater treatment processes,/natural sciences/biological sciences/genetics/DNA,/medical and health sciences/health sciences/nutrition,/natural sciences/earth and related environmental sciences/environmental sciences/pollution,/natural sciences/biological sciences/ecology/ecosystems,/humanities/history and archaeology/history,/medical and health sciences/clinical medicine/surgery,/engineering and technology/mechanical engineering/applied mechanics,/medical and health sciences/medical biotechnology/tissue engineering,/natural sciences/chemical sciences/polymer sciences,/engineering and technology/industrial biotechnology/biomaterials,/social sciences/sociology/anthropology,/social sciences/sociology/demography/human migrations,/humanities/history and archaeology/history,/social sciences/other social sciences/development studies/development theories/post-colonial theories,/natural sciences/chemical sciences/inorganic chemistry/alkali metals,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/aircraft,/engineering and technology/electrical engineering, electronic engineering, information engineering/information engineering/telecommunications/radio technology,/natural sciences/physical sciences/optics/microscopy,/natural sciences/physical sciences/electromagnetism and electronics/spintronics,/medical and health sciences/clinical medicine/oncology,/engineering and technology/nanotechnology/nano-materials,/natural sciences/biological sciences/zoology/entomology,/medical and health sciences/basic medicine/pathology,/natural sciences/biological sciences/biochemistry/biomolecules,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/medical and health sciences/clinical medicine/oncology/skin cancer/melanoma,/natural sciences/biological sciences/genetics/RNA/transcriptomes,/medical and health sciences/basic medicine/physiology/homeostasis,/medical and health sciences/clinical medicine/oncology,/natural sciences/biological sciences/microbiology/bacteriology,/natural sciences/biological sciences/biochemistry/biomolecules/carbohydrates,/natural sciences/biological sciences/biological behavioural sciences/ethology/biological interactions,/natural sciences/biological sciences/zoology/mammalogy,/social sciences/economics and business/business and management/employment,/natural sciences/biological sciences/neurobiology,/medical and health sciences/basic medicine/neurology/dementia/alzheimer,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs,/medical and health sciences/clinical medicine/obstetrics,/medical and health sciences/clinical medicine/embryology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/chemical sciences/catalysis/photocatalysis,/engineering and technology/environmental engineering/energy and fuels,/natural sciences/biological sciences/botany,/social sciences/political sciences/government systems/democracy,/natural sciences/chemical sciences/physical chemistry/photochemistry,/natural sciences/chemical sciences/polymer sciences,/natural sciences/biological sciences/neurobiology,/medical and health sciences/basic medicine/physiology/pathophysiology,/medical and health sciences/basic medicine/immunology,/medical and health sciences/basic medicine/pathology,/medical and health sciences/basic medicine/neurology/parkinson,/humanities/history and archaeology/history,/natural sciences/physical sciences/thermodynamics,/natural sciences/physical sciences/astronomy/planetary sciences/planets,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/natural sciences/computer and information sciences/software,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/basic medicine/pathology,/social sciences/sociology/social issues/corruption,/social sciences/political sciences/public administration/bureaucracy,/social sciences/sociology/demography/human migrations,/humanities/philosophy, ethics and religion/philosophy/epistemology,/social sciences/economics and business/economics/macroeconomics,/humanities/history and archaeology/history,/humanities/philosophy, ethics and religion/philosophy/history of philosophy/modern philosophy,/humanities/arts/modern and contemporary art,/natural sciences/physical sciences/theoretical physics/particle physics,/natural sciences/physical sciences/astronomy/astrophysics/dark matter,/natural sciences/biological sciences/neurobiology,/medical and health sciences/clinical medicine/ophthalmology/glaucoma,/medical and health sciences/basic medicine/toxicology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/medical and health sciences/health sciences/infectious diseases/malaria,/social sciences/sociology/demography/mortality,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/vaccines,/humanities/history and archaeology/history,/humanities/philosophy, ethics and religion/religions,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics/autonomous robots/drones,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/computer and information sciences/software/software applications/virtual reality,/natural sciences/physical sciences/electromagnetism and electronics/spintronics,/natural sciences/physical sciences/quantum physics,/natural sciences/physical sciences/thermodynamics,/natural sciences/physical sciences/condensed matter physics/quantum gases,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/aircraft,/natural sciences/physical sciences/electromagnetism and electronics/optoelectronics,/medical and health sciences/clinical medicine/ophthalmology,/engineering and technology/nanotechnology/nano-materials,/engineering and technology/other engineering and technologies/microtechnology/organ on a chip,/medical and health sciences/medical biotechnology/implants,/natural sciences/physical sciences/optics/microscopy/super resolution microscopy,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/antibiotics,/natural sciences/physical sciences/electromagnetism and electronics/semiconductivity,/engineering and technology/nanotechnology/nanoelectronics,/social sciences/law,/natural sciences/computer and information sciences/software,/medical and health sciences/health sciences/infectious diseases/RNA viruses/HIV,/natural sciences/biological sciences/biological behavioural sciences/ethology/biological interactions,/engineering and technology/materials engineering/composites,/engineering and technology/materials engineering/metallurgy,/natural sciences/chemical sciences/physical chemistry,/humanities/history and archaeology/history,/humanities/history and archaeology/archaeology,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/clinical medicine/oncology,/humanities/history and archaeology/history,/natural sciences/chemical sciences/polymer sciences,/natural sciences/physical sciences/theoretical physics/particle physics/neutrinos,/natural sciences/physical sciences/theoretical physics/particle physics/particle accelerator,/natural sciences/physical sciences/theoretical physics/particle physics/gluons,/natural sciences/physical sciences/theoretical physics/particle physics/quarks,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/supercomputers,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/medical and health sciences/basic medicine/physiology/homeostasis,/social sciences/political sciences/political transitions/armed conflicts,/natural sciences/physical sciences/optics/cavity optomechanics,/engineering and technology/nanotechnology/nano-materials,/natural sciences/physical sciences/optics/laser physics,/natural sciences/biological sciences/biochemistry/biomolecules/lipids,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/basic medicine/immunology/immunotherapy,/natural sciences/computer and information sciences/software,/medical and health sciences/clinical medicine/oncology/liver cancer,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases/cardiac arrhythmia,/natural sciences/chemical sciences/inorganic chemistry/alkaline earth metals,/engineering and technology/nanotechnology/nano-materials,/medical and health sciences/basic medicine/physiology/homeostasis,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/humanities/history and archaeology/history/ancient history,/humanities/languages and literature/literature studies/literary genres/essays,/humanities/languages and literature/literature studies/history of literature,/humanities/arts/performing arts/dramaturgy,/engineering and technology/materials engineering/composites,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/engineering and technology/mechanical engineering/manufacturing engineering/additive manufacturing,/medical and health sciences/medical biotechnology/implants,/natural sciences/physical sciences/acoustics/ultrasound,/engineering and technology/nanotechnology/nano-materials/nanocrystals,/natural sciences/earth and related environmental sciences/geology/mineralogy,/natural sciences/mathematics/pure mathematics/geometry,/natural sciences/biological sciences/genetics,/natural sciences/biological sciences/cell biology/cell signaling,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/physical sciences/molecular and chemical physics,/natural sciences/biological sciences/biophysics,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/optical sensors,/medical and health sciences/clinical medicine/oncology/skin cancer/melanoma,/natural sciences/physical sciences/optics/laser physics,/humanities/languages and literature/linguistics,/natural sciences/physical sciences/optics/microscopy,/engineering and technology/materials engineering/coating and films,/natural sciences/physical sciences/electromagnetism and electronics/spintronics,/natural sciences/physical sciences/electromagnetism and electronics/semiconductivity,/natural sciences/physical sciences/optics/spectroscopy,/humanities/languages and literature/linguistics,/humanities/history and archaeology/history,/medical and health sciences/health sciences/public health/epidemiology/pandemics,/social sciences/political sciences/political transitions/revolutions,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/satellite technology,/natural sciences/physical sciences/plasma physics,/social sciences/economics and business/business and management/entrepreneurship,/agricultural sciences/agriculture, forestry, and fisheries/fisheries,/social sciences/sociology/governance,/engineering and technology/environmental engineering/ecosystem-based management/climate change adaptation,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/social sciences/political sciences/political policies/civil society,/natural sciences/biological sciences/neurobiology,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/humanities/history and archaeology/history,/engineering and technology/nanotechnology/nano-processes,/natural sciences/chemical sciences/organic chemistry/organic reactions,/engineering and 

In [49]:
paths = paths.replace('/',',')
paths = paths.replace(',,',',')

In [50]:
paths

',natural sciences,computer and information sciences,software,natural sciences,physical sciences,optics,microscopy,natural sciences,physical sciences,theoretical physics,particle physics,photons,natural sciences,chemical sciences,inorganic chemistry,alkali metals,engineering and technology,materials engineering,textiles,natural sciences,earth and related environmental sciences,environmental sciences,pollution,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,physical sciences,acoustics,natural sciences,biological sciences,microbiology,bacteriology,engineering and technology,environmental engineering,energy and fuels,fossil energy,coal,natural sciences,biological sciences,biochemistry,biomolecules,lipids,natural sciences,biological sciences,microbiology,virology,natural sciences,biological sciences,evolutionary biology,medical and health sciences,health sciences,infectious diseases,RNA viruses,influenza,medical and health sciences,health sciences,infectious diseases,RNA viruses,coronaviruses,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,vaccines,natural sciences,mathematics,pure mathematics,mathematical analysis,differential equations,partial differential equations,natural sciences,earth and related environmental sciences,oceanography,natural sciences,physical sciences,astronomy,planetary sciences,planets,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,optical sensors,social sciences,sociology,industrial relations,automation,engineering and technology,environmental engineering,waste management,waste treatment processes,recycling,natural sciences,chemical sciences,electrochemistry,electrolysis,natural sciences,chemical sciences,catalysis,natural sciences,computer and information sciences,software,engineering and technology,materials engineering,colors,humanities,history and archaeology,history,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,quantum computers,natural sciences,physical sciences,electromagnetism and electronics,superconductivity,natural sciences,computer and information sciences,knowledge engineering,ontology,medical and health sciences,health sciences,public health,epidemiology,pandemics,social sciences,sociology,anthropology,agricultural sciences,animal and dairy science,domestic animals,animal husbandry,medical and health sciences,health sciences,public health,epidemiology,zoonosis,engineering and technology,industrial biotechnology,bioprocessing technologies,fermentation,natural sciences,biological sciences,biochemistry,biomolecules,natural sciences,physical sciences,optics,microscopy,engineering and technology,materials engineering,textiles,engineering and technology,nanotechnology,nano-materials,engineering and technology,civil engineering,water engineering,irrigation,engineering and technology,environmental engineering,ecosystem-based management,climate change adaptation,natural sciences,physical sciences,astronomy,planetary sciences,planets,engineering and technology,environmental engineering,remote sensing,natural sciences,earth and related environmental sciences,engineering and technology,electrical engineering, electronic engineering, information engineering,information engineering,telecommunications,radio technology,radio frequency,engineering and technology,nanotechnology,nano-materials,nanocrystals,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,physical sciences,theoretical physics,particle physics,photons,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,biological sciences,biophysics,natural sciences,computer and information sciences,artificial intelligence,social sciences,psychology,cognitive psychology,mental processes,natural sciences,biological sciences,neurobiology,cognitive neuroscience,natural sciences,biological sciences,neurobiology,computational neuroscience,natural sciences,physical sciences,optics,microscopy,engineering and technology,nanotechnology,nano-materials,natural sciences,chemical sciences,catalysis,electrocatalysis,natural sciences,biological sciences,microbiology,virology,natural sciences,biological sciences,genetics,DNA,natural sciences,biological sciences,genetics,genomes,engineering and technology,environmental engineering,energy and fuels,energy conversion,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,natural sciences,physical sciences,optics,microscopy,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,medical and health sciences,basic medicine,physiology,humanities,history and archaeology,history,natural sciences,physical sciences,astronomy,planetary sciences,meteorites,natural sciences,earth and related environmental sciences,geology,mineralogy,humanities,philosophy, ethics and religion,religions,natural sciences,biological sciences,ecology,ecosystems,natural sciences,chemical sciences,electrochemistry,electrolysis,agricultural sciences,agriculture, forestry, and fisheries,fisheries,social sciences,sociology,governance,social sciences,sociology,anthropology,agricultural sciences,agriculture, forestry, and fisheries,agriculture,social sciences,law,humanities,history and archaeology,history,natural sciences,biological sciences,ecology,ecosystems,natural sciences,biological sciences,zoology,invertebrate zoology,engineering and technology,nanotechnology,nano-materials,two-dimensional nanostructures,graphene,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,optical sensors,engineering and technology,materials engineering,coating and films,natural sciences,physical sciences,optics,laser physics,natural sciences,biological sciences,genetics,mutation,natural sciences,biological sciences,genetics,nucleotides,natural sciences,biological sciences,genetics,RNA,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,engineering and technology,materials engineering,fibers,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,computer and information sciences,software,natural sciences,computer and information sciences,artificial intelligence,heuristic programming,engineering and technology,nanotechnology,nanophotonics,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,biological sciences,genetics,mutation,natural sciences,biological sciences,ecology,social sciences,economics and business,economics,bioeconomy,natural sciences,chemical sciences,inorganic chemistry,metalloids,natural sciences,earth and related environmental sciences,oceanography,natural sciences,earth and related environmental sciences,geochemistry,biogeochemistry,engineering and technology,environmental engineering,water treatment processes,wastewater treatment processes,natural sciences,biological sciences,genetics,DNA,medical and health sciences,health sciences,nutrition,natural sciences,earth and related environmental sciences,environmental sciences,pollution,natural sciences,biological sciences,ecology,ecosystems,humanities,history and archaeology,history,medical and health sciences,clinical medicine,surgery,engineering and technology,mechanical engineering,applied mechanics,medical and health sciences,medical biotechnology,tissue engineering,natural sciences,chemical sciences,polymer sciences,engineering and technology,industrial biotechnology,biomaterials,social sciences,sociology,anthropology,social sciences,sociology,demography,human migrations,humanities,history and archaeology,history,social sciences,other social sciences,development studies,development theories,post-colonial theories,natural sciences,chemical sciences,inorganic chemistry,alkali metals,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,aircraft,engineering and technology,electrical engineering, electronic engineering, information engineering,information engineering,telecommunications,radio technology,natural sciences,physical sciences,optics,microscopy,natural sciences,physical sciences,electromagnetism and electronics,spintronics,medical and health sciences,clinical medicine,oncology,engineering and technology,nanotechnology,nano-materials,natural sciences,biological sciences,zoology,entomology,medical and health sciences,basic medicine,pathology,natural sciences,biological sciences,biochemistry,biomolecules,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,medical and health sciences,clinical medicine,oncology,skin cancer,melanoma,natural sciences,biological sciences,genetics,RNA,transcriptomes,medical and health sciences,basic medicine,physiology,homeostasis,medical and health sciences,clinical medicine,oncology,natural sciences,biological sciences,microbiology,bacteriology,natural sciences,biological sciences,biochemistry,biomolecules,carbohydrates,natural sciences,biological sciences,biological behavioural sciences,ethology,biological interactions,natural sciences,biological sciences,zoology,mammalogy,social sciences,economics and business,business and management,employment,natural sciences,biological sciences,neurobiology,medical and health sciences,basic medicine,neurology,dementia,alzheimer,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,medical and health sciences,clinical medicine,obstetrics,medical and health sciences,clinical medicine,embryology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,chemical sciences,catalysis,photocatalysis,engineering and technology,environmental engineering,energy and fuels,natural sciences,biological sciences,botany,social sciences,political sciences,government systems,democracy,natural sciences,chemical sciences,physical chemistry,photochemistry,natural sciences,chemical sciences,polymer sciences,natural sciences,biological sciences,neurobiology,medical and health sciences,basic medicine,physiology,pathophysiology,medical and health sciences,basic medicine,immunology,medical and health sciences,basic medicine,pathology,medical and health sciences,basic medicine,neurology,parkinson,humanities,history and archaeology,history,natural sciences,physical sciences,thermodynamics,natural sciences,physical sciences,astronomy,planetary sciences,planets,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,natural sciences,chemical sciences,inorganic chemistry,metalloids,natural sciences,computer and information sciences,software,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,medical and health sciences,clinical medicine,oncology,medical and health sciences,basic medicine,pathology,social sciences,sociology,social issues,corruption,social sciences,political sciences,public administration,bureaucracy,social sciences,sociology,demography,human migrations,humanities,philosophy, ethics and religion,philosophy,epistemology,social sciences,economics and business,economics,macroeconomics,humanities,history and archaeology,history,humanities,philosophy, ethics and religion,philosophy,history of philosophy,modern philosophy,humanities,arts,modern and contemporary art,natural sciences,physical sciences,theoretical physics,particle physics,natural sciences,physical sciences,astronomy,astrophysics,dark matter,natural sciences,biological sciences,neurobiology,medical and health sciences,clinical medicine,ophthalmology,glaucoma,medical and health sciences,basic medicine,toxicology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,medical and health sciences,health sciences,infectious diseases,malaria,social sciences,sociology,demography,mortality,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,vaccines,humanities,history and archaeology,history,humanities,philosophy, ethics and religion,religions,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,autonomous robots,drones,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,computer and information sciences,software,software applications,virtual reality,natural sciences,physical sciences,electromagnetism and electronics,spintronics,natural sciences,physical sciences,quantum physics,natural sciences,physical sciences,thermodynamics,natural sciences,physical sciences,condensed matter physics,quantum gases,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,aircraft,natural sciences,physical sciences,electromagnetism and electronics,optoelectronics,medical and health sciences,clinical medicine,ophthalmology,engineering and technology,nanotechnology,nano-materials,engineering and technology,other engineering and technologies,microtechnology,organ on a chip,medical and health sciences,medical biotechnology,implants,natural sciences,physical sciences,optics,microscopy,super resolution microscopy,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,antibiotics,natural sciences,physical sciences,electromagnetism and electronics,semiconductivity,engineering and technology,nanotechnology,nanoelectronics,social sciences,law,natural sciences,computer and information sciences,software,medical and health sciences,health sciences,infectious diseases,RNA viruses,HIV,natural sciences,biological sciences,biological behavioural sciences,ethology,biological interactions,engineering and technology,materials engineering,composites,engineering and technology,materials engineering,metallurgy,natural sciences,chemical sciences,physical chemistry,humanities,history and archaeology,history,humanities,history and archaeology,archaeology,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,clinical medicine,oncology,humanities,history and archaeology,history,natural sciences,chemical sciences,polymer sciences,natural sciences,physical sciences,theoretical physics,particle physics,neutrinos,natural sciences,physical sciences,theoretical physics,particle physics,particle accelerator,natural sciences,physical sciences,theoretical physics,particle physics,gluons,natural sciences,physical sciences,theoretical physics,particle physics,quarks,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,supercomputers,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,medical and health sciences,basic medicine,physiology,homeostasis,social sciences,political sciences,political transitions,armed conflicts,natural sciences,physical sciences,optics,cavity optomechanics,engineering and technology,nanotechnology,nano-materials,natural sciences,physical sciences,optics,laser physics,natural sciences,biological sciences,biochemistry,biomolecules,lipids,medical and health sciences,clinical medicine,oncology,medical and health sciences,basic medicine,immunology,immunotherapy,natural sciences,computer and information sciences,software,medical and health sciences,clinical medicine,oncology,liver cancer,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,cardiac arrhythmia,natural sciences,chemical sciences,inorganic chemistry,alkaline earth metals,engineering and technology,nanotechnology,nano-materials,medical and health sciences,basic medicine,physiology,homeostasis,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,humanities,history and archaeology,history,ancient history,humanities,languages and literature,literature studies,literary genres,essays,humanities,languages and literature,literature studies,history of literature,humanities,arts,performing arts,dramaturgy,engineering and technology,materials engineering,composites,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,engineering and technology,mechanical engineering,manufacturing engineering,additive manufacturing,medical and health sciences,medical biotechnology,implants,natural sciences,physical sciences,acoustics,ultrasound,engineering and technology,nanotechnology,nano-materials,nanocrystals,natural sciences,earth and related environmental sciences,geology,mineralogy,natural sciences,mathematics,pure mathematics,geometry,natural sciences,biological sciences,genetics,natural sciences,biological sciences,cell biology,cell signaling,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,physical sciences,molecular and chemical physics,natural sciences,biological sciences,biophysics,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,optical sensors,medical and health sciences,clinical medicine,oncology,skin cancer,melanoma,natural sciences,physical sciences,optics,laser physics,humanities,languages and literature,linguistics,natural sciences,physical sciences,optics,microscopy,engineering and technology,materials engineering,coating and films,natural sciences,physical sciences,electromagnetism and electronics,spintronics,natural sciences,physical sciences,electromagnetism and electronics,semiconductivity,natural sciences,physical sciences,optics,spectroscopy,humanities,languages and literature,linguistics,humanities,history and archaeology,history,medical and health sciences,health sciences,public health,epidemiology,pandemics,social sciences,political sciences,political transitions,revolutions,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,satellite technology,natural sciences,physical sciences,plasma physics,social sciences,economics and business,business and management,entrepreneurship,agricultural sciences,agriculture, forestry, and fisheries,fisheries,social sciences,sociology,governance,engineering and technology,environmental engineering,ecosystem-based management,climate change adaptation,agricultural sciences,agriculture, forestry, and fisheries,agriculture,social sciences,political sciences,political policies,civil society,natural sciences,biological sciences,neurobiology,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,humanities,history and archaeology,history,engineering and technology,nanotechnology,nano-processes,natural sciences,chemical sciences,organic chemistry,organic reactions,engineering and technology,materials engineering,coating and films,engineering and technology,nanotechnology,nano-materials,bulk nanostructured materials,natural sciences,physical sciences,molecular and chemical physics,natural sciences,mathematics,pure mathematics,mathematical analysis,diffe

In [51]:
refs = paths.split(',')
refs = set(refs)
refs = [r.strip() for r in refs]
refs

['',
 'liver cancer',
 'political economy',
 'physiotherapy',
 'crisis management',
 'skin cancer',
 'inflammatory bowel disease',
 'thermochemistry',
 'hepatology',
 'numerical analysis',
 'cardiovascular diseases',
 'basic medicine',
 'biodiversity conservation',
 'super-Earths',
 'physical geography',
 'social issues',
 'gastroenterology',
 'economic impact of epidemics',
 'geometry',
 'fertility',
 'quasiparticles',
 'earth and related environmental sciences',
 'generative artificial intelligence',
 'piezoelectrics',
 'data networks',
 'ethology',
 'entomology',
 'atmospheric sciences',
 'rheumatology',
 'neurology',
 'human migrations',
 'cinematography',
 'quantum field theory',
 'sexual health',
 'essays',
 'nonlinear optics',
 'social inequalities',
 'materials engineering',
 'ultrasound',
 'psychiatry',
 'marine biology',
 'immunology',
 'bioeconomy',
 'optical sensors',
 'photocatalysis',
 'electric power generation',
 'nutrition',
 'homeostasis',
 'data science',
 'carbon capture engineering',
 'geothermal energy',
 'air pollution engineering',
 'philosophy',
 'post-colonial theories',
 'social anthropology',
 'zoonosis',
 'irrigation',
 'multiphysics',
 'judaism',
 'cereals',
 'medieval philosophy',
 'religions',
 'geomorphology',
 'inorganic chemistry',
 'power engineering',
 'electron microscopy',
 'quarks',
 'mobile network',
 'photons',
 'employment',
 'public health',
 'synthetic biology',
 'science and technology studies',
 'other humanities',
 'radiochemistry',
 'nuclear chemistry',
 'graph theory',
 'prehistory',
 'terrorism',
 'analogue electronics',
 'infectious diseases',
 'geotechnics',
 'psychoanalysis',
 'planetary sciences',
 'economics',
 'ethical principles',
 'bulk nanostructured materials',
 'post-transition metals',
 'modern philosophy',
 'satellite navigation system',
 'domestic animals',
 'paediatrics',
 'public services',
 'photochemistry',
 'arteriosclerosis',
 'big data',
 'parasitology',
 'political philosophy',
 'histology',
 'pharmacology and pharmacy',
 'dark matter',
 'vehicle engineering',
 'fluid dynamics',
 'super resolution microscopy',
 'industrial crops',
 'epidemiology',
 'WiFi',
 'machine learning',
 'breast cancer',
 'nano-processes',
 'combinatorics',
 'cognitive psychology',
 'general language studies',
 'human rights',
 'primatology',
 'physical oceanography',
 'forestry',
 'differential equations',
 'gluons',
 'industrial biotechnology',
 'topology',
 'photovoltaic',
 'textiles',
 'mathematical model',
 'electrodialysis',
 'flood risk management',
 'computer security',
 'biocomposites',
 'subtractive manufacturing',
 'natural satellites',
 'nanotechnology',
 'nuclear engineering',
 'dynamical systems',
 'civil engineering',
 'monetary and finances',
 'video games',
 'molecular evolution',
 'obstetrics',
 'penology',
 'physical chemistry',
 'exoplanetology',
 'astrophysics',
 'quantum computers',
 'higgs bosons',
 'anatomy and morphology',
 'structural biology',
 'ancient history',
 'medical biotechnology',
 'optical astronomy',
 'drug resistance',
 'sustainable architecture',
 'agriculture',
 'national state of emergency',
 'rotorcraft',
 'metabolomes',
 'computational science',
 'plate tectonics',
 'vaccines',
 'electronic engineering',
 'pollution',
 'business and management',
 'metallurgy',
 'climatology',
 'software applications',
 'bioreactors',
 'organic reactions',
 'media and communications',
 'human rights violations',
 'cetology',
 'thermodynamic engineering',
 'linguistics',
 'solar astronomy',
 'botany',
 'epistemology',
 'structural health monitoring',
 'performing arts',
 'influenza',
 'cryptography',
 'fibers',
 'ecology',
 'social biomedical sciences',
 'renewable energy',
 'optical networks',
 'graphene',
 'control systems',
 'glaciology',
 'aerospace engineering',
 'visual arts',
 'political sciences',
 'bioarchaeology',
 'fluid mechanics',
 'parkinson',
 'polylactic acid',
 'chemical sciences',
 'cavity optomechanics',
 'signal processing',
 'fourier analysis',
 'wastewater treatment processes',
 'environmental sciences',
 'food technology',
 'productivity',
 'bioprocessing technologies',
 'christianity',
 'particle accelerator',
 'natural sciences',
 'heat engineering',
 'cartography',
 'polymer sciences',
 'mineralogy',
 'knowledge engineering',
 'biosphera',
 'water treatment processes',
 'hydrology',
 'giant planets',
 'deep learning',
 'lab on a chip',
 'microbiomes',
 'galaxy evolution',
 'computational neuroscience',
 'agroecology',
 'isotope geochemistry',
 'other engineering and technologies',
 'volcanology',
 'arboriculture',
 'paleoclimatology',
 'archaeology',
 'pneumology',
 'implants',
 'foreign policy',
 'data protection',
 'energy and fuels',
 'synthetic dyes',
 'additive manufacturing',
 'proteins',
 'physical anthropology',
 'electrolysis',
 'colors',
 'transition metals',
 'robotics',
 'mathematical logic',
 'international law',
 'contemporary philosophy',
 'observational astronomy',
 'eukaryotic genomes',
 'dementia',
 'social geography',
 'pharmaceutical drugs',
 'enzymes',
 'health sciences',
 'nongovernmental organizations',
 'cardiac arrhythmia',
 'ecosystem-based management',
 'human rights law',
 'digital humanities',
 'social psychology',
 'development theories',
 'diabetes',
 'inorganic compounds',
 'computer hardware',
 'schizophrenia',
 'alkali metals',
 'mobile phones',
 'epigenetics',
 'social developments',
 'automation',
 'alkaline earth metals',
 'geochronology',
 'nano-materials',
 'civil society organisations',
 'biosensors',
 'toxicology',
 'bioremediation',
 'mental processes',
 'wind energy',
 'nursing',
 'invertebrate zoology',
 'zoology',
 'animal feed',
 'diagnostic imaging',
 'nanophotonics',
 'stroke',
 'critical care medicine',
 'computer processors',
 'agricultural sciences',
 'drones',
 'telecommunications networks',
 'psychology',
 'biological morphology',
 'epigenomes',
 'mathematics',
 'engineering and technology',
 'corruption',
 'transcriptomes',
 'epilepsy',
 'obesity',
 'chemical process engineering',
 'ethnology',
 'exposomes',
 'educational sciences',
 'personalized medicine',
 'biological interactions',
 'logarithmic functions',
 'environmental law',
 'statistics and probability',
 'antivirals',
 'internet',
 'transport',
 'spectroscopy',
 'computer and information sciences',
 'globalization',
 'recycling',
 'aeronautical engineering',
 'data processing',
 'psychotherapy',
 'revolutions',
 'molecular neuroscience',
 'antibiotics',
 'kidney diseases',
 'vegetable growing',
 'pedagogy',
 'sociology',
 'alzheimer',
 'manufacturing engineering',
 'metalloids',
 'waste management',
 'gamma-ray astronomy',
 'family planning',
 'carbohydrates',
 'nephrology',
 'ethnoarchaeology',
 'lipids',
 'literature studies',
 'genomes',
 'mathematical analysis',
 'chemical engineering',
 'tuberculosis',
 'racial inequality',
 'geophysics',
 'medical engineering',
 'food packaging',
 'elections',
 'halogens',
 'business models',
 'reinforcement learning',
 'ideologies',
 'speleology',
 'didactics',
 'nanoelectronics',
 'telecommunications',
 'library sciences',
 'synthetic fuels',
 'ethnomusicology',
 'ecosystems',
 'innovation management',
 'seismology',
 'physiology',
 'z bosons',
 'spacecraft',
 'amorphous solids',
 'coronaviruses',
 'computational intelligence',
 'catalysis',
 'simulation software',
 'ethics and religion',
 'soft robotics',
 'mammalogy',
 'petroleum',
 'superconductivity',
 'genetic engineering',
 'dramaturgy',
 'nuclear medicine',
 'autonomous vehicles',
 'water engineering',
 'polyurethane',
 'virology',
 'supervised learning',
 'journalism',
 'computational fluid dynamics',
 'radiation chemistry',
 'oncology',
 'cardiology',
 'paleoecology',
 'genetics',
 'energy conversion',
 'entrepreneurship',
 'radar',
 'angiology',
 'immunisation',
 'animal husbandry',
 'stem cells',
 'lung cancer',
 'dairy',
 'black holes',
 'census',
 'crystallography',
 'tribology',
 'applied mathematics',
 'fossil energy',
 'urban studies',
 'microfluidics',
 'RNA',
 'duchenne muscular dystrophy',
 'asteroids',
 'cognitive neuroscience',
 'databases',
 'dermatology',
 'animal and dairy science',
 'demography',
 'bioplastics',
 'radio technology',
 'RNA viruses',
 'transplantation',
 'classical mechanics',
 'bureaucracy',
 'metaphysics',
 'family studies',
 'biosensing',
 'reproductive medicine',
 'molecular biology',
 'coal',
 'ergonomics',
 'biogeochemistry',
 'sensors',
 'planetary geology',
 'geology',
 'evolutionary biology',
 'applied mechanics',
 'palaeontology',
 'condensed matter physics',
 'analytical chemistry',
 'law',
 'islam',
 'fruit growing',
 'quantum gases',
 'literary genres',
 'cells technologies',
 'information engineering',
 'age inequality',
 'development studies',
 'physical sciences',
 'microscopy',
 'DNA',
 'embryology',
 'neutrinos',
 'endocrinology',
 'solar energy',
 'cultural and economic geography',
 'pure mathematics',
 'pandemics',
 'grains and oilseeds',
 'asthma',
 'prostate cancer',
 'biomaterials',
 'data mining',
 'ornithology',
 'supercomputers',
 'smart sensors',
 'functional morphology',
 'history',
 'navigation systems',
 'contemporary history',
 'muscular dystrophies',
 'microeconomics',
 'edge artificial intelligence',
 'internet of things',
 'motion analysis',
 'medical and health sciences',
 'optics',
 'tissue engineering',
 'galactic astronomy',
 'ethics',
 'environmental governance',
 'astronautical engineering',
 'surgery',
 'satellite technology',
 'environmental engineering',
 'semiconductivity',
 'stellar astronomy',
 'melanoma',
 'leukemia',
 'nucleotides',
 'aliphatic compounds',
 'astrochemistry',
 'system software',
 'soft matter physics',
 'hydrometeorology',
 'medical laboratory technology',
 'radiology',
 'development economics',
 'remote sensing',
 'supernova',
 'heredity',
 'information engineering',
 'theoretical physics',
 'pathophysiology',
 'radio frequency',
 'teleology',
 'agricultural biotechnology',
 'optoelectronics',
 'climatic changes',
 'ophthalmology',
 'pharmacokinetics',
 'governance',
 'data exchange',
 'cell biology',
 'aircraft',
 'biological sciences',
 'colorectal cancer',
 'democracy',
 'economics and business',
 'forestry',
 'public policies',
 'organometallic chemistry',
 'other social sciences',
 'proteomics',
 'public administration',
 'arts',
 'molecular genetics',
 'mechanical engineering',
 'gynaecology',
 'nanocrystals',
 'ethnolichenology',
 'amines',
 'algebraic geometry',
 'history and archaeology',
 'microbiology',
 'developmental biology',
 'molecular and chemical physics',
 'fermions',
 'organic chemistry',
 'acoustics',
 'quantum chemistry',
 'cell signaling',
 'transportation engineering',
 'postnatal care',
 'production economics',
 'automotive engineering',
 'nanomedicine',
 'fisheries',
 'heuristic programming',
 'electrical engineering',
 'multiple sclerosis',
 'arithmetics',
 'sustainable building',
 'government systems',
 'fodder',
 'gender inequality',
 'biomass',
 'biomolecules',
 'bacteriology',
 'algebra',
 'glacial geology',
 'discrete mathematics',
 'autonomous robots',
 'women’s studies',
 'leptons',
 'industrial relations',
 'particle physics',
 'electric power transmission',
 'pathology',
 'hydrocarbons',
 'history of philosophy',
 'composites',
 'bladder cancer',
 'clinical medicine',
 'horticulture',
 'astronomy',
 'sustainable economy',
 'electrocatalysis',
 'two-dimensional nanostructures',
 'biophysics',
 'global development studies',
 'virtual reality',
 'political communication',
 'electrochemistry',
 'sustainable agriculture',
 'climatic change mitigation',
 'artificial intelligence',
 'hydrogen energy',
 'remanufacturing',
 'speech-language pathology',
 'phonetics',
 'chromosomes',
 'political policies',
 'oceanography',
 'biochemistry',
 'molecular spintronics',
 'thermodynamics',
 'modern history',
 'humanities',
 'combined heat and power',
 'alcohols',
 'electric energy',
 'software',
 'nanocomposites',
 'human trafficking',
 'mycology',
 'architecture engineering',
 'fermentation',
 'computer vision',
 'behavioural ecology',
 'modern and contemporary art',
 'plasma physics',
 'laboratory samples analysis',
 'environmental biotechnology',
 'multidrug resistance',
 'amorphous semiconductors',
 'laser physics',
 'magnetic resonance imaging',
 'calorimetry',
 'ethical theories',
 'mortality',
 'quantum physics',
 'noble gases',
 'partial differential equations',
 'habitat conservation',
 'HIV',
 'civil society',
 'macroeconomics',
 'meteorology',
 'vascular diseases',
 'and fisheries',
 'separation technologies',
 'electromagnetism and electronics',
 'organ on a chip',
 'hybrid energy',
 'eastern religions',
 'gene therapy',
 'criminology',
 'electronic engineering',
 'comparative morphology',
 'antibiotic resistance',
 'ontology',
 'agronomy',
 'unemployment',
 'geochemistry',
 'sedimentology',
 'climate change adaptation',
 'medical genetics',
 'health economics',
 'phycology',
 'fuel cells',
 'atomic physics',
 'armed conflicts',
 'anthropology',
 'pandemic risks',
 'meteorites',
 'biocatalysis',
 'mutation',
 'history of literature',
 'aldehydes',
 'microelectronics',
 'psycholinguistics',
 'taxation',
 'neurobiology',
 'waste treatment processes',
 'organic amorphous solids',
 'glaucoma',
 'mathematical physics',
 'musicology',
 'biomass energy',
 'microtechnology',
 'gender studies',
 'immunotherapy',
 'biological behavioural sciences',
 'structural engineering',
 'coating and films',
 'quantum optics',
 'medieval history',
 'geographic information systems',
 'political transitions',
 'malaria',
 'planets',
 'languages and literature',
 'diagnostic technologies',
 'econometrics',
 'distillation',
 'social sciences',
 'plant breeding',
 'art history',
 'ecological restoration',
 'ceramics',
 'biofuels',
 'spintronics',
 'physical cosmology',
 'global navigation satellite system',
 'desalination',
 'phonology']

In [52]:
print (len(refs))

688

In [54]:
projects_no_widening['fundingScheme'].unique()

array(['HORIZON-ERC-POC', 'HORIZON-EIC', 'HORIZON-ERC', 'HORIZON-ERC-SYG',
       'HORIZON-IA', 'HORIZON-JU-IA', 'HORIZON-TMA-MSCA-Cofund-D',
       'HORIZON-TMA-MSCA-PF-GF', 'HORIZON-TMA-MSCA-PF-EF',
       'HORIZON-JU-RIA', 'HORIZON-EIC-ACC', 'HORIZON-TMA-MSCA-SE',
       'HORIZON-RIA', 'HORIZON-TMA-MSCA-DN', 'HORIZON-JU-CSA',
       'HORIZON-CSA', 'HORIZON-TMA-MSCA-DN-JD', 'HORIZON-TMA-MSCA-DN-ID',
       'HORIZON-TMA-MSCA-Cofund-P', 'HORIZON-EIT-KIC'], dtype=object)

In [59]:
projects_filt = projects_no_widening[projects_no_widening['fundingScheme'].isin(['HORIZON-RIA','RIA','HORIZON-EIC'])]

In [60]:
projects_filt

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
3,101257710,GREENDIGO,SIGNED,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",2026-02-23 17:36:55,281931,10.3030/101257710,"enzymatic dyeing, biocatalysis, textile biotec..."
1453,101257928,NanoFlash,SIGNED,Cell-targeted Biophotonic Nanoparticles for Vi...,2026-05-01,2030-04-30,"2999978,75",2999978,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NanoFlash aims to develop disruptive nano-enab...,2025-12-22 15:23:57,281936,10.3030/101257928,"photoactivable polymer nanoparticles, cell tar..."
1455,101223249,2D-ADDICT,SIGNED,TWO-Dimensional materials for ADvanced DevIces...,2025-11-01,2028-10-31,0,"3970518,04",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,2025-11-25,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The grand challenge facing the electronics ind...,2026-01-14 10:02:44,282684,NaN,"Low-power electronics, two-dimensional materia..."
1530,101221404,AstrAware,SIGNED,An On-board Dynamic Vision Sensor Suite for En...,2025-10-01,2028-09-30,0,"2957757,13",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,2025-07-30,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The current overpopulation of satellites in or...,2025-10-20 17:38:03,274812,10.3030/101221404,"Debris, Detection, Neuromorphic, Startracker, ..."
1592,101257287,ULTRAPURE,SIGNED,INTEGRATED SOURCES FOR ULTRAPURE OSCILLATIONS ...,2026-02-01,2029-01-31,"3054936,25",3054935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Many high-performance photonics applications w...,2026-01-05 11:56:18,281942,10.3030/101257287,"Stimulated Brillouin Scattering, lithium tanta..."
1678,101258353,PHINDER,SIGNED,Picosecond-scale Photonic Heterogeneous Integr...,2026-04-01,2030-03-31,"3129503,75","3129503,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-21,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Advanced applications—ranging from 5D-imaging ...,2026-02-03 05:45:15,283727,10.3030/101258353,"optoelectronics, heterogeneous integration, co..."
1702,101257985,SuperICQ,SIGNED,Superconducting Integrated Circuits for Scalab...,2026-03-01,2030-02-28,"2998012,75","2998012,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Superconducting circuits based on Josephson ju...,2026-01-14 10:03:57,282696,10.3030/101257985,"JoFET, 200 mm wafer-scale, graphene, supercond..."
1713,101235287,THUNDER,SIGNED,INNOVATION IN E-MEOH PRODUCTION BY ONE-POT TAN...,2025-10-01,2029-09-30,3992190,3992190,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,2025-08-22,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,"THUNDER aims to develop an innovative, modular...",2025-11-26 11:07:05,276090,10.3030/101235287,"e-MeOH, process intensification, 3D-printed re..."
1854,101259018,OutMARCH,SIGNED,OutMARCH-ing cancer: Towards innovative membra...,2026-05-01,2030-04-30,2999050,2999050,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-23,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,The OutMARCH project pioneers a paradigm-shift...,2026-01-14 10:04:01,282695,10.3030/101259018,"Ubiquitination, lysosomal degradation, nanobodies"
1868,101259117,REMMIA,SIGNED,REcycling perManent Magnets: an Innovative App...,2026-03-01,2030-02-28,"2991615,75","2991615,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-14,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Rare earth elements (REE) are crucial for mode...,2026-01-26 12:44:31,283247,10.3030/101259117,magnet recycling; magneto-electrochemistry; ra...
1882,101259120,FeROS,SIGNED,Prodrugs oF antiparasitic RedOx-active compoundS,2026-03-01,2030-02-28,"3046491,25","3046491,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-14,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"With 600,000 deaths per year, malaria remains ...",2026-01-27 09:55:21,283249,10.3030/101259120,"antiparasitic drugs, malaria, neglected parasi..."
1917,101223135,C-SINC,SIGNED,Concrete products through sustainable and inno...,2025-10-01,2029-09-30,0,"3997434,44",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-11-24,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The cement industry is a major contributor to ...,2026-01-12 11:36:02,279240,10.3030/101223135,"CO2 Sequestration,Mineral Carbonation,Accelera..."
1936,101259183,NEQIOS,SIGNED,Neuromorphic Quantum-Inspired Optimization and...,2026-01-01,2030-12-31,"3358894,25","3333894,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NEQIOS introduces a radically new approach to ...,2025-12-22 15:23:57,281944,10.3030/101259183,Neuromorphic Computing; Quantum-Inspired Optim...
2002,101223119,STORM,SIGNED,Solar Weather Forecasting Mission,2025-11-01,2028-04-30,0,"3549793,55",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,2025-11-25,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"In STORM, satellite constellation operation in...",2025-12-10 11:02:05,279234,10.3030/101223119,"Space Weather, Solar Storms, Advanced Space Pr..."
2015,101259077,CHEM-SCAN,SIGNED,HIGH-RESOLUTION FUNCTIONAL OPTICAL IMAGING OF ...,2026-03-01,2030-02-28,"2998207,5","2998207,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The development of chemoresistance, i.e. the a...",2025-12-22 15:23:57,281941,10.3030/101259077,"functional fluorescent probes, chemoresistance..."
2155,101181686,ArcticKnows,SIGNED,Just knowledge co-creation for a regenerative ...,2025-10-01,2028-09-30,0,"2809495,63",HORIZON.2.6,HORIZON-CL6-2024-COMMUNITIES-01-3,2025-08-19,HORIZON,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-RIA,"ArcticKnows will empower Coastal, Local and In...",2025-08-28 16:06:09,276067,10.3030/101181686,"Regenerative economy, Environmental justice, M..."
2188,101257530,ALERT,SIGNED,MULTIANALYTE DIGITAL SENSING WITH QR-CODE MICR...,2026-03-01,2029-02-28,"2917386,25","2917386,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"""ALERT introduces a groundbreaking leap in med...",2025-12-22 15:23:57,281930,10.3030/101257530,"Digital sensing, digital microneedles, QR code..."
2221,101236115,C2FUe-LS,SIGNED,Turning recycled carbon into valuable fuels fo...,2025-10-01,2029-09-30,"4028302,5",4028302,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,2025-09-26,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,+C2Fue-LS aims to develop a direct cold plasma...,2026-02-03 13:56:56,276516,10.3030/101236115,NaN
2232,101258419,INTEGRAL,SIGNED,INTEGRATED PHOTONICS FOR SIGNAL PROCESSING AND...,2026-03-01,2029-02-28,2999500,2999500,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Optical Coherence Tomography (OCT) is a powerf...,2025-12-22 15:23:57,281943,10.3030/101258419,"lasers, photonics, OCT. biomedical, tunable la..."
2309,101259068,DRIVIN CAR,SIGNED,DRIVIN' CAR: Developing robust in vivo nanomed...,2026-03-01,2030-02-28,"3000347,5",3000346,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-18,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,DRIVIN’ CAR aims to transform immunotherapy by...,2026-01-12 05:35:38,282625,10.3030/101259068,"Nanoparticles, in vivo CAR cell therapy, CAR T..."
2317,101257413,HEARTCORE,SIGNED,HUMAN-BASED ADVANCED CARDIAC SAFETY PLATFORM I...,2026-06-01,2030-05-31,"2993436,25",2993436,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Cardiac safety testing still relies on animal ...,2026-01-05 11:56:09,281929,10.3030/101257413,MEA; cardiac organoids; human pluripotent stem...
2322,101257628,AMFactory,SIGNED,Engineering bioreactor mass production of arbu...,2026-05-01,2029-04-30,2993767,2993767,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-18,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Microbial inoculants containing arbuscular myc...,2026-01-05 11:58:05,281932,10.3030/101257628,"lipid biosynthesis, signaling compounds, micro..."
2346,101258189,CarboNcare,SIGNED,CARBON-EFFICIENT BIOPRODUCTION OF CHEMICALS FR...,2026-05-01,2030-04-30,"3135362,35","3135362,35",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,A major challenge in carbon-based bioproductio...,2026-01-08 18:05:13,281935,10.3030/101258189,"Metabolic engineering, Respiro-fermentation, G..."
2354,101258103,PROPANTHERA,SIGNED,Retrograde atrophy induction: a paradigm shift...,2026-03-01,2029-02-28,3140625,3140625,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-28,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Pancreatic cancer (PaC) is a leading cause of ...,2026-02-06 13:24:36,283675,10.3030/101258103,"thermal ablation, medical devices, pancreatic ..."
2357,101257982,MECH-QUBIT,SIGNED,MECHanical QUBIT With Enhanced Coherence,2026-02-01,2030-01-31,3072590,3072590,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"Condensed-matter qubits, such as transmons and...",2025-12-22 15:23:57,281938,10.3030/101257982,NaN
2496,101256857,ULYSSES,SIGNED,Ultrasensitive Luminescence-based Yeast Sensor...,2026-05-01,2029-04-30,"2991106,25","2991106,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,ULYSSES is a pioneering project aimed at devel...,2026-01-27 09:55:20,283248,10.3030/101256857,"Biosensor, Cancer Screening, Breast Cancer, Pr..."
2735,101216412,HARARA,SIGNED,Co-creating inclusive local climate adaptation...,2026-01-01,2028-12-31,"1999658,75","1999658,75",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,2025-05-07,HORIZON,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,"European societies, especially in urban areas,...",2026-01-07 15:05:24,272926,10.3030/101216412,migration; heat; air temperature; atmospheric ...
2988,101223271,CERBERUS,SIGNED,Unlocking the Full Potential of Edge AI throug...,2026-02-01,2030-01-31,0,"3997743,75",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,2025-06-18,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The introduction of the on-device AI paradigm ...,2025-07-23 15:37:47,273210,10.3030/101223271,"In-memory computing, edge AI, MoS2, hBN, graph..."
3018,101219355,SOLARSPOON,SIGNED,Solar-driven synthesis of proteins and lipids ...,2025-11-01,2029-10-31,0,"3999731,63",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,2025-06-18,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,Biohybrid systems offer unique energy-efficien...,2025-09-01 23:34:51,273209,10.3030/101219355,"Biohybrid, photoelectrochemistry, proteins, li..."
3108,101223091,C5,SIGNED,Clever Combination of Synthetic Compartmentali...,2025-11-01,2029-10-31,0,"3930291,98",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,NaN,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The C5 Pathfinder project aims to revolutioniz...,2025-09-01 23:36:01,272683,10.3030/101223091,"Synthetic compartmentalization, Metabolic engi..."
3229,101223335,CONCERTO,SIGNED,CarbOn Negative CemEnt fRom ulTra-mafic rOcks,2025-10-01,2029-09-30,0,"4521199,7",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-06-13,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The majority of CO2 emissions associated with ...,2025-11-26 11:04:34,273192,10.3030/101223335,"Silico-magnesia cement, Ultramafic rocks, Low-..."
3316,101216923,URBAN PROSUMERS,SIGNED,URBAN PROSUMERS – towards a knowledge transfer...,2025-10-01,2028-03-31,"1999847,5","1999847,25",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,2025-05-07,HORIZON,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,The URBAN PROSUMERS project supports the imple...,2025-06-05 15:00:30,272773,10.3030/101216923,"Climate Neutral and Smart Cities, citizen enga..."
3343,101221957,MOJITO,SIGNED,Decarbonized liMe PrOduction through enhanced ...,2025-10-01,2028-09-30,0,"2235763,33",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-04-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The MOJITO project aims to validate a laborato...,2025-11-26 11:04:01,272918,10.3030/101221957,"lime, microwaves, calcination, machine learnin..."
3620,101223193,SUN2CN,SIGNED,Fully-Integrated PV-EC Device for the Producti...,2025-11-01,2029-10-31,0,"3997401,47",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,2025-06-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The SUN2CN project aims to deliver a standalon...,2025-06-18 17:23:13,273191,10.3030/101223193,"Photovoltaic–electrochemical device, Organoni..."
5076,101258941,HeartVision,SIGNED,Illuminating new paths in heart failure therapy,2026-07-01,2030-06-30,"3998796,25","3998796,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"HeartVision is an ambitious high-risk, high-ga...",2026-01-14 10:03:59,282697,10.3030/101258941,In vivo microscopy of live heart with cell-sca...
17755,101221259,ECO-SLAG-CEM,SIGNED,ENVIRONMENTALLY COMPATIBLE OPTIMIZATION OF EAF...,2025-10-01,2029-09-30,0,"3991545,98",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-06-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"""The ECO-SLAG-CEM project aims to develop high...",2026-02-03 17:08:19,273187,10.3030/101221259,"SCM, Cement, EAF-Cement, EAF, Slag, low clinke..."
18203,101257934,AI-RITMIA,SIGNED,AI-assisted peRsonalized heart-on-chIp as adva...,2026-08-01,2029-07-31,2999935,2999935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Inherited cardiomyopathies (iCMPs) are a major...,2026-01-14 10:05:48,282698,10.3030/101257934,organ-on-chip; artificial intelligence; cardio...
18249,101234842,COMPASS,SIGNED,Comprehensive Offshore Management Platform for...,2025-11-01,2029-10-31,0,"4999786,87",HORIZON.2.5,HORIZON-CL5-2024-D3-02-08,2025-08-22,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,Europe is at the forefront of offshore wind en...,2026-01-07 15:11:33,276087,10.3030/101234842,"Sustainability, Offshore wind farm design, Cum..."
18327,101220926,X-SeeO2,SIGNED,Real-time X-ray diffraction and microstructure...,2025-10-01,2029-09-30,0,"4043885,24",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-05-30,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,X-SeeO2 delivers unique tools to the portfolio...,2025-08-18 13:48:30,272885,10.3030/101220926,"synchrotron radiation, Advanced X-ray powder ..."

In [61]:
projects_ = projects_filt[['id','acronym','title','startDate','endDate','totalCost','legalBasis','topics','masterCall','subCall','fundingScheme','objective','grantDoi']]

In [62]:
projects_['topics'].tolist()

['HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL6-2024-COMMUNITIES-01-3',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL5-2024-D3-02-08',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02']

In [63]:
# Define function to assign clusters
def assign_cluster(topic):
    if "CL2" in topic:
        return "Cluster 2"
    elif "CL3" in topic:
        return "Cluster 3"
    elif "CL4" in topic:
        return "Cluster 4"
    elif "CL5" in topic:
        return "Cluster 5"
    elif "CL6" in topic:
        return "Cluster 6"
    elif "HLTH" in topic:
        return "Cluster Health"
    elif "MISS" in topic:
        return "Cluster MISS"
    else:
        return "Other"

# Apply function to create a new column
projects_["cluster"] = projects_["topics"].apply(assign_cluster)

C:\Users\user\AppData\Local\Temp\ipykernel_20656\2163152521.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  projects_["cluster"] = projects_["topics"].apply(assign_cluster)

In [64]:
projects_

,id,acronym,title,startDate,endDate,totalCost,legalBasis,topics,masterCall,subCall,fundingScheme,objective,grantDoi,cluster
3,101257710,GREENDIGO,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",10.3030/101257710,Other
1453,101257928,NanoFlash,Cell-targeted Biophotonic Nanoparticles for Vi...,2026-05-01,2030-04-30,"2999978,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NanoFlash aims to develop disruptive nano-enab...,10.3030/101257928,Other
1455,101223249,2D-ADDICT,TWO-Dimensional materials for ADvanced DevIces...,2025-11-01,2028-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The grand challenge facing the electronics ind...,NaN,Other
1530,101221404,AstrAware,An On-board Dynamic Vision Sensor Suite for En...,2025-10-01,2028-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The current overpopulation of satellites in or...,10.3030/101221404,Other
1592,101257287,ULTRAPURE,INTEGRATED SOURCES FOR ULTRAPURE OSCILLATIONS ...,2026-02-01,2029-01-31,"3054936,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Many high-performance photonics applications w...,10.3030/101257287,Other
1678,101258353,PHINDER,Picosecond-scale Photonic Heterogeneous Integr...,2026-04-01,2030-03-31,"3129503,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Advanced applications—ranging from 5D-imaging ...,10.3030/101258353,Other
1702,101257985,SuperICQ,Superconducting Integrated Circuits for Scalab...,2026-03-01,2030-02-28,"2998012,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Superconducting circuits based on Josephson ju...,10.3030/101257985,Other
1713,101235287,THUNDER,INNOVATION IN E-MEOH PRODUCTION BY ONE-POT TAN...,2025-10-01,2029-09-30,3992190,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,"THUNDER aims to develop an innovative, modular...",10.3030/101235287,Cluster 5
1854,101259018,OutMARCH,OutMARCH-ing cancer: Towards innovative membra...,2026-05-01,2030-04-30,2999050,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,The OutMARCH project pioneers a paradigm-shift...,10.3030/101259018,Other
1868,101259117,REMMIA,REcycling perManent Magnets: an Innovative App...,2026-03-01,2030-02-28,"2991615,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Rare earth elements (REE) are crucial for mode...,10.3030/101259117,Other
1882,101259120,FeROS,Prodrugs oF antiparasitic RedOx-active compoundS,2026-03-01,2030-02-28,"3046491,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"With 600,000 deaths per year, malaria remains ...",10.3030/101259120,Other
1917,101223135,C-SINC,Concrete products through sustainable and inno...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The cement industry is a major contributor to ...,10.3030/101223135,Other
1936,101259183,NEQIOS,Neuromorphic Quantum-Inspired Optimization and...,2026-01-01,2030-12-31,"3358894,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NEQIOS introduces a radically new approach to ...,10.3030/101259183,Other
2002,101223119,STORM,Solar Weather Forecasting Mission,2025-11-01,2028-04-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"In STORM, satellite constellation operation in...",10.3030/101223119,Other
2015,101259077,CHEM-SCAN,HIGH-RESOLUTION FUNCTIONAL OPTICAL IMAGING OF ...,2026-03-01,2030-02-28,"2998207,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The development of chemoresistance, i.e. the a...",10.3030/101259077,Other
2155,101181686,ArcticKnows,Just knowledge co-creation for a regenerative ...,2025-10-01,2028-09-30,0,HORIZON.2.6,HORIZON-CL6-2024-COMMUNITIES-01-3,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-RIA,"ArcticKnows will empower Coastal, Local and In...",10.3030/101181686,Cluster 6
2188,101257530,ALERT,MULTIANALYTE DIGITAL SENSING WITH QR-CODE MICR...,2026-03-01,2029-02-28,"2917386,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"""ALERT introduces a groundbreaking leap in med...",10.3030/101257530,Other
2221,101236115,C2FUe-LS,Turning recycled carbon into valuable fuels fo...,2025-10-01,2029-09-30,"4028302,5",HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,+C2Fue-LS aims to develop a direct cold plasma...,10.3030/101236115,Cluster 5
2232,101258419,INTEGRAL,INTEGRATED PHOTONICS FOR SIGNAL PROCESSING AND...,2026-03-01,2029-02-28,2999500,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Optical Coherence Tomography (OCT) is a powerf...,10.3030/101258419,Other
2309,101259068,DRIVIN CAR,DRIVIN' CAR: Developing robust in vivo nanomed...,2026-03-01,2030-02-28,"3000347,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,DRIVIN’ CAR aims to transform immunotherapy by...,10.3030/101259068,Other
2317,101257413,HEARTCORE,HUMAN-BASED ADVANCED CARDIAC SAFETY PLATFORM I...,2026-06-01,2030-05-31,"2993436,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Cardiac safety testing still relies on animal ...,10.3030/101257413,Other
2322,101257628,AMFactory,Engineering bioreactor mass production of arbu...,2026-05-01,2029-04-30,2993767,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Microbial inoculants containing arbuscular myc...,10.3030/101257628,Other
2346,101258189,CarboNcare,CARBON-EFFICIENT BIOPRODUCTION OF CHEMICALS FR...,2026-05-01,2030-04-30,"3135362,35",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,A major challenge in carbon-based bioproductio...,10.3030/101258189,Other
2354,101258103,PROPANTHERA,Retrograde atrophy induction: a paradigm shift...,2026-03-01,2029-02-28,3140625,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Pancreatic cancer (PaC) is a leading cause of ...,10.3030/101258103,Other
2357,101257982,MECH-QUBIT,MECHanical QUBIT With Enhanced Coherence,2026-02-01,2030-01-31,3072590,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"Condensed-matter qubits, such as transmons and...",10.3030/101257982,Other
2496,101256857,ULYSSES,Ultrasensitive Luminescence-based Yeast Sensor...,2026-05-01,2029-04-30,"2991106,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,ULYSSES is a pioneering project aimed at devel...,10.3030/101256857,Other
2735,101216412,HARARA,Co-creating inclusive local climate adaptation...,2026-01-01,2028-12-31,"1999658,75",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,"European societies, especially in urban areas,...",10.3030/101216412,Cluster MISS
2988,101223271,CERBERUS,Unlocking the Full Potential of Edge AI throug...,2026-02-01,2030-01-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The introduction of the on-device AI paradigm ...,10.3030/101223271,Other
3018,101219355,SOLARSPOON,Solar-driven synthesis of proteins and lipids ...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,Biohybrid systems offer unique energy-efficien...,10.3030/101219355,Other
3108,101223091,C5,Clever Combination of Synthetic Compartmentali...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The C5 Pathfinder project aims to revolutioniz...,10.3030/101223091,Other
3229,101223335,CONCERTO,CarbOn Negative CemEnt fRom ulTra-mafic rOcks,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The majority of CO2 emissions associated with ...,10.3030/101223335,Other
3316,101216923,URBAN PROSUMERS,URBAN PROSUMERS – towards a knowledge transfer...,2025-10-01,2028-03-31,"1999847,5",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,The URBAN PROSUMERS project supports the imple...,10.3030/101216923,Cluster MISS
3343,101221957,MOJITO,Decarbonized liMe PrOduction through enhanced ...,2025-10-01,2028-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The MOJITO project aims to validate a laborato...,10.3030/101221957,Other
3620,101223193,SUN2CN,Fully-Integrated PV-EC Device for the Producti...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The SUN2CN project aims to deliver a standalon...,10.3030/101223193,Other
5076,101258941,HeartVision,Illuminating new paths in heart failure therapy,2026-07-01,2030-06-30,"3998796,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"HeartVision is an ambitious high-risk, high-ga...",10.3030/101258941,Other
17755,101221259,ECO-SLAG-CEM,ENVIRONMENTALLY COMPATIBLE OPTIMIZATION OF EAF...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"""The ECO-SLAG-CEM project aims to develop high...",10.3030/101221259,Other
18203,101257934,AI-RITMIA,AI-assisted peRsonalized heart-on-chIp as adva...,2026-08-01,2029-07-31,2999935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Inherited cardiomyopathies (iCMPs) are a major...,10.3030/101257934,Other
18249,101234842,COMPASS,Comprehensive Offshore Management Platform for...,2025-11-01,2029-10-31,0,HORIZON.2.5,HORIZON-CL5-2024-D3-02-08,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,Europe is at the forefront of offshore wind en...,10.3030/101234842,Cluster 5
18327,101220926,X-SeeO2,Real-time X-ray diffraction and microstructure...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,X-SeeO2 delivers unique tools to the portfolio...,10.3030/101220926,Other

In [65]:
projects_.to_csv('projects.csv',index=False,sep='|')

In [66]:
orgs_ = orgs_no_widening[orgs_no_widening['projectID'].isin(projects_['id'].tolist())]

In [67]:
orgs_

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
47,101257710,GREENDIGO,871776346,DK44981068,NordicBlue,NordicBlue ApS,True,PRC,Bakken 21,3050,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1994752,3,participant,1443808.75,1443808.75,"1443808,75",False,NaN
48,101257710,GREENDIGO,896476232,NL003125251B98,NEAGU ALEXANDRU-VALENTIN,BEE GRANTED,True,PRC,THORBECKEWEG 27,3732 BH,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1987817,4,participant,90220.00,90220.00,90220,False,NaN
49,101257710,GREENDIGO,991256096,FI22283574,AALTO KORKEAKOULUSAATIO SR,AALTO,False,HES,OTAKAARI 1,02150,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1906096,2,participant,841681.21,841681.21,"841681,21",False,NaN
50,101257710,GREENDIGO,999897341,IT00816350276,UNIVERSITA CA' FOSCARI VENEZIA,UNIVE,False,HES,DORSODURO 3246,30123,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-02-23 17:36:55,1909514,1,coordinator,623435.04,623435.04,"623435,04",False,NaN
16851,101257928,NanoFlash,999977172,GB823847609,THE CHANCELLOR MASTERS AND SCHOLARS OF THE UNI...,NaN,False,HES,TRINITY LANE THE OLD SCHOOLS,CB2 1TN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-12-22 15:23:57,1905558,1,coordinator,898075.00,898075.00,898075,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115369,101234842,COMPASS,999591209,FI02459042,LAPPEENRANNAN-LAHDEN TEKNILLINEN YLIOPISTO LUT,LUT University,False,HES,YLIOPISTONKATU 34,53850,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1918456,6,participant,280442.50,280442.50,0,False,NaN
115807,101220926,X-SeeO2,999842924,GB639542122,UNIVERSITY OF BATH,UBAH,False,HES,CLAVERTON DOWN,BA2 7AY,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:30,1908879,2,participant,895242.48,895242.48,0,False,NaN
115808,101220926,X-SeeO2,999903840,GB849738956,THE UNIVERSITY OF MANCHESTER,UNIVERSITY OF MANCHESTER,False,HES,OXFORD ROAD,M13 9PL,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:30,1905551,3,participant,760945.51,760945.51,0,False,NaN
115809,101220926,X-SeeO2,999484121,FR60338723919,EUROPEAN SYNCHROTRON RADIATION FACILITY,INSTALLATION EUROPEENNE DE RAYONNEMENT SYNCHROTON,False,REC,71 AVENUE DES MARTYRS,38000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:30,1910254,4,participant,985782.45,985782.45,0,False,NaN
115810,101220926,X-SeeO2,999898311,ESQ2918001E,UNIVERSIDAD DE MALAGA,UMA,False,HES,"AVDA CERVANTES, NUM. 2",29016,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-18 13:48:30,1909235,1,coordinator,1401914.80,1401914.80,0,False,NaN

In [68]:
orgs_ = orgs_[['projectID','name','shortName','SME','activityType','city','country','organizationURL','contactForm','order','role','ecContribution']]

In [69]:
print (orgs_['country'].unique())

['DK' 'NL' 'FI' 'IT' 'UK' 'BE' 'CH' 'AT' 'DE' 'FR' 'SE' 'ES' 'IE' 'US'
 'LU' 'NO' 'IS' 'GL']

In [70]:
orgs_.to_csv('orgs.csv',index=False,sep='|')