In [1]:
import pandas as pd

In [2]:
topics = pd.read_excel('data/topics.xlsx')
projects = pd.read_excel('data/project.xlsx')
euroscivoc = pd.read_excel('data/euroSciVoc.xlsx')
orgs = pd.read_excel('data/organization.xlsx')

E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
projects['startDate']= pd.to_datetime(projects['startDate'],errors = 'coerce')
projects['endDate']= pd.to_datetime(projects['endDate'],errors = 'coerce')
projects.info()

from datetime import datetime
filterdate = datetime(2024,1,1)
projects_fil = projects[projects['startDate']>=filterdate]
projects_fil = projects_fil[projects_fil['endDate']>=datetime(2027,9,25)]
projects_fil

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  19190 non-null  int64
 1   acronym             19190 non-null  object
 2   status              19190 non-null  object
 3   title               19190 non-null  object
 4   startDate           19190 non-null  datetime64[ns]
 5   endDate             19190 non-null  datetime64[ns]
 6   totalCost           19190 non-null  object
 7   ecMaxContribution   19190 non-null  object
 8   legalBasis          19190 non-null  object
 9   topics              19190 non-null  object
 10  ecSignatureDate     19188 non-null  object
 11  frameworkProgramme  19190 non-null  object
 12  masterCall          19190 non-null  object
 13  subCall             19190 non-null  object
 14  fundingScheme       19190 non-null  object
 15  objective           19190 non-null  object
 16  contentUpdateDate   19190 non-null  object
 17  rcn                 19190 non-null  int64
 18  grantDoi            19007 non-null  object
 19  keywords            17460 non-null  object
dtypes: datetime64[ns](2), int64(2), object(16)
memory usage: 2.9+ MB

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
0,101220893,EpiMoSis,SIGNED,Epigenome Maintenance on Sister Chromatids,2026-02-01,2031-01-31,1665563,1665563,HORIZON.1.1,ERC-2025-STG,2025-11-19,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,DNA replication not only involves the copying ...,2025-11-27 11:32:23,278677,10.3030/101220893,"DNA replication, Functional Genomics, histone ..."
1,101170559,ENCODED,SIGNED,Encoded Knowledge: Epistemology of Computer T...,2025-12-01,2030-11-30,1999968,1999968,HORIZON.1.1,ERC-2024-COG,2025-09-04,HORIZON,ERC-2024-COG,ERC-2024-COG,HORIZON-ERC,Modern economics has become an influential sci...,2025-11-25 16:38:32,276259,10.3030/101170559,values in science/values in economicshistory o...
3,101247800,OLIGOFEED_EU,SIGNED,OLIGOFEED,2025-10-01,2027-09-30,0,2499999,HORIZON.3.1,HORIZON-EIC-2025-ACCELERATOR-02-OPEN-01,2025-09-30,HORIZON,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-ACC,Pollinators are vital for global food producti...,2025-11-25 14:35:21,277798,10.3030/101247800,"BEEKEEPING, POLLINATORS, CHEMISTRY, FEED"
4,101233650,UNICHE,SIGNED,Unified No-Code platform for Interactive Cultu...,2025-10-01,2028-09-30,0,"3608915,55",HORIZON.2.2,HORIZON-CL2-2024-HERITAGE-ECCCH-01-04,2025-08-26,HORIZON,HORIZON-CL2-2024-HERITAGE-ECCCH-01,HORIZON-CL2-2024-HERITAGE-ECCCH-01,HORIZON-IA,"""The UNICHE project aspires to co-design and c...",2025-11-26 11:09:06,276114,10.3030/101233650,"cultural experiences, ECCCH compliant tools & ..."
5,101247959,NEXTBIOMOL,SIGNED,THE COMPUTATIONAL LABORATORY FOR THE NEXT GENE...,2025-11-03,2027-11-02,0,"2468494,24",HORIZON.3.1,HORIZON-EIC-2025-ACCELERATOR-02-CHALLENGES-01,2025-10-08,HORIZON,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-ACC,Bytelab Solutions S.L. (Bytelab) is a B2B deep...,2025-11-26 11:14:55,277785,10.3030/101247959,"advanced materials,digital R&D, high-performan..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19147,101187110,DELTA-HUB,SIGNED,"DELTA-HUB: RIVER DELTA SCIENCE, EDUCATION, AND...",2025-03-01,2030-02-28,0,2490375,HORIZON.4.1,HORIZON-WIDERA-2023-TALENTS-01-01,2024-09-23,HORIZON,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-CSA,DELTA-Hub aims to establish a competitive ERA ...,2024-10-03 16:51:45,266365,10.3030/101187110,"Danube River Delta, delta sustainability and r..."
19149,101176529,RACE,SIGNED,RACE: ERA Chair Initiative for Establishing a ...,2025-03-01,2030-02-28,0,2500000,HORIZON.4.1,HORIZON-WIDERA-2023-TALENTS-01-01,2024-10-31,HORIZON,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-CSA,"""The University of Crete (UoC), starting from ...",2024-11-08 16:30:05,267218,10.3030/101176529,"Ageing, Genome Instability, DNA repair"
19150,101187661,IMAGINE,SIGNED,Establishing a Chair for the Study of Imaginat...,2024-11-01,2029-10-31,0,"2497787,9",HORIZON.4.1,HORIZON-WIDERA-2023-TALENTS-01-01,2024-10-28,HORIZON,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-WIDERA-2023-TALENTS-01,HORIZON-CSA,The ERA Chair on Imagination and Society at th...,2024-11-08 16:30:32,267249,10.3030/101187661,"Imagination, Social sciences, Interdisciplin..."
19155,101177821,SkillResilience4EU,SIGNED,Resilience through re-skilling and upskilling ...,2025-01-01,2027-12-31,"2892507,5","2892507,5",HORIZON.2.2,HORIZON-CL2-2024-TRANSFORMATIONS-01-03,2024-10-01,HORIZON,HORIZON-CL2-2024-TRANSFORMATIONS-01,HORIZON-CL2-2024-TRANSFORMATIONS-01,HORIZON-RIA,The ongoing global challenges and the twin tra...,2024-10-09 16:43:00,266445,10.3030/101177821,"twin transition, job creation and destruction,..."
19158,101178623,Just Fashion,SIGNED,Supporting the Just transition for the Fashion...,2024-12-01,2027-11-30,0,"3754773,04",HORIZON.2.2,HORIZON-CL2-2024-HERITAGE-01-02,2024-09-29,HORIZON,HORIZON-CL2-2024-HERITAGE-01,HORIZON-CL2-2024-HERITAGE-01,HORIZON-IA,"“Just Fashion”, is set to develop a portfolio ...",2025-07-24 14:48:01,266345,10.3030/101178623,"Fashion, circularity, business models, sustain..."

In [4]:
projectIDs = projects_fil['id'].tolist()

In [5]:
orgs

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101220893,EpiMoSis,999990267,DE129517720,MAX-PLANCK-GESELLSCHAFT ZUR FORDERUNG DER WISS...,MPG,False,REC,HOFGARTENSTRASSE 8,80539,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-27 11:32:23,1949732,1,coordinator,1665563.0,1665563.0,1665563,False,NaN
1,101170559,ENCODED,999991043,DK29979812,KOBENHAVNS UNIVERSITET,UCPH,False,HES,NORREGADE 10,1165,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 16:38:32,1906270,1,coordinator,1999968.0,1999968.0,1999968,False,NaN
2,101247164,EyeView360,999840984,GB604609849,UNIVERSITY OF LANCASTER,Lancaster University,False,HES,BAILRIGG,LA1 4YW,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:09:41,1907918,1,coordinator,150000.0,150000.0,0,False,NaN
3,101247800,OLIGOFEED_EU,877992494,FR00952576759,Oligofeed,NaN,True,PRC,15 Rue des Remparts d'Ainay,69002,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 14:35:21,1994421,1,coordinator,2499999.0,2499999.0,0,False,NaN
4,101233650,UNICHE,996685089,IT01346820481,Museo Galileo - Istituto e Museo di Storia del...,IMSS,False,REC,PIAZZA DEI GIUDICI 1,50122,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:09:06,2927301,11,participant,132812.5,132812.5,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119431,101070800,MICIE,941799967,CY90000457V,OMOSPONDIA ERGODOTON & VIOMICHANON KYPROU,CYPRUS EMPLOYERS AND INDUSTRIALISTS FEDERATION...,True,OTH,4 CYPRUS EMPLOYERS & INDUSTRIALISTS FEDERATION...,2000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-08-16 22:53:11,1957244,4,participant,27500.0,27500.0,0,False,NaN
119432,101070800,MICIE,917561607,NL855175588B01,CLIMATE-KIC HOLDING BV,NaN,False,PRC,PLANTAGE MIDDENLAAN 45,1018 DC,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-08-16 22:53:11,1953833,8,participant,61875.0,61875.0,0,False,NaN
119433,101051386,BRIDGE,999822263,NaN,MINISTERE AUPRES DU MIN DE L EDUCATION NATIONA...,NaN,False,PUB,RUE DESCARTES 1,75005,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-09-13 17:50:47,1906385,1,coordinator,100000.0,100000.0,125000,False,NaN
119434,101051287,ICRI 2022,999880657,CZ00216224,Masarykova univerzita,MU,False,HES,Zerotinovo namesti 9,601 77,...,https://ec.europa.eu/info/funding-tenders/oppo...,2023-03-10 20:23:53,1910106,1,coordinator,300000.0,300000.0,300000,False,NaN
119435,101124993,GLORI,999421944,ESG82999871,FUNDACION ESPANOLA PARA LA CIENCIAY LA TECNOLO...,FECYT,False,REC,CALLE DEL PINTOR MURILLO NUMERO 15,28100,...,https://ec.europa.eu/info/funding-tenders/oppo...,2023-10-04 12:10:51,1914112,1,coordinator,100000.0,100000.0,"164961,25",False,NaN

In [6]:
orgsinproj = orgs[orgs['projectID'].isin(projectIDs)]
orgsinproj

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101220893,EpiMoSis,999990267,DE129517720,MAX-PLANCK-GESELLSCHAFT ZUR FORDERUNG DER WISS...,MPG,False,REC,HOFGARTENSTRASSE 8,80539,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-27 11:32:23,1949732,1,coordinator,1665563.00,1665563.00,1665563,False,NaN
1,101170559,ENCODED,999991043,DK29979812,KOBENHAVNS UNIVERSITET,UCPH,False,HES,NORREGADE 10,1165,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 16:38:32,1906270,1,coordinator,1999968.00,1999968.00,1999968,False,NaN
3,101247800,OLIGOFEED_EU,877992494,FR00952576759,Oligofeed,NaN,True,PRC,15 Rue des Remparts d'Ainay,69002,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 14:35:21,1994421,1,coordinator,2499999.00,2499999.00,0,False,NaN
4,101233650,UNICHE,996685089,IT01346820481,Museo Galileo - Istituto e Museo di Storia del...,IMSS,False,REC,PIAZZA DEI GIUDICI 1,50122,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:09:06,2927301,11,participant,132812.50,132812.50,0,False,NaN
5,101233650,UNICHE,899075056,LU30575136,UNISYSTEMS LUXEMBOURG SARL,NaN,False,PRC,"29, RUE DU PUITS ROMAIN",8070,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:09:06,1965637,1,coordinator,415100.00,380100.00,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119346,101178623,Just Fashion,928030235,ESG66210345,FUNDACIO EURECAT,EURECAT,False,REC,AVENIDA UNIVERSITAT AUTONOMA 23,08290,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-24 14:48:01,2284307,9,participant,327500.00,327500.00,0,False,NaN
119347,101178623,Just Fashion,999647857,LT119502413,VILNIAUS GEDIMINO TECHNIKOS UNIVERSITETAS,VILNIUS TECH,False,HES,SAULETEKIO AL 11,LT-10223,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-24 14:48:01,1923020,4,participant,274581.20,274581.20,0,False,NaN
119348,101178623,Just Fashion,878883148,DE365722521,EUROPEAN FASHION ALLIANCE E.V.,NaN,True,OTH,MEINEKESTR. 12,10719,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-24 14:48:01,1989623,19,participant,100047.15,100047.15,0,False,NaN
119349,101178623,Just Fashion,999967763,GB783637490,UNIVERSITY FOR THE CREATIVE ARTS,UNIVERSITY FOR THE CREATIVE ARTS,False,HES,FALKNER ROAD,GU9 7DS,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-24 14:48:01,2120992,2,participant,308670.53,308670.53,0,False,NaN
119350,101178623,Just Fashion,950582056,ESG65652232,AGRUPACIO CATALANA DEL TEXTIL I DE LA MODA,MODACC,False,OTH,AVENIDA DIAGONAL 474 ESC NB PLANTA 1,08006,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-24 14:48:01,1985465,8,participant,163020.00,163020.00,0,False,NaN

In [7]:
print (orgsinproj['country'].unique())

['DE' 'DK' 'FR' 'IT' 'LU' 'EL' 'PL' 'ES' 'HU' 'UK' 'CH' 'LT' 'BE' 'US'
 'AT' 'CZ' 'SE' 'TR' 'CY' 'IE' 'EE' 'NL' 'FI' 'SI' 'BG' 'RS' 'ZA' 'UG'
 'MU' 'KE' 'NO' 'BR' 'AU' 'CA' 'PT' 'IL' 'CN' 'RO' 'AW' 'TN' 'AM' 'SK'
 'CO' 'AR' 'CU' 'MT' 'HR' 'LV' 'UZ' 'KG' 'KZ' 'TM' 'TJ' 'JP' 'MK' 'EC'
 'PE' 'TZ' 'ET' 'BF' 'RW' 'MD' 'CD' 'EG' 'UY' 'IS' 'NG' 'PH' 'UA' 'GH'
 'KR' 'MV' 'CL' 'MX' 'AE' 'JO' 'GL' 'IN' 'NZ' 'BI' 'SA' 'MA' 'CR' 'MY'
 'BA' 'VN' 'PG' 'LK' 'NP' 'PK' 'AL' 'LA' 'IQ' 'CM' 'SN' 'GE' 'SG' 'MZ'
 'ZM' 'ID' 'TH' 'LB' 'BJ' 'BD' nan 'GA' 'CG' 'ZW' 'SZ' 'ME' 'HK' 'SV' 'KH'
 'PF' 'MN' 'MW' 'CI' 'XH' 'DZ' 'CV' 'LR' 'MH' 'MG' 'GT' 'BW' 'DJ' 'TD'
 'ML' 'FO' 'DE;HU' 'TG' 'MC' 'BQ' 'CF' 'IR' 'TW' 'SL' 'PY' 'BO' 'QA' 'GU'
 'MP' 'XK' 'SR' 'ST' 'JM' 'DO' 'AZ' 'FJ' 'KM' 'GW' 'AO' 'GN' 'BT' 'LI'
 'MO']

In [8]:
projectsIDS_with_widening = orgsinproj[orgsinproj['country'].isin(['EL','BG','HR','CZ','EE','HU','LV','LT','MT','PL','PT','RO','SK','SI',
                                                                   'AL','BA','AM','FO','GE','XK','MD','ME','MK','RS','TN','TR','UA','MA',
                                                                   'GP','GF','MQ','YT','CY'])]
projectsIDS_with_widening= projectsIDS_with_widening['projectID'].tolist()

In [9]:
projects_no_widening = projects_fil[~projects_fil['id'].isin(projectsIDS_with_widening)]
projects_no_widening

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
0,101220893,EpiMoSis,SIGNED,Epigenome Maintenance on Sister Chromatids,2026-02-01,2031-01-31,1665563,1665563,HORIZON.1.1,ERC-2025-STG,2025-11-19,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,DNA replication not only involves the copying ...,2025-11-27 11:32:23,278677,10.3030/101220893,"DNA replication, Functional Genomics, histone ..."
1,101170559,ENCODED,SIGNED,Encoded Knowledge: Epistemology of Computer T...,2025-12-01,2030-11-30,1999968,1999968,HORIZON.1.1,ERC-2024-COG,2025-09-04,HORIZON,ERC-2024-COG,ERC-2024-COG,HORIZON-ERC,Modern economics has become an influential sci...,2025-11-25 16:38:32,276259,10.3030/101170559,values in science/values in economicshistory o...
3,101247800,OLIGOFEED_EU,SIGNED,OLIGOFEED,2025-10-01,2027-09-30,0,2499999,HORIZON.3.1,HORIZON-EIC-2025-ACCELERATOR-02-OPEN-01,2025-09-30,HORIZON,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-ACC,Pollinators are vital for global food producti...,2025-11-25 14:35:21,277798,10.3030/101247800,"BEEKEEPING, POLLINATORS, CHEMISTRY, FEED"
5,101247959,NEXTBIOMOL,SIGNED,THE COMPUTATIONAL LABORATORY FOR THE NEXT GENE...,2025-11-03,2027-11-02,0,"2468494,24",HORIZON.3.1,HORIZON-EIC-2025-ACCELERATOR-02-CHALLENGES-01,2025-10-08,HORIZON,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-2025-ACCELERATOR-02,HORIZON-EIC-ACC,Bytelab Solutions S.L. (Bytelab) is a B2B deep...,2025-11-26 11:14:55,277785,10.3030/101247959,"advanced materials,digital R&D, high-performan..."
8,101219207,STEPS,SIGNED,STEPS: Biomechanical simulations of hominin lo...,2025-11-01,2030-10-31,1499522,1499522,HORIZON.1.1,ERC-2025-STG,2025-09-24,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,Human bipedalism is a rare and distinct form o...,2025-11-29 16:43:55,276497,10.3030/101219207,"human evolution, palaeoanthropology, evolution..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18993,101125504,U-Tube,SIGNED,Improving Kidney Health by Targeting Urinary ...,2024-06-01,2029-05-31,2000000,2000000,HORIZON.1.1,ERC-2023-COG,2024-01-24,HORIZON,ERC-2023-COG,ERC-2023-COG,HORIZON-ERC,Chronic kidney disease (CKD) affects one in te...,2024-01-30 18:10:27,259747,10.3030/101125504,"Chronic kidney disease, Extracellular vesicle..."
18995,101096659,MakingSense,SIGNED,Making sense of the senses: Causal Inference i...,2024-04-01,2029-03-31,2499527,2499527,HORIZON.1.1,ERC-2022-ADG,2023-11-15,HORIZON,ERC-2022-ADG,ERC-2022-ADG,HORIZON-ERC,To interact effectively with the complex dynam...,2023-11-21 13:25:10,258279,10.3030/101096659,"Multisensory , audiovisual integration, multi..."
19015,101230875,RESAVER_2025,SIGNED,Support to Retirement Savings Vehicle for Euro...,2025-01-01,2028-12-31,"4998988,75","4998988,75",HORIZON.4.2,HORIZON-WIDERA-2025-RESAVER-IBA,2025-05-07,HORIZON,HORIZON-WIDERA-2025-RESAVER-IBA,HORIZON-WIDERA-2025-RESAVER-IBA,HORIZON-CSA,The RESAVER Pension Fund aims to address the c...,2025-05-12 12:15:33,272159,10.3030/101230875,"social security, brain circulation, removing b..."
19024,101156751,SHIELD,SIGNED,Strategic Health Initiatives for Effective Dis...,2024-12-01,2028-11-30,0,"6552184,1",HORIZON.2.1,HORIZON-HLTH-2024-STAYHLTH-01-05-two-stage,2024-11-06,HORIZON,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-RIA,The prevalence of Non-Communicable Diseases is...,2024-11-15 16:33:20,267337,10.3030/101156751,"AI, risk-stratification, explainability, monit..."
19026,101145636,SOFAR,SIGNED,SOuthern aFrica research cApacity netwoRk,2024-10-01,2029-03-31,"4370387,88","4370387,5",HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-01-01,2024-09-13,HORIZON,HORIZON-JU-GH-EDCTP3-2023-01,HORIZON-JU-GH-EDCTP3-2023-01,HORIZON-JU-RIA,The SOuthern aFrica Research cApacity netwoRk ...,2025-07-28 10:51:20,265997,10.3030/101145636,"Research capacity building, fellowships, PhD, ..."

In [10]:
orgs_no_widening = orgs[orgs['projectID'].isin(projects_no_widening['id'].tolist())]
orgs_no_widening

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101220893,EpiMoSis,999990267,DE129517720,MAX-PLANCK-GESELLSCHAFT ZUR FORDERUNG DER WISS...,MPG,False,REC,HOFGARTENSTRASSE 8,80539,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-27 11:32:23,1949732,1,coordinator,1665563.00,1665563.00,1665563,False,NaN
1,101170559,ENCODED,999991043,DK29979812,KOBENHAVNS UNIVERSITET,UCPH,False,HES,NORREGADE 10,1165,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 16:38:32,1906270,1,coordinator,1999968.00,1999968.00,1999968,False,NaN
3,101247800,OLIGOFEED_EU,877992494,FR00952576759,Oligofeed,NaN,True,PRC,15 Rue des Remparts d'Ainay,69002,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-25 14:35:21,1994421,1,coordinator,2499999.00,2499999.00,0,False,NaN
17,101247959,NEXTBIOMOL,899551714,ESB67405589,BYTELAB SOLUTIONS SL,NaN,True,PRC,CALLE MALLORCA 1 PLANTA 1 PUERTA 3,08014,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:14:55,1975323,1,coordinator,2468494.24,2468494.24,0,False,NaN
20,101219207,STEPS,999977172,GB823847609,THE CHANCELLOR MASTERS AND SCHOLARS OF THE UNI...,NaN,False,HES,TRINITY LANE THE OLD SCHOOLS,CB2 1TN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-29 16:43:55,1905558,1,coordinator,1499522.00,1499522.00,1499522,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118953,101145636,SOFAR,920444738,NaN,ZAMBART,NaN,False,OTH,ZAMBART HOUSE RIDGEWAY CAMPUS OFF NATIONALIST ...,10110,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-28 10:51:20,1982513,4,participant,1208827.50,1208827.50,"1208827,5",False,NaN
118954,101145636,SOFAR,995625946,NaN,KLINIKUM DER LUDWIG-MAXIMILIANS-UNIVERSITAT MU...,LMU KLINIKUM,False,PUB,MARCHIONINISTRASSE 15,81377,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-28 10:51:20,1933291,1,thirdParty,0.00,596032.50,0,False,NaN
118955,101145636,SOFAR,994873905,NaN,Instituto Nacional de Saúde,INS,False,REC,"EN1, bairro da vila, parcela n 3943",1120,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-28 10:51:20,1907423,3,participant,1266777.50,1266777.50,"1266777,88",False,NaN
118956,101145636,SOFAR,999912667,GB233756066,LONDON SCHOOL OF HYGIENE AND TROPICAL MEDICINE...,LSHTM,False,HES,KEPPEL STREET,WC1E 7HT,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-28 10:51:20,1906028,5,associatedPartner,NaN,0.00,0,False,NaN
118957,101145636,SOFAR,972852286,NaN,BIOMEDICAL RESEARCH AND TRAINING INSTITUTE LBG,BRTI,False,REC,CNR SAMORA MACHEL AND PARK STREET,NaN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-28 10:51:20,1982511,2,participant,1298750.00,1298750.00,1298750,False,NaN

In [11]:
euroscivoc

,projectID,euroSciVocCode,euroSciVocPath,euroSciVocTitle,euroSciVocDescription
0,101170559,/31/111/609/1415,"/humanities/philosophy, ethics and religion/ph...",epistemology,NaN
1,101170559,/31/113/613,/humanities/history and archaeology/history,history,NaN
2,101247800,/29/101/553/1353,/social sciences/sociology/demography/mortality,mortality,NaN
3,101247800,/21/33/117,/medical and health sciences/health sciences/n...,nutrition,NaN
4,101247800,/27/81/30021,"/agricultural sciences/agriculture, forestry, ...",agriculture,NaN
...,...,...,...,...,...
40468,101205255,/25/69/433,/engineering and technology/nanotechnology/nan...,nanoelectronics,NaN
40469,101104602,/23/43/265,/natural sciences/physical sciences/thermodyna...,thermodynamics,NaN
40470,101104602,/23/51/359/1071,/natural sciences/mathematics/pure mathematics...,topology,NaN
40471,101104602,/23/49/329,/natural sciences/biological sciences/biophysics,biophysics,NaN
40472,101104602,/23/47/307/979/1607,/natural sciences/computer and information sci...,simulation software,NaN

In [12]:
euroscivoc_proj_no_widening = euroscivoc[euroscivoc['projectID'].isin(projects_no_widening['id'].tolist())]

In [13]:
euroscivoc_proj_no_widening['euroSciVocTitle'].unique()

array(['epistemology', 'history', 'mortality', 'nutrition', 'agriculture',
       'polymer sciences', 'coating and films', 'physical anthropology',
       'nuclear engineering', 'metallurgy', 'chemical sciences',
       'tribology', 'religions', 'law', 'philosophy', 'implants',
       'mathematics', 'anthropology', 'ideologies', 'DNA', 'melanoma',
       'mobile phones', 'ethnology', 'pollution', 'aircraft',
       'arithmetics', 'surgery', 'pathophysiology', 'bacteriology',
       'pandemics', 'proteins', 'vaccines', 'nano-materials', 'catalysis',
       'energy and fuels', 'neurobiology', 'transcriptomes',
       'grains and oilseeds', 'sociology', 'musicology',
       'wastewater treatment processes', 'sensors', 'RNA', 'homeostasis',
       'democracy', 'ontology', 'metaphysics', 'history of literature',
       'microbiology', 'linguistics', 'revolutions',
       'analytical chemistry', 'critical care medicine',
       'personalized medicine', 'governance', 'psychology',
       'spectroscopy', 'cardiac arrhythmia', 'geometry', 'combinatorics',
       'photochemistry', 'oncology', 'gender inequality', 'endocrinology',
       'inorganic compounds', 'nanotechnology', 'semiconductivity',
       'metalloids', 'electrolysis', 'amines', 'diabetes',
       'carbohydrates', 'physiology', 'climatic change mitigation',
       'geotechnics', 'geothermal energy', 'databases', 'lipids',
       'supercomputers', 'political sciences', 'geophysics', 'ultrasound',
       'proteomics', 'mutation', 'genomes', 'tissue engineering',
       'marine biology', 'civil society', 'stroke', 'immunology',
       'neurology', 'pharmacology and pharmacy', 'virology',
       'antibiotics', 'fibers', 'immunotherapy', 'neutrinos', 'leptons',
       'particle accelerator', 'physical cosmology', 'ecosystems',
       'post-colonial theories', 'ecology', 'smart sensors',
       'multiphysics', 'aliphatic compounds', 'pneumology', 'graphene',
       'composites', 'topology', 'solar energy', 'photocatalysis',
       'botany', 'epilepsy', 'social inequalities', 'criminology',
       'biodiversity conservation', 'elections', 'microscopy',
       'geographic information systems', 'pharmaceutical drugs',
       'biosensors', 'microelectronics', 'essays', 'software',
       'food technology', 'spacecraft', 'asteroids', 'pathology',
       'allergology', 'transplantation', 'enzymes', 'microfluidics',
       'ethnolichenology', 'entomology', 'amorphous semiconductors',
       'colors', 'social issues', 'primatology', 'epigenomes',
       'data science', 'astrophysics', 'supernova', 'parkinson',
       'evolutionary biology', 'evolutionary ecology', 'cereals',
       'internet of things', 'public policies', 'hydrogen energy',
       'alkaline earth metals', 'mathematical logic', 'census', 'algebra',
       'ancient history', 'satellite technology', 'astronomy',
       'climatology', 'animal husbandry', 'dairy', 'lubrication',
       'globalization', 'biomolecules', 'machine learning',
       'biocatalysis', 'forestry', 'anatomy and morphology', 'robotics',
       'developmental biology', 'plant breeding', 'internet',
       'mechatronics', 'alzheimer', 'fisheries', 'cavity optomechanics',
       'atomic physics', 'superconductivity', 'photons',
       'simulation software', 'super resolution microscopy',
       'spintronics', 'econometrics', 'macroeconomics', 'obstetrics',
       'prostate cancer', 'cytology', 'quantum physics', 'age inequality',
       'multidrug resistance', 'biosensing',
       'global navigation satellite system', 'dementia', 'HIV',
       'hepatology', 'post-transition metals', 'recycling', 'biophysics',
       'signal processing', 'natural resources management',
       'polylactic acid', 'meteorites', 'exoplanetology',
       'cosmochemistry', 'petrology', 'biological interactions',
       'cardiology', 'schizophrenia', 'epigenetics', 'molecular biology',
       'coronaviruses', 'software development', 'psychiatry',
       'habitat conservation', 'air pollution engineering', 'ceramics',
       'entrepreneurship', 'taxation', 'waste treatment processes',
       'fruit growing', 'fermentation', 'gene therapy', 'irrigation',
       'diagnostic technologies', 'obesity', 'genetics', 'rheumatology',
       'reproductive biology', 'inflammatory diseases', 'epidemiology',
       'soil sciences', 'volcanology', 'mineralogy', 'knot theory',
       'chemical process engineering', 'acoustics', 'didactics',
       'social psychology', 'social geography', 'dark matter',
       'behavioural psychology', 'cartography',
       'magnetic resonance imaging', 'virtual reality',
       'navigation systems', 'quarks', 'electrocatalysis', 'leukemia',
       'mammalogy', 'nucleotides', 'embryology', 'palaeontology',
       'radiochemistry', 'radiation chemistry', 'thermodynamics',
       'quasiparticles', 'fermions', 'partial differential equations',
       'amorphous solids', 'solid-state physics', 'quantum optics',
       'subtractive manufacturing', 'quantum computers', 'radar',
       'computer processors', 'cryptography', 'transport', 'archaeology',
       'islam', 'electrochemistry', 'modern history',
       'digital humanities', 'contemporary history', 'prehistory',
       'radiology', 'nonlinear optics', 'photovoltaic', 'alcohols',
       'family studies', 'humanities', 'ophthalmology', 'tuberculosis',
       'histology', 'literature studies', 'artificial intelligence',
       'otorhinolaryngology', 'robotic surgery', 'additive manufacturing',
       'arts', 'manufacturing engineering', 'architectural design',
       'applied mathematics', 'textiles', 'ornithology', 'cetology',
       'wind energy', 'bioeconomy', 'statistics and probability',
       'animal feed', 'asteroseismology', 'transition metals',
       'natural satellites', 'toxicology', 'organometallic chemistry',
       'hydrocarbons', 'distillation', 'educational sciences',
       'generative artificial intelligence', 'woodworking', 'bioreactors',
       'system software', 'eHealth', 'electric batteries',
       'computer security', 'numerical analysis',
       'thermodynamic engineering', 'aromatic compounds',
       'organic reactions', 'deep learning', 'computational intelligence',
       'analogue electronics', 'optics', 'plate tectonics',
       'computational science', 'innovation management',
       'pharmacokinetics', 'employment', 'cognitive neuroscience',
       'substance abuse', 'computational neuroscience',
       'cognitive psychology', 'immunisation', 'pandemic risks',
       'reinforcement learning', 'petroleum', 'productivity', 'biosphera',
       'knowledge organization', 'black holes', 'political communication',
       'public services', 'infectious diseases', 'mobile network',
       'fluid dynamics', 'cell signaling', 'optical astronomy',
       'galactic astronomy', 'stellar astronomy', 'astrochemistry',
       'christianity', 'plasma physics', 'solar astronomy', 'ethology',
       'condensed matter physics', 'electromagnetism and electronics',
       'molecular and chemical physics', 'theoretical physics',
       'climatic changes', 'political economy',
       'general language studies', 'mathematical physics', 'malaria',
       'aldehydes', 'molecular genetics', 'eukaryotic genomes',
       'particle physics', 'dramaturgy', 'antibiotic resistance',
       'paleoecology', 'science and technology studies', 'unemployment',
       'geochemistry', 'bureaucracy', 'big data', 'gender equality',
       'sexual violence', 'glaciology', 'corruption', 'optoelectronics',
       'medicinal chemistry', 'social work', 'paediatrics', 'fertility',
       'medieval history', 'art history', 'nanophotonics',
       'cinematography', 'urban studies', 'ecohydrology', 'stem cells',
       'organ on a chip', 'crystallography', 'vascular diseases',
       'synthetic fuels', 'family planning', 'racial inequality',
       'physiotherapy', 'penology', 'pedagogy', 'molecular evolution',
       'developmental psychology', 'control systems', 'dynamical systems',
       'separation technologies', 'two-dimensional nanostructures',
       'applied mechanics', 'biomaterials', 'lab on a chip',
       'breast cancer', 'game theory', 'piezoelectrics',
       'development economics', 'calorimetry', 'biofuels', 'noble gases',
       'biochemistry', 'graphic design', 'asthma', 'hepatitis B',
       'cells technologies', 'structural health monitoring',
       'computer vision', 'nanocrystals', 'halogens',
       'mathematical analysis', 'nongovernmental organizations',
       'teleology', 'microtechnology', 'data processing',
       'climate change adaptation', 'sustainable economy',
       'hydroelectricity', 'electric energy', 'renewable energy',
       'combined heat and power', 'hydrology', 'sustainable building',
       'biomass energy', 'energy conversion', 'microseisms',
       'environmental engineering', 'transportation engineering',
       'electric power transmission', 'fuel cells',
       'aeronautical engineering', 'drones', 'e-commerce', 'terrorism',
       'natural language processing', 'armed conflicts',
       'human rights violations', 'mathematical model',
       'medieval philosophy', 'influenza', 'RNA viruses',
       'nanocomposites', 'knowledge engineering', 'antivirals',
       'pancreatic cancer', 'invertebrate zoology', 'viticulture',
       'geology', 'biogeochemistry', 'oceanography', 'public health',
       'graph theory', 'medical engineering', 'sexual health',
       'structural biology', 'physical chemistry', 'rotorcraft',
       'journalism', 'reproductive medicine', 'speleology',
       'bioarchaeology', 'super-Earths', 'electrical engineering',
       'atmospheric sciences', 'colorectal cancer', 'microeconomics',
       'heuristic programming', 'genetic selection', 'visual arts',
       'planetary geology', 'physical geography', 'mental processes',
       'postnatal care', 'childbirth', 'laser physics', 'seismology',
       'flood risk management', 'geochronology', 'vegetable growing',
       'sustainable agriculture', 'nanoelectronics', 'chromosomes',
       'heredity', 'statistical mechanics', 'comparative morphology',
       'laboratory samples analysis', 'metabolomes', 'arteriosclerosis',
       'remanufacturing', 'glaucoma', 'hepatitis C', 'phycology',
       'protein folding', 'ultrafast lasers', 'polyhydroxyalkanoates',
       'nanomedicine', 'mycology', 'business models',
       'modern and contemporary art', 'algebraic geometry', 'skin cancer',
       'dermatology', 'animal and dairy science', 'crystals',
       'soft matter physics', 'quantum chemistry', 'social developments',
       'heat engineering', 'organic chemistry', 'geomorphology',
       'human migrations', 'e-governance', 'political violence',
       'international protection of human rights', 'psychoanalysis',
       'economics', 'social anthropology',
       'cultural and economic geography', 'anaesthesiology',
       'horticulture', 'sustainability sciences', 'gluons', 'biomass',
       'radio frequency', 'fourier analysis', 'bioremediation',
       'soil management', 'bioplastics', 'thermochemistry', 'ebola',
       'polyurethane', 'apidology', 'drug discovery',
       'electron microscopy', 'physical sciences', 'human trafficking',
       'genetic engineering', 'cell biology',
       'biological behavioural sciences', 'optical sensors',
       'fibre optics', 'bulk nanostructured materials', 'odontology',
       'orthopaedics', 'fodder', 'prime numbers', 'synthetic dyes',
       'inflammatory bowel disease', 'organic amorphous solids',
       'desalination', 'ocean engineering', 'radio technology',
       'control engineering', 'planets', 'sedimentology',
       'ozone depletion', 'comets', 'climatic zones', 'paleoclimatology',
       'ecological restoration', 'commerce', 'arboriculture',
       'automation', 'gerontology', 'zoology', 'zoonosis',
       'graft versus host disease', 'discrete mathematics', 'exposomes',
       'drug resistance', 'ethnoarchaeology', 'agronomy',
       'gender studies', 'government systems', 'public administration',
       'mass spectrometry', 'eastern religions', 'plant protection',
       'data protection', 'meteorology', 'active learning',
       'data exchange', 'neutron stars', 'space exploration',
       'production economics', 'remote sensing', 'alkali metals',
       'isotope geochemistry', 'coastal ecosystems', 'demography',
       'health economics', 'nursing', 'nuclear medicine',
       'diagnostic imaging', 'cardiovascular diseases',
       'logarithmic functions', 'coal',
       'computer and information sciences', 'carbon capture engineering',
       'compost', 'ethnomusicology', 'galaxy evolution',
       'gravitational waves', 'radio astronomy', 'anxiety disorders',
       'literary genres', 'ergonomics', 'celestial mechanics',
       'observational astronomy', 'performing arts',
       'business and management', 'supervised learning',
       'extragalactic astronomy', 'aerospace engineering', 'parasitology',
       'inertial navigation system', 'product engineering',
       'power engineering', 'multiple sclerosis', 'environmental law',
       'apiculture', 'languages and literature', 'folklore',
       'women’s studies', 'foreign policy', 'agroecology',
       'library sciences', 'functional morphology', 'behavioural ecology',
       'hematology', 'crisis management', 'natural disasters',
       'drainage basins', 'digital electronics', 'prokaryotic genomes',
       'bayesian statistics', 'judaism', 'software applications',
       'international law', 'human rights',
       'computational fluid dynamics', 'hydrometeorology', 'phonology',
       'phonetics', 'waste management', 'health care services',
       'psycholinguistics', 'ethical principles', 'physical oceanography',
       'cervical cancer', 'DNA viruses', 'fossil energy', 'big bang',
       'infrared astronomy', 'history and archaeology',
       'dendrochronology', 'cultural anthropology', 'electromagnetism',
       'planetary sciences', 'inclusive education',
       'posttraumatic stress disorder', 'solar physics', 'ethics',
       'nuclear fusion', 'public transport',
       'modeling of diseases spread', 'synthetic biology',
       'literary theory', 'political transitions', 'law enforcement',
       'constitutional law', 'psychotherapy', 'history of medicine',
       'optical networks', 'mining and mineral processing',
       'contemporary philosophy', 'data networks', 'archaeometry',
       'lung cancer', 'computed tomography', 'sign language', 'riots',
       'world wide web', 'food packaging', 'speech-language pathology',
       'ecosystem-based management', 'literary criticism',
       'kidney diseases', 'soft robotics', 'quantum field theory',
       'agricultural biotechnology', 'biocomposites',
       'bioartificial liver', 'ethical theories', 'video games',
       'veterinary sciences', 'z bosons', 'higgs bosons',
       'motion analysis', 'microbiomes', 'architecture engineering',
       'palynology', 'data mining', 'underwater archaeology',
       'operator algebra', 'political philosophy',
       'medical biotechnology', 'sleep disorders',
       'bose-einstein condensates', 'molecular spintronics',
       'materials engineering'], dtype=object)

In [14]:
scivocpathlist = euroscivoc_proj_no_widening['euroSciVocPath'].tolist()

In [15]:
paths = ",".join(scivocpathlist)
print (paths)

/humanities/philosophy, ethics and religion/philosophy/epistemology,/humanities/history and archaeology/history,/social sciences/sociology/demography/mortality,/medical and health sciences/health sciences/nutrition,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/natural sciences/chemical sciences/polymer sciences,/engineering and technology/materials engineering/coating and films,/medical and health sciences/health sciences/nutrition,/social sciences/sociology/anthropology/physical anthropology,/engineering and technology/other engineering and technologies/nuclear engineering,/engineering and technology/materials engineering/metallurgy,/natural sciences/chemical sciences,/engineering and technology/mechanical engineering/tribology,/humanities/history and archaeology/history,/humanities/philosophy, ethics and religion/religions,/social sciences/law,/humanities/philosophy, ethics and religion/philosophy,/medical and health sciences/medical biotechnology/implants,/natural sciences/mathematics,/social sciences/sociology/anthropology,/social sciences/sociology/ideologies,/natural sciences/biological sciences/genetics/DNA,/medical and health sciences/clinical medicine/oncology/skin cancer/melanoma,/engineering and technology/electrical engineering, electronic engineering, information engineering/information engineering/telecommunications/mobile phones,/social sciences/sociology/anthropology/ethnology,/natural sciences/earth and related environmental sciences/environmental sciences/pollution,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/aircraft,/humanities/history and archaeology/history,/natural sciences/mathematics/pure mathematics/arithmetics,/humanities/philosophy, ethics and religion/philosophy,/medical and health sciences/clinical medicine/surgery,/medical and health sciences/basic medicine/physiology/pathophysiology,/natural sciences/biological sciences/microbiology/bacteriology,/medical and health sciences/health sciences/public health/epidemiology/pandemics,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/vaccines,/engineering and technology/nanotechnology/nano-materials,/natural sciences/chemical sciences/catalysis,/engineering and technology/environmental engineering/energy and fuels,/natural sciences/biological sciences/neurobiology,/natural sciences/biological sciences/genetics/RNA/transcriptomes,/medical and health sciences/health sciences/public health/epidemiology/pandemics,/social sciences/sociology/anthropology,/medical and health sciences/health sciences/nutrition,/natural sciences/earth and related environmental sciences/environmental sciences/pollution,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/agricultural sciences/agriculture, forestry, and fisheries/agriculture/grains and oilseeds,/social sciences/sociology,/humanities/arts/musicology,/engineering and technology/environmental engineering/water treatment processes/wastewater treatment processes,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/social sciences/law,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/biological sciences/genetics/RNA,/medical and health sciences/basic medicine/physiology/homeostasis,/social sciences/political sciences/government systems/democracy,/natural sciences/chemical sciences/catalysis,/humanities/philosophy, ethics and religion/philosophy,/natural sciences/computer and information sciences/knowledge engineering/ontology,/humanities/philosophy, ethics and religion/philosophy/metaphysics,/humanities/languages and literature/literature studies/history of literature,/natural sciences/biological sciences/microbiology,/humanities/languages and literature/linguistics,/social sciences/political sciences/political transitions/revolutions,/humanities/philosophy, ethics and religion/philosophy,/natural sciences/chemical sciences/analytical chemistry,/medical and health sciences/clinical medicine/critical care medicine,/medical and health sciences/health sciences/nutrition,/medical and health sciences/health sciences/personalized medicine,/natural sciences/biological sciences/neurobiology,/medical and health sciences/basic medicine/physiology/pathophysiology,/social sciences/sociology/governance,/social sciences/psychology,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/physical sciences/optics/spectroscopy,/natural sciences/biological sciences/neurobiology,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases/cardiac arrhythmia,/social sciences/sociology/demography/mortality,/natural sciences/mathematics/pure mathematics/geometry,/natural sciences/mathematics/pure mathematics/discrete mathematics/combinatorics,/medical and health sciences/clinical medicine/oncology/skin cancer/melanoma,/natural sciences/chemical sciences/physical chemistry/photochemistry,/medical and health sciences/clinical medicine/oncology,/natural sciences/biological sciences/neurobiology,/social sciences/sociology/social issues/social inequalities/gender inequality,/humanities/history and archaeology/history,/social sciences/psychology,/medical and health sciences/clinical medicine/endocrinology,/natural sciences/chemical sciences/inorganic chemistry/inorganic compounds,/engineering and technology/nanotechnology,/natural sciences/physical sciences/electromagnetism and electronics/semiconductivity,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/natural sciences/chemical sciences/electrochemistry/electrolysis,/natural sciences/chemical sciences/catalysis,/natural sciences/chemical sciences/organic chemistry/amines,/medical and health sciences/clinical medicine/endocrinology/diabetes,/natural sciences/biological sciences/biochemistry/biomolecules/carbohydrates,/medical and health sciences/basic medicine/physiology,/engineering and technology/environmental engineering/ecosystem-based management/climatic change mitigation,/engineering and technology/environmental engineering/geotechnics,/engineering and technology/environmental engineering/energy and fuels/renewable energy/geothermal energy,/natural sciences/computer and information sciences/databases,/natural sciences/biological sciences/biochemistry/biomolecules/lipids,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/supercomputers,/social sciences/political sciences,/humanities/history and archaeology/history,/natural sciences/earth and related environmental sciences/geophysics,/natural sciences/physical sciences/acoustics/ultrasound,/natural sciences/biological sciences/neurobiology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/proteomics,/natural sciences/biological sciences/genetics/mutation,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/biological sciences/genetics/RNA,/natural sciences/biological sciences/genetics/genomes,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/supercomputers,/medical and health sciences/clinical medicine/surgery,/medical and health sciences/medical biotechnology/tissue engineering,/humanities/philosophy, ethics and religion/philosophy/epistemology,/social sciences/law,/natural sciences/biological sciences/marine biology,/humanities/history and archaeology/history,/social sciences/political sciences/political policies/civil society,/medical and health sciences/basic medicine/neurology/stroke,/medical and health sciences/basic medicine/immunology,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/basic medicine/neurology,/medical and health sciences/basic medicine/pharmacology and pharmacy,/natural sciences/mathematics/pure mathematics/geometry,/natural sciences/biological sciences/microbiology/virology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/antibiotics,/medical and health sciences/clinical medicine/oncology,/engineering and technology/materials engineering/fibers,/social sciences/sociology/demography/mortality,/medical and health sciences/clinical medicine/surgery,/engineering and technology/nanotechnology/nano-materials,/medical and health sciences/basic medicine/immunology/immunotherapy,/natural sciences/physical sciences/theoretical physics/particle physics/neutrinos,/natural sciences/physical sciences/theoretical physics/particle physics/leptons,/natural sciences/physical sciences/theoretical physics/particle physics/particle accelerator,/natural sciences/physical sciences/astronomy/physical cosmology,/natural sciences/biological sciences/ecology/ecosystems,/social sciences/other social sciences/development studies/development theories/post-colonial theories,/humanities/history and archaeology/history,/natural sciences/biological sciences/ecology,/engineering and technology/materials engineering/fibers,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/smart sensors,/natural sciences/computer and information sciences/computational science/multiphysics,/natural sciences/chemical sciences/electrochemistry/electrolysis,/natural sciences/biological sciences/biochemistry/biomolecules/lipids,/natural sciences/chemical sciences/catalysis,/natural sciences/chemical sciences/organic chemistry/aliphatic compounds,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/medical and health sciences/clinical medicine/pneumology,/natural sciences/biological sciences/microbiology/bacteriology,/medical and health sciences/basic medicine/physiology/pathophysiology,/natural sciences/biological sciences/genetics/RNA,/engineering and technology/materials engineering/fibers,/natural sciences/biological sciences/genetics/DNA,/engineering and technology/nanotechnology/nano-materials/two-dimensional nanostructures/graphene,/engineering and technology/materials engineering/composites,/natural sciences/mathematics/pure mathematics/topology,/natural sciences/chemical sciences/polymer sciences,/natural sciences/mathematics/pure mathematics/geometry,/engineering and technology/environmental engineering/energy and fuels/renewable energy/solar energy,/natural sciences/chemical sciences/catalysis/photocatalysis,/natural sciences/biological sciences/botany,/social sciences/sociology/demography/mortality,/natural sciences/biological sciences/genetics/mutation,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/basic medicine/neurology/epilepsy,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/biological sciences/genetics/mutation,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/social sciences/sociology/social issues/social inequalities,/social sciences/psychology,/social sciences/law/criminology,/natural sciences/chemical sciences/catalysis,/natural sciences/biological sciences/biodiversity conservation,/humanities/history and archaeology/history,/humanities/arts/musicology,/engineering and technology/environmental engineering/ecosystem-based management/climatic change mitigation,/social sciences/sociology/governance,/social sciences/political sciences/political transitions/elections,/natural sciences/biological sciences/microbiology/bacteriology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/antibiotics,/natural sciences/physical sciences/optics/microscopy,/medical and health sciences/health sciences/nutrition,/natural sciences/physical sciences/optics/spectroscopy,/natural sciences/computer and information sciences/databases,/natural sciences/earth and related environmental sciences/physical geography/cartography/geographic information systems,/natural sciences/biological sciences/ecology/ecosystems,/humanities/languages and literature/literature studies/history of literature,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs,/natural sciences/chemical sciences/catalysis,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/biosensors,/natural sciences/physical sciences/electromagnetism and electronics/microelectronics,/medical and health sciences/medical biotechnology/implants,/humanities/history and archaeology/history,/humanities/languages and literature/literature studies/literary genres/essays,/social sciences/psychology,/humanities/arts/musicology,/humanities/philosophy, ethics and religion/philosophy,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/natural sciences/computer and information sciences/software,/natural sciences/computer and information sciences/databases,/engineering and technology/other engineering and technologies/food technology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/health sciences/nutrition,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/astronautical engineering/spacecraft,/natural sciences/physical sciences/astronomy/planetary sciences/asteroids,/humanities/history and archaeology/history,/medical and health sciences/health sciences/nutrition,/medical and health sciences/basic medicine/pathology,/medical and health sciences/clinical medicine/allergology,/medical and health sciences/basic medicine/immunology/immunotherapy,/medical and health sciences/clinical medicine/transplantation,/natural sciences/biological sciences/biochemistry/biomolecules/lipids,/natural sciences/biological sciences/genetics/RNA/transcriptomes,/natural sciences/biological sciences/genetics/genomes,/social sciences/psychology,/natural sciences/chemical sciences/catalysis,/engineering and technology/nanotechnology/nano-materials,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/mathematics/pure mathematics/geometry,/natural sciences/physical sciences/classical mechanics/fluid mechanics/microfluidics,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/basic medicine/physiology,/medical and health sciences/health sciences/nutrition,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/natural sciences/biological sciences/microbiology/mycology/ethnolichenology,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/physical sciences/optics/microscopy,/natural sciences/biological sciences/ecology/ecosystems,/natural sciences/biological sciences/zoology/entomology,/engineering and technology/materials engineering/amorphous solids/amorphous semiconductors,/medical and health sciences/clinical medicine/oncology,/natural sciences/computer and information sciences/databases,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors,/engineering and technology/materials engineering/colors,/social sciences/political sciences/government systems/democracy,/social sciences/sociology/social issues,/natural sciences/biological sciences/zoology/mammalogy/primatology,/natural sciences/biological sciences/genetics/DNA,/natural sciences/biological sciences/genetics/mutation,/medical and health sciences/clinical medicine/oncology,/natural sciences/biological sciences/genetics/epigenetics/epigenomes,/engineering and technology/environmental engineering/energy and fuels,/natural sciences/computer and information sciences/data science,/natural sciences/physical sciences/astronomy/physical cosmology,/natural sciences/biological sciences/marine biology,/natural sciences/physical sciences/theoretical physics/particle physics/neutrinos,/natural sciences/physical sciences/astronomy/astrophysics,/natural sciences/physical sciences/astronomy/stellar astronomy/supernova,/natural sciences/biological sciences/neurobiology,/humanities/philosophy, ethics and religion/philosophy/epistemology,/medical and health sciences/clinical medicine/oncology/skin cancer/melanoma,/medical and health sciences/basic medicine/immunology/immunotherapy,/medical and health sciences/basic medicine/neurology/parkinson,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/humanities/history and archaeology/history,/natural sciences/biological sciences/evolutionary biology,/natural sciences/biological sciences/ecology/evolutionary ecology,/agricultural sciences/agriculture, forestry, and fisheries/agriculture/grains and oilseeds/cereals,/natural sciences/computer and information sciences/internet/internet of things,/natural sciences/computer and information sciences/databases,/social sciences/political sciences/political policies/public policies,/natural sciences/chemical sciences/catalysis/photocatalysis,/natural sciences/chemical sciences/electrochemistry/electrolysis,/engineering and technology/nanotechnology/nano-materials,/natural sciences/physical sciences/optics/spectroscopy,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/astronautical engineering/spacecraft,/engineering and technology/environmental engineering/energy and fuels/renewable energy/hydrogen energy,/natural sciences/biological sciences/botany,/natural sciences/chemical sciences/polymer sciences,/humanities/history and archaeology/history,/natural sciences/chemical sciences/inorganic chemistry/alkaline earth metals,/natural sciences/mathematics/pure mathematics/discrete mathematics/mathematical logic,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases/cardiac arrhythmia,/social sciences/sociology/demography/mortality,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/natural sciences/biological sciences/genetics/mutation,/social sciences/sociology/demography/census,/natural sciences/physical sciences/astronomy/physical cosmology,/natural sciences/mathematics/pure mathematics/algebra,/humanities/languages and literature/linguistics,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs/antibiotics,/humanities/history and archaeology/history/ancient history,/natural sciences/earth and related environmental sciences/environmental sciences/pollution,/humanities/languages and literature/literature studies/history of literature,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/satellite technology,/natural sciences/physical sciences/astronomy,/social sciences/sociology/demography/mortality,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/natural sciences/earth and related environmental sciences/atmospheric sciences/climatology,/natural sciences/biological sciences/evolutionary biology,/agricultural sciences/animal and dairy science/domestic animals/animal husbandry,/agricultural sciences/animal and dairy science/dairy,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/health science

In [16]:
paths = paths.replace('/',',')
paths = paths.replace(',,',',')

In [17]:
paths

',humanities,philosophy, ethics and religion,philosophy,epistemology,humanities,history and archaeology,history,social sciences,sociology,demography,mortality,medical and health sciences,health sciences,nutrition,agricultural sciences,agriculture, forestry, and fisheries,agriculture,natural sciences,chemical sciences,polymer sciences,engineering and technology,materials engineering,coating and films,medical and health sciences,health sciences,nutrition,social sciences,sociology,anthropology,physical anthropology,engineering and technology,other engineering and technologies,nuclear engineering,engineering and technology,materials engineering,metallurgy,natural sciences,chemical sciences,engineering and technology,mechanical engineering,tribology,humanities,history and archaeology,history,humanities,philosophy, ethics and religion,religions,social sciences,law,humanities,philosophy, ethics and religion,philosophy,medical and health sciences,medical biotechnology,implants,natural sciences,mathematics,social sciences,sociology,anthropology,social sciences,sociology,ideologies,natural sciences,biological sciences,genetics,DNA,medical and health sciences,clinical medicine,oncology,skin cancer,melanoma,engineering and technology,electrical engineering, electronic engineering, information engineering,information engineering,telecommunications,mobile phones,social sciences,sociology,anthropology,ethnology,natural sciences,earth and related environmental sciences,environmental sciences,pollution,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,aircraft,humanities,history and archaeology,history,natural sciences,mathematics,pure mathematics,arithmetics,humanities,philosophy, ethics and religion,philosophy,medical and health sciences,clinical medicine,surgery,medical and health sciences,basic medicine,physiology,pathophysiology,natural sciences,biological sciences,microbiology,bacteriology,medical and health sciences,health sciences,public health,epidemiology,pandemics,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,vaccines,engineering and technology,nanotechnology,nano-materials,natural sciences,chemical sciences,catalysis,engineering and technology,environmental engineering,energy and fuels,natural sciences,biological sciences,neurobiology,natural sciences,biological sciences,genetics,RNA,transcriptomes,medical and health sciences,health sciences,public health,epidemiology,pandemics,social sciences,sociology,anthropology,medical and health sciences,health sciences,nutrition,natural sciences,earth and related environmental sciences,environmental sciences,pollution,agricultural sciences,agriculture, forestry, and fisheries,agriculture,agricultural sciences,agriculture, forestry, and fisheries,agriculture,grains and oilseeds,social sciences,sociology,humanities,arts,musicology,engineering and technology,environmental engineering,water treatment processes,wastewater treatment processes,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,social sciences,law,natural sciences,biological sciences,biochemistry,biomolecules,proteins,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,biological sciences,genetics,RNA,medical and health sciences,basic medicine,physiology,homeostasis,social sciences,political sciences,government systems,democracy,natural sciences,chemical sciences,catalysis,humanities,philosophy, ethics and religion,philosophy,natural sciences,computer and information sciences,knowledge engineering,ontology,humanities,philosophy, ethics and religion,philosophy,metaphysics,humanities,languages and literature,literature studies,history of literature,natural sciences,biological sciences,microbiology,humanities,languages and literature,linguistics,social sciences,political sciences,political transitions,revolutions,humanities,philosophy, ethics and religion,philosophy,natural sciences,chemical sciences,analytical chemistry,medical and health sciences,clinical medicine,critical care medicine,medical and health sciences,health sciences,nutrition,medical and health sciences,health sciences,personalized medicine,natural sciences,biological sciences,neurobiology,medical and health sciences,basic medicine,physiology,pathophysiology,social sciences,sociology,governance,social sciences,psychology,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,physical sciences,optics,spectroscopy,natural sciences,biological sciences,neurobiology,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,cardiac arrhythmia,social sciences,sociology,demography,mortality,natural sciences,mathematics,pure mathematics,geometry,natural sciences,mathematics,pure mathematics,discrete mathematics,combinatorics,medical and health sciences,clinical medicine,oncology,skin cancer,melanoma,natural sciences,chemical sciences,physical chemistry,photochemistry,medical and health sciences,clinical medicine,oncology,natural sciences,biological sciences,neurobiology,social sciences,sociology,social issues,social inequalities,gender inequality,humanities,history and archaeology,history,social sciences,psychology,medical and health sciences,clinical medicine,endocrinology,natural sciences,chemical sciences,inorganic chemistry,inorganic compounds,engineering and technology,nanotechnology,natural sciences,physical sciences,electromagnetism and electronics,semiconductivity,natural sciences,chemical sciences,inorganic chemistry,metalloids,natural sciences,chemical sciences,electrochemistry,electrolysis,natural sciences,chemical sciences,catalysis,natural sciences,chemical sciences,organic chemistry,amines,medical and health sciences,clinical medicine,endocrinology,diabetes,natural sciences,biological sciences,biochemistry,biomolecules,carbohydrates,medical and health sciences,basic medicine,physiology,engineering and technology,environmental engineering,ecosystem-based management,climatic change mitigation,engineering and technology,environmental engineering,geotechnics,engineering and technology,environmental engineering,energy and fuels,renewable energy,geothermal energy,natural sciences,computer and information sciences,databases,natural sciences,biological sciences,biochemistry,biomolecules,lipids,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,supercomputers,social sciences,political sciences,humanities,history and archaeology,history,natural sciences,earth and related environmental sciences,geophysics,natural sciences,physical sciences,acoustics,ultrasound,natural sciences,biological sciences,neurobiology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,proteomics,natural sciences,biological sciences,genetics,mutation,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,biological sciences,genetics,RNA,natural sciences,biological sciences,genetics,genomes,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,supercomputers,medical and health sciences,clinical medicine,surgery,medical and health sciences,medical biotechnology,tissue engineering,humanities,philosophy, ethics and religion,philosophy,epistemology,social sciences,law,natural sciences,biological sciences,marine biology,humanities,history and archaeology,history,social sciences,political sciences,political policies,civil society,medical and health sciences,basic medicine,neurology,stroke,medical and health sciences,basic medicine,immunology,medical and health sciences,clinical medicine,oncology,medical and health sciences,basic medicine,neurology,medical and health sciences,basic medicine,pharmacology and pharmacy,natural sciences,mathematics,pure mathematics,geometry,natural sciences,biological sciences,microbiology,virology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,antibiotics,medical and health sciences,clinical medicine,oncology,engineering and technology,materials engineering,fibers,social sciences,sociology,demography,mortality,medical and health sciences,clinical medicine,surgery,engineering and technology,nanotechnology,nano-materials,medical and health sciences,basic medicine,immunology,immunotherapy,natural sciences,physical sciences,theoretical physics,particle physics,neutrinos,natural sciences,physical sciences,theoretical physics,particle physics,leptons,natural sciences,physical sciences,theoretical physics,particle physics,particle accelerator,natural sciences,physical sciences,astronomy,physical cosmology,natural sciences,biological sciences,ecology,ecosystems,social sciences,other social sciences,development studies,development theories,post-colonial theories,humanities,history and archaeology,history,natural sciences,biological sciences,ecology,engineering and technology,materials engineering,fibers,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,smart sensors,natural sciences,computer and information sciences,computational science,multiphysics,natural sciences,chemical sciences,electrochemistry,electrolysis,natural sciences,biological sciences,biochemistry,biomolecules,lipids,natural sciences,chemical sciences,catalysis,natural sciences,chemical sciences,organic chemistry,aliphatic compounds,natural sciences,chemical sciences,inorganic chemistry,metalloids,medical and health sciences,clinical medicine,pneumology,natural sciences,biological sciences,microbiology,bacteriology,medical and health sciences,basic medicine,physiology,pathophysiology,natural sciences,biological sciences,genetics,RNA,engineering and technology,materials engineering,fibers,natural sciences,biological sciences,genetics,DNA,engineering and technology,nanotechnology,nano-materials,two-dimensional nanostructures,graphene,engineering and technology,materials engineering,composites,natural sciences,mathematics,pure mathematics,topology,natural sciences,chemical sciences,polymer sciences,natural sciences,mathematics,pure mathematics,geometry,engineering and technology,environmental engineering,energy and fuels,renewable energy,solar energy,natural sciences,chemical sciences,catalysis,photocatalysis,natural sciences,biological sciences,botany,social sciences,sociology,demography,mortality,natural sciences,biological sciences,genetics,mutation,medical and health sciences,clinical medicine,oncology,medical and health sciences,basic medicine,neurology,epilepsy,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,biological sciences,genetics,mutation,natural sciences,biological sciences,biochemistry,biomolecules,proteins,social sciences,sociology,social issues,social inequalities,social sciences,psychology,social sciences,law,criminology,natural sciences,chemical sciences,catalysis,natural sciences,biological sciences,biodiversity conservation,humanities,history and archaeology,history,humanities,arts,musicology,engineering and technology,environmental engineering,ecosystem-based management,climatic change mitigation,social sciences,sociology,governance,social sciences,political sciences,political transitions,elections,natural sciences,biological sciences,microbiology,bacteriology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,antibiotics,natural sciences,physical sciences,optics,microscopy,medical and health sciences,health sciences,nutrition,natural sciences,physical sciences,optics,spectroscopy,natural sciences,computer and information sciences,databases,natural sciences,earth and related environmental sciences,physical geography,cartography,geographic information systems,natural sciences,biological sciences,ecology,ecosystems,humanities,languages and literature,literature studies,history of literature,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,natural sciences,chemical sciences,catalysis,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,biosensors,natural sciences,physical sciences,electromagnetism and electronics,microelectronics,medical and health sciences,medical biotechnology,implants,humanities,history and archaeology,history,humanities,languages and literature,literature studies,literary genres,essays,social sciences,psychology,humanities,arts,musicology,humanities,philosophy, ethics and religion,philosophy,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,natural sciences,computer and information sciences,software,natural sciences,computer and information sciences,databases,engineering and technology,other engineering and technologies,food technology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,health sciences,nutrition,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,astronautical engineering,spacecraft,natural sciences,physical sciences,astronomy,planetary sciences,asteroids,humanities,history and archaeology,history,medical and health sciences,health sciences,nutrition,medical and health sciences,basic medicine,pathology,medical and health sciences,clinical medicine,allergology,medical and health sciences,basic medicine,immunology,immunotherapy,medical and health sciences,clinical medicine,transplantation,natural sciences,biological sciences,biochemistry,biomolecules,lipids,natural sciences,biological sciences,genetics,RNA,transcriptomes,natural sciences,biological sciences,genetics,genomes,social sciences,psychology,natural sciences,chemical sciences,catalysis,engineering and technology,nanotechnology,nano-materials,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,mathematics,pure mathematics,geometry,natural sciences,physical sciences,classical mechanics,fluid mechanics,microfluidics,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,medical and health sciences,clinical medicine,oncology,medical and health sciences,basic medicine,physiology,medical and health sciences,health sciences,nutrition,agricultural sciences,agriculture, forestry, and fisheries,agriculture,natural sciences,biological sciences,microbiology,mycology,ethnolichenology,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,physical sciences,optics,microscopy,natural sciences,biological sciences,ecology,ecosystems,natural sciences,biological sciences,zoology,entomology,engineering and technology,materials engineering,amorphous solids,amorphous semiconductors,medical and health sciences,clinical medicine,oncology,natural sciences,computer and information sciences,databases,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,engineering and technology,materials engineering,colors,social sciences,political sciences,government systems,democracy,social sciences,sociology,social issues,natural sciences,biological sciences,zoology,mammalogy,primatology,natural sciences,biological sciences,genetics,DNA,natural sciences,biological sciences,genetics,mutation,medical and health sciences,clinical medicine,oncology,natural sciences,biological sciences,genetics,epigenetics,epigenomes,engineering and technology,environmental engineering,energy and fuels,natural sciences,computer and information sciences,data science,natural sciences,physical sciences,astronomy,physical cosmology,natural sciences,biological sciences,marine biology,natural sciences,physical sciences,theoretical physics,particle physics,neutrinos,natural sciences,physical sciences,astronomy,astrophysics,natural sciences,physical sciences,astronomy,stellar astronomy,supernova,natural sciences,biological sciences,neurobiology,humanities,philosophy, ethics and religion,philosophy,epistemology,medical and health sciences,clinical medicine,oncology,skin cancer,melanoma,medical and health sciences,basic medicine,immunology,immunotherapy,medical and health sciences,basic medicine,neurology,parkinson,agricultural sciences,agriculture, forestry, and fisheries,agriculture,humanities,history and archaeology,history,natural sciences,biological sciences,evolutionary biology,natural sciences,biological sciences,ecology,evolutionary ecology,agricultural sciences,agriculture, forestry, and fisheries,agriculture,grains and oilseeds,cereals,natural sciences,computer and information sciences,internet,internet of things,natural sciences,computer and information sciences,databases,social sciences,political sciences,political policies,public policies,natural sciences,chemical sciences,catalysis,photocatalysis,natural sciences,chemical sciences,electrochemistry,electrolysis,engineering and technology,nanotechnology,nano-materials,natural sciences,physical sciences,optics,spectroscopy,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,astronautical engineering,spacecraft,engineering and technology,environmental engineering,energy and fuels,renewable energy,hydrogen energy,natural sciences,biological sciences,botany,natural sciences,chemical sciences,polymer sciences,humanities,history and archaeology,history,natural sciences,chemical sciences,inorganic chemistry,alkaline earth metals,natural sciences,mathematics,pure mathematics,discrete mathematics,mathematical logic,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,cardiac arrhythmia,social sciences,sociology,demography,mortality,natural sciences,biological sciences,biochemistry,biomolecules,proteins,natural sciences,biological sciences,genetics,mutation,social sciences,sociology,demography,census,natural sciences,physical sciences,astronomy,physical cosmology,natural sciences,mathematics,pure mathematics,algebra,humanities,languages and literature,linguistics,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,antibiotics,humanities,history and archaeology,history,ancient history,natural sciences,earth and related environmental sciences,environmental sciences,pollution,humanities,languages and literature,literature studies,history of literature,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,satellite technology,natural sciences,physical sciences,astronomy,social sciences,sociology,demography,mortality,agricultural sciences,agriculture, forestry, and fisheries,agriculture,natural sciences,earth and related environmental sciences,atmospheric sciences,climatology,natural sciences,biological sciences,evolutionary biology,agricultural sciences,animal and dairy science,domestic animals,animal husbandry,agricultural sciences,animal and dairy science,dairy,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,health sciences,nutrition,engineering and technology,mechanical engineering,tribology,lubrication,humanities,history and archaeology,history,ancient history,social sciences,other social sciences,development studies,development theories,global development studies,globalization,natural sciences,biological sciences,b

In [18]:
refs = paths.split(',')
refs = set(refs)
refs = [r.strip() for r in refs]
refs

['',
 'analytical chemistry',
 'seismology',
 'electrocatalysis',
 'obstetrics',
 'human rights law',
 'ancient history',
 'epigenetics',
 'algebra',
 'solar astronomy',
 'physical chemistry',
 'stem cells',
 'environmental engineering',
 'lab on a chip',
 'natural language processing',
 'visual arts',
 'ocean engineering',
 'media and communications',
 'thermochemistry',
 'coronaviruses',
 'bioprocessing technologies',
 'terrorism',
 'DNA',
 'ecosystems',
 'organic reactions',
 'underwater archaeology',
 'protein folding',
 'wastewater treatment processes',
 'vegetable growing',
 'palynology',
 'macroeconomics',
 'coating and films',
 'graphic design',
 'tuberculosis',
 'reproductive biology',
 'political violence',
 'geothermal energy',
 'hydrogen energy',
 'polyhydroxyalkanoates',
 'discrete mathematics',
 'super-Earths',
 'phycology',
 'physical anthropology',
 'data exchange',
 'metallurgy',
 'combinatorics',
 'navigation systems',
 'medicinal chemistry',
 'aeronautical engineering',
 'emergency medicine',
 'development studies',
 'rheumatology',
 'other engineering and technologies',
 'physical cosmology',
 'fodder',
 'topology',
 'performing arts',
 'prostate cancer',
 'z bosons',
 'medical engineering',
 'control engineering',
 'meteorites',
 'algebraic geometry',
 'sustainable economy',
 'democracy',
 'genomes',
 'ecology',
 'invertebrate zoology',
 'gravitational waves',
 'computer processors',
 'compost',
 'habitat conservation',
 'biofuels',
 'climate change adaptation',
 'genetic engineering',
 'remanufacturing',
 'hydroelectricity',
 'production economics',
 'mathematical physics',
 'didactics',
 'software',
 'international protection of human rights',
 'public administration',
 'applied mathematics',
 'carbohydrates',
 'hematology',
 'data protection',
 'thermodynamic engineering',
 'data networks',
 'zoology',
 'electronic engineering',
 'cetology',
 'quarks',
 'embryology',
 'mathematical model',
 'optical astronomy',
 'animal husbandry',
 'radiation chemistry',
 'pathophysiology',
 'microbiomes',
 'speech-language pathology',
 'architecture engineering',
 'physical sciences',
 'galactic astronomy',
 'biogeochemistry',
 'political sciences',
 'fermions',
 'autonomous robots',
 'pancreatic cancer',
 'nano-materials',
 'ontology',
 'ecohydrology',
 'information engineering',
 'graphene',
 'coal',
 'posttraumatic stress disorder',
 'fisheries',
 'ultrasound',
 'antivirals',
 'mobile phones',
 'exposomes',
 'genetics',
 'other social sciences',
 'mobile network',
 'software applications',
 'clinical medicine',
 'soft matter physics',
 'functional morphology',
 'productivity',
 'basic medicine',
 'enzymes',
 'higgs bosons',
 'pharmacology and pharmacy',
 'physical geography',
 'structural health monitoring',
 'nanotechnology',
 'waste treatment processes',
 'volcanology',
 'amines',
 'skin cancer',
 'social biomedical sciences',
 'electric power transmission',
 'eastern religions',
 'vascular diseases',
 'physiotherapy',
 'heat engineering',
 'influenza',
 'proteomics',
 'classical mechanics',
 'childbirth',
 'knowledge engineering',
 'food packaging',
 'paleoecology',
 'social sciences',
 'neutron stars',
 'sustainable building',
 'computational fluid dynamics',
 'ozone depletion',
 'black holes',
 'microelectronics',
 'plasma physics',
 'medical and health sciences',
 'history of literature',
 'electromagnetism',
 'nuclear physics',
 'astrochemistry',
 'atmospheric sciences',
 'social work',
 'calorimetry',
 'ethnology',
 'substance abuse',
 'contemporary history',
 'agriculture',
 'biomass',
 'melanoma',
 'behavioural psychology',
 'desalination',
 'diagnostic technologies',
 'vaccines',
 'and fisheries',
 'dendrochronology',
 'gene therapy',
 'dairy',
 'nursing',
 'immunisation',
 'psychotherapy',
 'humanities',
 'fourier analysis',
 'pandemic risks',
 'public services',
 'social developments',
 'pneumology',
 'business models',
 'food technology',
 'developmental biology',
 'two-dimensional nanostructures',
 'drones',
 'deep learning',
 'health sciences',
 'geophysics',
 'world wide web',
 'ethics',
 'celestial mechanics',
 'human rights violations',
 'speleology',
 'microbiology',
 'psychology',
 'applied mechanics',
 'political philosophy',
 'robotics',
 'crisis management',
 'biological interactions',
 'medieval history',
 'postnatal care',
 'arts',
 'essays',
 'chemical process engineering',
 'educational sciences',
 'ethnomusicology',
 'polyurethane',
 'revolutions',
 'functional analysis',
 'breast cancer',
 'data processing',
 'religions',
 'water engineering',
 'structural engineering',
 'molecular biology',
 'history and archaeology',
 'dramaturgy',
 'inclusive education',
 'econometrics',
 'social geography',
 'viticulture',
 'modeling of diseases spread',
 'heredity',
 'bioarchaeology',
 'diabetes',
 'gender equality',
 'galaxy evolution',
 'hepatology',
 'separation technologies',
 'pharmaceutical drugs',
 'grains and oilseeds',
 'fruit growing',
 'mineralogy',
 'computer vision',
 'anthropology',
 'photovoltaic',
 'constitutional law',
 'mutation',
 'medieval philosophy',
 'organic chemistry',
 'multiphysics',
 'electric energy',
 'spintronics',
 'cervical cancer',
 'neurology',
 'data science',
 'computer security',
 'transcriptomes',
 'additive manufacturing',
 'remote sensing',
 'foreign policy',
 'physiology',
 'apiculture',
 'nanocomposites',
 'aliphatic compounds',
 'development theories',
 'malaria',
 'inflammatory bowel disease',
 'linguistics',
 'primatology',
 'drainage basins',
 'agricultural sciences',
 'eukaryotic genomes',
 'geomorphology',
 'water treatment processes',
 'mathematical logic',
 'geochemistry',
 'optical sensors',
 'public policies',
 'heuristic programming',
 'electronic engineering',
 'global development studies',
 'recycling',
 'islam',
 'ergonomics',
 'computational intelligence',
 'public transport',
 'mining and mineral processing',
 'microseisms',
 'animal feed',
 'cultural and economic geography',
 'natural sciences',
 'ethics and religion',
 'evolutionary ecology',
 'petroleum',
 'radiochemistry',
 'synthetic dyes',
 'big bang',
 'reinforcement learning',
 'optics',
 'metalloids',
 'alkali metals',
 'genetic selection',
 'tribology',
 'glaciology',
 'pandemics',
 'pathology',
 'medical biotechnology',
 'biosensors',
 'plate tectonics',
 'armed conflicts',
 'computer and information sciences',
 'lipids',
 'manufacturing engineering',
 'soil sciences',
 'ethology',
 'climatology',
 'control systems',
 'e-governance',
 'reproductive medicine',
 'art history',
 'databases',
 'political policies',
 'simulation software',
 'history of philosophy',
 'planetary sciences',
 'judaism',
 'oceanography',
 'evolutionary biology',
 'game theory',
 'satellite navigation system',
 'mammalogy',
 'family planning',
 'super resolution microscopy',
 'agricultural biotechnology',
 'medical laboratory technology',
 'quantum computers',
 'glaucoma',
 'satellite technology',
 'analogue electronics',
 'computational neuroscience',
 'surgery',
 'fertility',
 'amorphous solids',
 'apidology',
 'leptons',
 'dermatology',
 'veterinary sciences',
 'urban studies',
 'toxicology',
 'national state of emergency',
 'otorhinolaryngology',
 'employment',
 'product engineering',
 'political communication',
 'power engineering',
 'corruption',
 'cosmochemistry',
 'active learning',
 'earth and related environmental sciences',
 'nuclear engineering',
 'biochemistry',
 'commerce',
 'system software',
 'health economics',
 'fibers',
 'human trafficking',
 'inorganic chemistry',
 'nonlinear optics',
 'mental processes',
 'women’s studies',
 'physical oceanography',
 'inertial navigation system',
 'age inequality',
 'laboratory samples analysis',
 'piezoelectrics',
 'transportation engineering',
 'anaesthesiology',
 'chromosomes',
 'subtractive manufacturing',
 'bioeconomy',
 'plant breeding',
 'literary theory',
 'soil management',
 'phonology',
 'social inequalities',
 'radio frequency',
 'amorphous semiconductors',
 'industrial relations',
 'mechatronics',
 'cardiovascular diseases',
 'nuclear medicine',
 'angiology',
 'census',
 'alcohols',
 'halogens',
 'forestry',
 'critical care medicine',
 'sexual violence',
 'meteorology',
 'mycology',
 'data mining',
 'combined heat and power',
 'electron microscopy',
 'e-commerce',
 'arithmetics',
 'modern history',
 'developmental psychology',
 'development economics',
 'video games',
 'environmental law',
 'microfluidics',
 'radar',
 'science and technology studies',
 'philosophy',
 'transition metals',
 'immunology',
 'gluons',
 'ethnoarchaeology',
 'catalysis',
 'virology',
 'literary genres',
 'geotechnics',
 'radio technology',
 'obesity',
 'biodiversity conservation',
 'natural satellites',
 'metabolomes',
 'climatic change mitigation',
 'textiles',
 'acoustics',
 'alkaline earth metals',
 'contemporary philosophy',
 'geometry',
 'microscopy',
 'information engineering',
 'literature studies',
 'photons',
 'zoonosis',
 'noble gases',
 'anatomy and morphology',
 'fibre optics',
 'logarithmic functions',
 'journalism',
 'fluid mechanics',
 'multidrug resistance',
 'ebola',
 'sedimentology',
 'epistemology',
 'operator algebra',
 'bose-einstein condensates',
 'criminology',
 'personalized medicine',
 'post-transition metals',
 'marine biology',
 'environmental biotechnology',
 'natural disasters',
 'planetary geology',
 'cardiac arrhythmia',
 'natural resources management',
 'electrical engineering',
 'social psychology',
 'optical networks',
 'composites',
 'numerical analysis',
 'cryptography',
 'anxiety disorders',
 'magnetic resonance imaging',
 'electrolysis',
 'general language studies',
 'parasitology',
 'molecular spintronics',
 'quantum chemistry',
 'superconductivity',
 'parkinson',
 'spacecraft',
 'big data',
 'racial inequality',
 'epigenomes',
 'proteins',
 'economics and business',
 'polylactic acid',
 'irrigation',
 'pedagogy',
 'crystals',
 'digital humanities',
 'comparative morphology',
 'sustainability sciences',
 'eHealth',
 'schizophrenia',
 'multiple sclerosis',
 'behavioural ecology',
 'planets',
 'innovation management',
 'aromatic compounds',
 'homeostasis',
 'social anthropology',
 'microtechnology',
 'taxation',
 'synthetic fuels',
 'virtual reality',
 'bioplastics',
 'comets',
 'health care services',
 'hydrocarbons',
 'solid-state physics',
 'structural biology',
 'botany',
 'geographic information systems',
 'astrophysics',
 'isotope geochemistry',
 'business and management',
 'smart sensors',
 'arboriculture',
 'other medical sciences',
 'gender studies',
 'electric power generation',
 'horticulture',
 'bioremediation',
 'differential equations',
 'gender inequality',
 'thermodynamics',
 'psychiatry',
 'solar energy',
 'forestry',
 'kidney diseases',
 'neurobiology',
 'asteroids',
 'fermentation',
 'civil society organisations',
 'library sciences',
 'biological morphology',
 'supercomputers',
 'psycholinguistics',
 'aerospace engineering',
 'molecular and chemical physics',
 'cells technologies',
 'spectroscopy',
 'mathematics',
 'quantum physics',
 'radiology',
 'supervised learning',
 'signal processing',
 'sign language',
 'fluid dynamics',
 'sustainable agriculture',
 'cultural anthropology',
 'antibiotic resistance',
 'RNA',
 'ethical principles',
 'organometallic chemistry',
 'asteroseismology',
 'gastroenterology',
 'mass spectrometry',
 'histology',
 'sexual health',
 'law enforcement',
 'energy and fuels',
 'languages and literature',
 'climatic changes',
 'sociology',
 'penology',
 'quantum field theory',
 'coastal ecosystems',
 'motion analysis',
 'government systems',
 'microeconomics',
 'orthopaedics',
 'ultrafast lasers',
 'industrial crops',
 'globalization',
 'photocatalysis',
 'unemployment',
 'flood risk management',
 'statistical mechanics',
 'sustainable architecture',
 'knowledge organization',
 'political economy',
 'bioartificial liver',
 'neutrinos',
 'colorectal cancer',
 'human rights',
 'palaeontology',
 'quasiparticles',
 'cereals',
 'computed tomography',
 'plant protection',
 'chemical sciences',
 'ecosystem-based management',
 'robotic surgery',
 'DNA viruses',
 'HIV',
 'phonetics',
 'digital electronics',
 'law',
 'economics',
 'hydrometeorology',
 'bayesian statistics',
 'odontology',
 'allergology',
 'rotorcraft',
 'internet of things',
 'carbon capture engineering',
 'nanomedicine',
 'drug resistance',
 'cell biology',
 'sleep disorders',
 'prime numbers',
 'tissue engineering',
 'space exploration',
 'distillation',
 'hydrology',
 'ceramics',
 'prokaryotic genomes',
 'stroke',
 'condensed matter physics',
 'crystallography',
 'soft robotics',
 'cardiology',
 'electric batteries',
 'nongovernmental organizations',
 'biophysics',
 'diagnostic imaging',
 'photochemistry',
 'post-colonial theories',
 'pharmacokinetics',
 'ornithology',
 'materials engineering',
 'industrial biotechnology',
 'arteriosclerosis',
 'entrepreneurship',
 'theoretical physics',
 'bureaucracy',
 'architectural design',
 'political transitions',
 'artificial intelligence',
 'inflammatory diseases',
 'pure mathematics',
 'public health',
 'exoplanetology',
 'transport',
 'biosphera',
 'paleoclimatology',
 'nanoelectronics',
 'pollution',
 'computational science',
 'bulk nanostructured materials',
 'telecommunications networks',
 'christianity',
 'riots',
 'biocomposites',
 'epilepsy',
 'environmental sciences',
 'family studies',
 'antibiotics',
 'archaeometry',
 'statistics and probability',
 'epidemiology',
 'drug discovery',
 'astronautical engineering',
 'immunotherapy',
 'climatic zones',
 'geochronology',
 'alzheimer',
 'animal and dairy science',
 'laser physics',
 'hepatitis B',
 'musicology',
 'folklore',
 'literary criticism',
 'particle physics',
 'archaeology',
 'generative artificial intelligence',
 'semiconductivity',
 'nanocrystals',
 'colors',
 'sensors',
 'knot theory',
 'atomic physics',
 'partial differential equations',
 'molecular evolution',
 'prehistory',
 'optoelectronics',
 'oncology',
 'mortality',
 'infectious diseases',
 'endocrinology',
 'cartography',
 'supernova',
 'ethnolichenology',
 'psychoanalysis',
 'biological behavioural sciences',
 'teleology',
 'woodworking',
 'nutrition',
 'waste management',
 'biomaterials',
 'electromagnetism and electronics',
 'petrology',
 'quantum optics',
 'paediatrics',
 'infrared astronomy',
 'domestic animals',
 'global navigation satellite system',
 'molecular genetics',
 'mechanical engineering',
 'governance',
 'inorganic compounds',
 'history',
 'internet',
 'fuel cells',
 'nephrology',
 'aircraft',
 'ecological restoration',
 'graft versus host disease',
 'leukemia',
 'automation',
 'renewable energy',
 'RNA viruses',
 'bioreactors',
 'nuclear chemistry',
 'history of medicine',
 'biological sciences',
 'synthetic biology',
 'dark matter',
 'metaphysics',
 'chemical engineering',
 'lung cancer',
 'civil society',
 'particle accelerator',
 'machine learning',
 'astronomy',
 'engineering and technology',
 'vehicle engineering',
 'ophthalmology',
 'cavity optomechanics',
 'cognitive neuroscience',
 'fossil energy',
 'modern and contemporary art',
 'lubrication',
 'stellar astronomy',
 'cinematography',
 'cell signaling',
 'air pollution engineering',
 'human migrations',
 'gynaecology',
 'graph theory',
 'observational astronomy',
 'social issues',
 'gerontology',
 'dementia',
 'cognitive psychology',
 'asthma',
 'agroecology',
 'solar physics',
 'international law',
 'ethical theories',
 'aldehydes',
 'ideologies',
 'nuclear fusion',
 'elections',
 'geology',
 'biosensing',
 'implants',
 'demography',
 'computer hardware',
 'energy conversion',
 'other humanities',
 'radio astronomy',
 'biomolecules',
 'giant planets',
 'nanophotonics',
 'biocatalysis',
 'organic amorphous solids',
 'polymer sciences',
 'bacteriology',
 'agronomy',
 'mathematical analysis',
 'nucleotides',
 'telecommunications',
 'cytology',
 'organ on a chip',
 'software development',
 'electrochemistry',
 'entomology',
 'dynamical systems',
 'extragalactic astronomy',
 'hepatitis C',
 'wind energy',
 'transplantation',
 'civil engineering',
 'biomass energy']

In [19]:
print (len(refs))

795

In [20]:
projects_no_widening['fundingScheme'].unique()

array(['HORIZON-ERC', 'HORIZON-EIC-ACC', 'HORIZON-TMA-MSCA-PF-GF',
       'HORIZON-ERC-POC', 'HORIZON-JU-CSA', 'HORIZON-TMA-MSCA-PF-EF',
       'HORIZON-TMA-MSCA-DN-JD', 'HORIZON-TMA-MSCA-DN', 'HORIZON-EIC',
       'HORIZON-TMA-MSCA-Cofund-P', 'HORIZON-RIA', 'HORIZON-ERC-SYG',
       'HORIZON-CSA', 'HORIZON-TMA-MSCA-Cofund-D',
       'HORIZON-TMA-MSCA-DN-ID', 'HORIZON-EIC-ACC-BF',
       'HORIZON-TMA-MSCA-SE', 'HORIZON-IA', 'HORIZON-JU-RIA',
       'EURATOM-IA', 'HORIZON-JU-IA', 'EURATOM-RIA', 'HORIZON-EIT-KIC',
       'HORIZON-PCP', 'HORIZON-COFUND'], dtype=object)

In [21]:
projects_filt = projects_no_widening[projects_no_widening['fundingScheme'].isin(['HORIZON-RIA','RIA'])]

In [22]:
projects_filt

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
214,101226563,M-CARE,SIGNED,Implementation of an Integrated Care Model for...,2025-07-01,2030-06-30,4000000,4000000,HORIZON.2.1,HORIZON-HLTH-2024-DISEASE-13-01,2025-07-05,HORIZON,HORIZON-HLTH-2024-DISEASE-13,HORIZON-HLTH-2024-DISEASE-13,HORIZON-RIA,Addressing multiple long-term conditions inclu...,2025-07-14 11:09:45,274520,NaN,"Multiple long-term chronic conditions, Primar..."
347,101180091,COASTS,SIGNED,Coastal Observation Advances leveraging Space ...,2024-11-01,2027-10-31,"1971987,5","1971987,5",HORIZON.2.4,HORIZON-EUSPA-2023-SPACE-01-43,2024-10-17,HORIZON,HORIZON-EUSPA-2023-SPACE,HORIZON-EUSPA-2023-SPACE,HORIZON-RIA,"Coastal zones are critical regions, accommodat...",2025-11-26 10:40:49,267052,10.3030/101180091,"Blue Carbon, coastal resilience, downstream se..."
626,101138807,SiToLub,SIGNED,Simulation Tools for the design of safe and su...,2024-01-01,2027-12-31,0,"5195467,19",HORIZON.2.4,HORIZON-CL4-2023-RESILIENCE-01-23,2023-12-06,HORIZON,HORIZON-CL4-2023-RESILIENCE-01,HORIZON-CL4-2023-RESILIENCE-01,HORIZON-RIA,SiToLub project aims to develop a digital tool...,2025-10-20 17:38:03,259116,10.3030/101138807,"Lubricants, additives, simulation, safe, susta..."
678,101135082,IRE,SIGNED,Intelligent Robotic Endoscopes for Improved He...,2024-03-01,2028-02-29,6189085,6189082,HORIZON.2.4,HORIZON-CL4-2023-DIGITAL-EMERGING-01-01,2023-11-23,HORIZON,HORIZON-CL4-2023-DIGITAL-EMERGING-01,HORIZON-CL4-2023-DIGITAL-EMERGING-01,HORIZON-RIA,In Intelligent Robotic Endoscopes (IRE) for Im...,2025-10-30 21:47:38,259555,10.3030/101135082,"Simulation-driven deep learning, Autonomous co..."
1415,101136935,ENDEAVOR,SIGNED,Endoscopic brush cytology and single cell clin...,2024-01-01,2028-12-31,"6726488,69","6726488,68",HORIZON.2.1,HORIZON-MISS-2023-CANCER-01-03,2023-12-11,HORIZON,HORIZON-MISS-2023-CANCER-01,HORIZON-MISS-2023-CANCER-01,HORIZON-RIA,In many European countries the recent rise in ...,2025-11-05 11:14:52,258989,10.3030/101136935,"Clinical trial, personalised medicine, quali..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15216,101136670,GLIOMATCH,SIGNED,The malignant Glioma immuno-oncology matchmake...,2024-01-01,2028-12-31,"11389958,75","11389958,75",HORIZON.2.1,HORIZON-MISS-2023-CANCER-01-01,2023-12-07,HORIZON,HORIZON-MISS-2023-CANCER-01,HORIZON-MISS-2023-CANCER-01,HORIZON-RIA,"""Adult and paediatric malignant glioma (GBM an...",2025-10-20 17:38:03,259415,10.3030/101136670,"Radio-multiomics, Immunotherapy using DC vacci..."
15282,101135431,CRYSALIS,SIGNED,Cryogenic storage and refuelling in space,2024-01-01,2028-06-30,"7430993,75","7430993,75",HORIZON.2.4,HORIZON-CL4-2023-SPACE-01-22,2023-11-21,HORIZON,HORIZON-CL4-2023-SPACE-01,HORIZON-CL4-2023-SPACE-01,HORIZON-RIA,To move away from the dependence on hydrazine ...,2025-07-25 09:49:12,259175,10.3030/101135431,"cryogenic propellent, in-orbit refuelling, ZBO..."
17522,101180133,SNOWCOP,SIGNED,Unlocking the full potential of Copernicus dat...,2024-10-01,2027-09-30,0,1013435,HORIZON.2.4,HORIZON-EUSPA-2023-SPACE-01-46,2024-09-24,HORIZON,HORIZON-EUSPA-2023-SPACE,HORIZON-EUSPA-2023-SPACE,HORIZON-RIA,The current Copernicus snow water equivalent (...,2025-06-17 18:24:20,266356,10.3030/101180133,"Snow water equivalent, SWE, Snow model, cloud ..."
18349,101134993,NGI TRANSOCEANIC,SIGNED,NGI platform for coordinated EU-US Open Calls ...,2024-01-01,2027-12-31,4000000,4000000,HORIZON.2.4,HORIZON-CL4-2023-HUMAN-01-13,2023-11-17,HORIZON,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-RIA,NGI TRANSOCEANIC builds on the success of the ...,2023-11-23 09:38:58,258379,10.3030/101134993,"International cooperation, Next Generation Int..."
19024,101156751,SHIELD,SIGNED,Strategic Health Initiatives for Effective Dis...,2024-12-01,2028-11-30,0,"6552184,1",HORIZON.2.1,HORIZON-HLTH-2024-STAYHLTH-01-05-two-stage,2024-11-06,HORIZON,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-RIA,The prevalence of Non-Communicable Diseases is...,2024-11-15 16:33:20,267337,10.3030/101156751,"AI, risk-stratification, explainability, monit..."

In [23]:
projects_ = projects_filt[['id','acronym','title','startDate','endDate','totalCost','legalBasis','topics','masterCall','subCall','fundingScheme','objective','grantDoi']]

In [24]:
projects_['topics'].tolist()

['HORIZON-HLTH-2024-DISEASE-13-01',
 'HORIZON-EUSPA-2023-SPACE-01-43',
 'HORIZON-CL4-2023-RESILIENCE-01-23',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-01',
 'HORIZON-MISS-2023-CANCER-01-03',
 'HORIZON-CL4-2023-SPACE-01-72',
 'HORIZON-CL4-2023-TWIN-TRANSITION-01-45',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-46',
 'HORIZON-HLTH-2024-DISEASE-03-13-two-stage',
 'HORIZON-CL4-2023-RESILIENCE-01-34',
 'HORIZON-HLTH-2022-DISEASE-07-03',
 'HORIZON-MISS-2023-CANCER-01-03',
 'HORIZON-EUROHPC-JU-2023-QEC-05-01',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-46',
 'HORIZON-CL3-2024-INFRA-01-03',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-03',
 'HORIZON-HLTH-2024-DISEASE-03-11-two-stage',
 'HORIZON-HLTH-2024-DISEASE-13-01',
 'HORIZON-HLTH-2024-TOOL-05-06-two-stage',
 'HORIZON-HLTH-2024-ENVHLTH-02-06-two-stage',
 'HORIZON-CL5-2023-D3-02-07',
 'HORIZON-CL5-2024-D3-01-07',
 'HORIZON-CL5-2023-D3-02-05',
 'HORIZON-CL5-2024-D1-01-02',
 'HORIZON-CL5-2024-D3-01-10',
 'HORIZON-CL5-2023-D5-01-11',
 'HORIZON-CL5-2024-D3-01-04',
 'HORIZON-CL5-2024-D5-01-02',
 'HORIZON-CL5-2024-D5-01-07',
 'HORIZON-CL5-2024-D2-01-04',
 'HORIZON-CL5-2023-D3-01-13',
 'HORIZON-CL5-2023-D3-02-05',
 'HORIZON-CL5-2023-D6-01-11',
 'HORIZON-CL5-2024-D3-01-14',
 'HORIZON-CL5-2024-D3-01-10',
 'HORIZON-CL5-2023-D3-02-02',
 'HORIZON-CL5-2024-D2-01-04',
 'HORIZON-CL5-2024-D1-01-06',
 'HORIZON-CL5-2024-D5-01-08',
 'HORIZON-CL5-2024-D3-01-15',
 'HORIZON-CL5-2024-D5-01-07',
 'HORIZON-CL5-2023-D3-01-05',
 'HORIZON-CL5-2024-D3-02-08',
 'HORIZON-CL5-2024-D5-01-18',
 'HORIZON-CL5-2023-D3-02-15',
 'HORIZON-CL5-2024-D1-01-07',
 'HORIZON-CL5-2024-D3-01-04',
 'HORIZON-CL5-2023-D5-01-09',
 'HORIZON-HLTH-2024-DISEASE-08-20',
 'HORIZON-HLTH-2024-DISEASE-08-20',
 'HORIZON-CL4-2024-SPACE-01-73',
 'HORIZON-INFRA-2023-DEV-01-03',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-05',
 'HORIZON-CL5-2023-D3-03-01',
 'HORIZON-CL5-2023-D3-02-07',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-11',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-12',
 'HORIZON-CL5-2023-D3-02-15',
 'HORIZON-CL5-2023-D1-01-02',
 'HORIZON-CL5-2023-D2-02-02',
 'HORIZON-MISS-2024-NEB-01-01',
 'HORIZON-CL6-2024-CLIMATE-02-3',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-CL6-2023-FARM2FORK-01-20',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-CL6-2022-FARM2FORK-01-09',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-CL6-2023-ZEROPOLLUTION-01-3',
 'HORIZON-CL6-2024-COMMUNITIES-01-3',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-CL6-2024-CircBio-02-1-two-stage',
 'HORIZON-CL6-2024-ZEROPOLLUTION-02-2-two-stage',
 'HORIZON-INFRA-2024-TECH-01-01',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-CL5-2023-D1-01-02',
 'HORIZON-CL4-2024-SPACE-01-73',
 'HORIZON-CL4-2024-SPACE-01-73',
 'HORIZON-INFRA-2023-TECH-01-01',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-12',
 'HORIZON-CL4-2024-SPACE-01-73',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-11',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-11',
 'HORIZON-CL4-2024-DIGITAL-EMERGING-01-31',
 'HORIZON-CL4-2023-DIGITAL-EMERGING-01-40',
 'HORIZON-CL5-2024-D2-01-01',
 'HORIZON-CL5-2023-D5-01-11',
 'HORIZON-INFRA-2024-DEV-01-03',
 'HORIZON-CL5-2023-D1-01-01',
 'HORIZON-CL5-2024-D1-01-03',
 'HORIZON-HLTH-2024-DISEASE-03-11-two-stage',
 'HORIZON-CL5-2024-D6-01-01',
 'HORIZON-HLTH-2024-DISEASE-08-20',
 'HORIZON-MISS-2024-CLIMA-01-03',
 'HORIZON-HLTH-2023-TOOL-05-04',
 'HORIZON-HLTH-2023-DISEASE-03-17',
 'HORIZON-CL5-2023-D1-01-11',
 'HORIZON-CL2-2024-DEMOCRACY-01-07',
 'HORIZON-CL2-2024-HERITAGE-01-05',
 'HORIZON-CL2-2024-TRANSFORMATIONS-01-06',
 'HORIZON-CL4-2024-DIGITAL-EMERGING-01-21',
 'HORIZON-CL4-2024-SPACE-01-73',
 'HORIZON-INFRA-2023-DEV-01-03',
 'HORIZON-HLTH-2023-DISEASE-03-03',
 'HORIZON-CL5-2024-D1-01-02',
 'HORIZON-CL5-2024-D2-01-01',
 'HORIZON-CL5-2024-D2-02-02',
 'HORIZON-HLTH-2024-DISEASE-13-01',
 'HORIZON-HLTH-2023-ENVHLTH-02-01',
 'HORIZON-HLTH-2024-TOOL-11-02',
 'HORIZON-HLTH-2024-DISEASE-03-08-two-stage',
 'HORIZON-CL4-2024-TWIN-TRANSITION-01-46',
 'HORIZON-CL2-2024-HERITAGE-01-05',
 'HORIZON-CL2-2024-TRANSFORMATIONS-01-11',
 'HORIZON-CL2-2024-DEMOCRACY-01-09',
 'HORIZON-CL2-2024-TRANSFORMATIONS-01-11',
 'HORIZON-MISS-2023-CANCER-01-01',
 'HORIZON-CL4-2023-SPACE-01-22',
 'HORIZON-EUSPA-2023-SPACE-01-46',
 'HORIZON-CL4-2023-HUMAN-01-13',
 'HORIZON-HLTH-2024-STAYHLTH-01-05-two-stage']

In [25]:
# Define function to assign clusters
def assign_cluster(topic):
    if "CL2" in topic:
        return "Cluster 2"
    elif "CL3" in topic:
        return "Cluster 3"
    elif "CL4" in topic:
        return "Cluster 4"
    elif "CL5" in topic:
        return "Cluster 5"
    elif "CL6" in topic:
        return "Cluster 6"
    elif "HLTH" in topic:
        return "Cluster Health"
    elif "MISS" in topic:
        return "Cluster MISS"
    else:
        return "Other"

# Apply function to create a new column
projects_["cluster"] = projects_["topics"].apply(assign_cluster)

C:\Users\user\AppData\Local\Temp\ipykernel_25232\2163152521.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  projects_["cluster"] = projects_["topics"].apply(assign_cluster)

In [26]:
projects_

,id,acronym,title,startDate,endDate,totalCost,legalBasis,topics,masterCall,subCall,fundingScheme,objective,grantDoi,cluster
214,101226563,M-CARE,Implementation of an Integrated Care Model for...,2025-07-01,2030-06-30,4000000,HORIZON.2.1,HORIZON-HLTH-2024-DISEASE-13-01,HORIZON-HLTH-2024-DISEASE-13,HORIZON-HLTH-2024-DISEASE-13,HORIZON-RIA,Addressing multiple long-term conditions inclu...,NaN,Cluster Health
347,101180091,COASTS,Coastal Observation Advances leveraging Space ...,2024-11-01,2027-10-31,"1971987,5",HORIZON.2.4,HORIZON-EUSPA-2023-SPACE-01-43,HORIZON-EUSPA-2023-SPACE,HORIZON-EUSPA-2023-SPACE,HORIZON-RIA,"Coastal zones are critical regions, accommodat...",10.3030/101180091,Other
626,101138807,SiToLub,Simulation Tools for the design of safe and su...,2024-01-01,2027-12-31,0,HORIZON.2.4,HORIZON-CL4-2023-RESILIENCE-01-23,HORIZON-CL4-2023-RESILIENCE-01,HORIZON-CL4-2023-RESILIENCE-01,HORIZON-RIA,SiToLub project aims to develop a digital tool...,10.3030/101138807,Cluster 4
678,101135082,IRE,Intelligent Robotic Endoscopes for Improved He...,2024-03-01,2028-02-29,6189085,HORIZON.2.4,HORIZON-CL4-2023-DIGITAL-EMERGING-01-01,HORIZON-CL4-2023-DIGITAL-EMERGING-01,HORIZON-CL4-2023-DIGITAL-EMERGING-01,HORIZON-RIA,In Intelligent Robotic Endoscopes (IRE) for Im...,10.3030/101135082,Cluster 4
1415,101136935,ENDEAVOR,Endoscopic brush cytology and single cell clin...,2024-01-01,2028-12-31,"6726488,69",HORIZON.2.1,HORIZON-MISS-2023-CANCER-01-03,HORIZON-MISS-2023-CANCER-01,HORIZON-MISS-2023-CANCER-01,HORIZON-RIA,In many European countries the recent rise in ...,10.3030/101136935,Cluster MISS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15216,101136670,GLIOMATCH,The malignant Glioma immuno-oncology matchmake...,2024-01-01,2028-12-31,"11389958,75",HORIZON.2.1,HORIZON-MISS-2023-CANCER-01-01,HORIZON-MISS-2023-CANCER-01,HORIZON-MISS-2023-CANCER-01,HORIZON-RIA,"""Adult and paediatric malignant glioma (GBM an...",10.3030/101136670,Cluster MISS
15282,101135431,CRYSALIS,Cryogenic storage and refuelling in space,2024-01-01,2028-06-30,"7430993,75",HORIZON.2.4,HORIZON-CL4-2023-SPACE-01-22,HORIZON-CL4-2023-SPACE-01,HORIZON-CL4-2023-SPACE-01,HORIZON-RIA,To move away from the dependence on hydrazine ...,10.3030/101135431,Cluster 4
17522,101180133,SNOWCOP,Unlocking the full potential of Copernicus dat...,2024-10-01,2027-09-30,0,HORIZON.2.4,HORIZON-EUSPA-2023-SPACE-01-46,HORIZON-EUSPA-2023-SPACE,HORIZON-EUSPA-2023-SPACE,HORIZON-RIA,The current Copernicus snow water equivalent (...,10.3030/101180133,Other
18349,101134993,NGI TRANSOCEANIC,NGI platform for coordinated EU-US Open Calls ...,2024-01-01,2027-12-31,4000000,HORIZON.2.4,HORIZON-CL4-2023-HUMAN-01-13,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-RIA,NGI TRANSOCEANIC builds on the success of the ...,10.3030/101134993,Cluster 4
19024,101156751,SHIELD,Strategic Health Initiatives for Effective Dis...,2024-12-01,2028-11-30,0,HORIZON.2.1,HORIZON-HLTH-2024-STAYHLTH-01-05-two-stage,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-HLTH-2024-STAYHLTH-01-two-stage,HORIZON-RIA,The prevalence of Non-Communicable Diseases is...,10.3030/101156751,Cluster Health

In [27]:
projects_.to_csv('projects.csv',index=False,sep='|')

In [28]:
orgs_ = orgs_no_widening[orgs_no_widening['projectID'].isin(projects_['id'].tolist())]

In [29]:
orgs_

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
1224,101226563,M-CARE,999878911,NaN,UNIVERSITY OF GHANA,UNIVERSITY OF GHANA,False,HES,"G4-488-7076, J.B. DANQUAH ROAD, OFF J.J. RAWLI...",NaN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 11:09:45,1905947,3,participant,800250.00,800250.00,800250,False,NaN
1225,101226563,M-CARE,954530344,NL851029279B01,STICHTING VU,NaN,False,HES,DE BOELELAAN 1105,1081 HV,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 11:09:45,1905554,6,participant,262500.00,262500.00,262500,False,NaN
1226,101226563,M-CARE,999861063,GB629588094,LONDON SCHOOL OF ECONOMICS AND POLITICAL SCIENCE,NaN,False,HES,Houghton Street 1,WC2A 2AE,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 11:09:45,1908354,7,participant,220756.25,220756.25,"220756,25",False,NaN
1227,101226563,M-CARE,999991043,DK29979812,KOBENHAVNS UNIVERSITET,UCPH,False,HES,NORREGADE 10,1165,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 11:09:45,1906270,2,participant,146875.00,146875.00,146875,False,NaN
1228,101226563,M-CARE,915614914,NaN,LIRA UNIVERSITY,NaN,False,HES,BLOCK 7 PLOT 1162 AYERE VILLAGE BARAPWO PARISH...,NaN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 11:09:45,1993486,5,participant,614243.75,614243.75,"614243,75",False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118939,101156751,SHIELD,999809071,IE6609370G,UNIVERSITY OF LIMERICK,UNIVERSITY OF LIMERICK,False,HES,"NATIONAL TECHNOLOGICAL PARK, PLASSEY",-,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-11-15 16:33:20,1905867,5,participant,1098085.00,1098085.00,0,False,NaN
118940,101156751,SHIELD,999655229,IT08882901005,CONSORZIO PER LA RICERCA NELL' AUTOMATICA E NE...,CRAT,False,REC,VIA GIOVANNI NICOTERA 29,00195,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-11-15 16:33:20,1913587,4,participant,953500.00,953500.00,0,False,NaN
118941,101156751,SHIELD,999481987,ESQ2801221I,SERVICIO MADRILENO DE SALUD,SERMAS,False,PUB,"Paseo De la Castellana, 280",28046,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-11-15 16:33:20,1906277,2,participant,944062.50,944062.50,0,False,NaN
118942,101156751,SHIELD,999840596,IT01086760723,UNIVERSITA DEGLI STUDI DI BARI ALDO MORO,UNIBA,False,HES,PIAZZA UMBERTO I 1,70121,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-11-15 16:33:20,1919411,6,participant,746187.50,746187.50,0,False,NaN
118943,101156751,SHIELD,999974844,ESQ2818015F,UNIVERSIDAD POLITECNICA DE MADRID,UPM,False,HES,CALLE RAMIRO DE MAEZTU 7 EDIFICIO RECTORADO,28040,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-11-15 16:33:20,1905672,3,participant,904687.50,904687.50,0,False,NaN

In [30]:
orgs_ = orgs_[['projectID','name','shortName','SME','activityType','city','country','organizationURL','contactForm','order','role','ecContribution']]

In [31]:
print (orgs_['country'].unique())

['GH' 'NL' 'UK' 'DK' 'UG' 'KE' 'BE' 'DE' 'MV' 'IT' 'ES' 'AT' 'IE' 'CH'
 'FR' 'SE' 'FI' 'NO' 'LU' 'IL' 'MZ' 'IN' 'XH' 'IS' 'CA' 'GT' 'US' 'AU'
 'KR' 'BJ' 'NG' 'ZA' 'CI' 'CN' 'GL' 'JP' 'MG' 'AW' 'TZ' 'BF' 'TG' 'PH'
 'MC' 'AR' 'CL']

In [32]:
orgs_.to_csv('orgs.csv',index=False,sep='|')