In [70]:
import pandas as pd

In [71]:
topics = pd.read_excel('data/topics.xlsx')
projects = pd.read_excel('data/project.xlsx')
euroscivoc = pd.read_excel('data/euroSciVoc.xlsx')
orgs = pd.read_excel('data/organization.xlsx')

E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
E:\Code\hoponfacilities\venv\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [72]:
projects['startDate']= pd.to_datetime(projects['startDate'],errors = 'coerce')
projects['endDate']= pd.to_datetime(projects['endDate'],errors = 'coerce')
projects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20337 entries, 0 to 20336
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  20337 non-null  int64
 1   acronym             20337 non-null  object
 2   status              20337 non-null  object
 3   title               20337 non-null  object
 4   startDate           20337 non-null  datetime64[ns]
 5   endDate             20337 non-null  datetime64[ns]
 6   totalCost           20337 non-null  object
 7   ecMaxContribution   20337 non-null  object
 8   legalBasis          20337 non-null  object
 9   topics              20337 non-null  object
 10  ecSignatureDate     20336 non-null  object
 11  frameworkProgramme  20337 non-null  object
 12  masterCall          20337 non-null  object
 13  subCall             20337 non-null  object
 14  fundingScheme       20337 non-null  object
 15  objective           20337 non-null  object
 16  contentUpdateDate   20337 non-null  object
 17  rcn                 20337 non-null  int64
 18  grantDoi            20142 non-null  object
 19  keywords            18495 non-null  object
dtypes: datetime64[ns](2), int64(2), object(16)
memory usage: 3.1+ MB

In [73]:
projects

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
0,101131342,6G-ICARUS,SIGNED,6G Intelligent Connectivity And inteRaction fo...,2024-03-01,2028-02-29,0,501400,HORIZON.1.2,HORIZON-MSCA-2022-SE-01-01,2023-10-23,HORIZON,HORIZON-MSCA-2022-SE-01,HORIZON-MSCA-2022-SE-01,HORIZON-TMA-MSCA-SE,"In the context of modern technologies, the tra...",2026-01-23 07:56:15,257832,10.3030/101131342,"future wireless networks, mm-wave, sub-Teraher..."
1,101194172,NeAIxt,SIGNED,Next Generation of edge AI crossing technology...,2025-09-01,2028-08-31,"95628952,84",25010735,HORIZON.2.4,HORIZON-JU-Chips-2024-1-IA-T1,2025-08-04,HORIZON,HORIZON-JU-Chips-2024-1-IA,HORIZON-JU-Chips-2024-1-IA,HORIZON-JU-IA,Europe is poised to play a pivotal role in the...,2026-03-30 11:37:00,274881,10.3030/101194172,"edge AI, eNVM, AI, use cases, demonstrators"
2,101236710,eRISIKO,SIGNED,AI-Driven Dynamic Fire Risk Assessment for Ele...,2026-01-01,2029-12-31,0,450900,HORIZON.1.2,HORIZON-MSCA-2024-SE-01-01,2025-07-31,HORIZON,HORIZON-MSCA-2024-SE-01,HORIZON-MSCA-2024-SE-01,HORIZON-TMA-MSCA-SE,The eRISIKO project enhances international mob...,2026-01-07 15:11:22,274828,10.3030/101236710,"Electric vehicle fires, fire risk assessment, ..."
3,101135437,AI-CODE,SIGNED,AI-CODE - AI services for COntinuous trust in ...,2023-12-01,2026-11-30,0,"4969471,25",HORIZON.2.4,HORIZON-CL4-2023-HUMAN-01-05,2023-10-20,HORIZON,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-CL4-2023-HUMAN-01-CNECT,HORIZON-IA,The media sector is exposed to and undergoing ...,2026-02-03 05:45:15,257887,10.3030/101135437,"disinformation, media professionals, generativ..."
4,101095957,Q-SCALING,SIGNED,Doing Charges Right: Modelling Ion-Controlled ...,2023-10-01,2028-09-30,2499115,2499115,HORIZON.1.1,ERC-2022-ADG,2023-06-08,HORIZON,ERC-2022-ADG,ERC-2022-ADG,HORIZON-ERC,Electrical stimuli are essential for a plethor...,2025-10-20 17:38:03,250736,10.3030/101095957,"molecular dynamics, force field, electronic po..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20332,101052954,SRS,SIGNED,Stationary Random Subgroups,2022-05-01,2028-04-30,2149023,2149023,HORIZON.1.1,ERC-2021-ADG,2022-04-27,HORIZON,ERC-2021-ADG,ERC-2021-ADG,HORIZON-ERC,The notion of invariant random subgroups (IRS)...,2022-07-28 23:54:01,238792,10.3030/101052954,"Discrete Subgroups of Lie Groups, Lattices, Ar..."
20333,101043003,IMPACT,SIGNED,Investigating the Molecular identity of PAcema...,2022-09-01,2027-08-31,1490000,1490000,HORIZON.1.1,ERC-2021-STG,2022-02-04,HORIZON,ERC-2021-STG,ERC-2021-STG,HORIZON-ERC,Spontaneous activity is a prominent feature of...,2025-08-08 16:24:31,238363,10.3030/101043003,"cerebral cortex, neuronal diversity, spontaneo..."
20334,101039524,TIME,SIGNED,It's about time: Towards a dynamic account of ...,2022-07-01,2027-06-30,1499455,1499455,HORIZON.1.1,ERC-2021-STG,2022-03-24,HORIZON,ERC-2021-STG,ERC-2021-STG,HORIZON-ERC,The visual world around us is a source of rich...,2023-04-05 12:11:46,238048,10.3030/101039524,"human vision, visual system, eye-movements, re..."
20335,101041799,NEUROGROUP,SIGNED,Neuronal basis of group cooperation and social...,2022-07-01,2027-06-30,1700000,1700000,HORIZON.1.1,ERC-2021-STG,2022-06-16,HORIZON,ERC-2021-STG,ERC-2021-STG,HORIZON-ERC,The negative impact on society's mental health...,2022-07-25 17:49:14,238255,10.3030/101041799,"Neurophysiology, social cognition, social inte..."
20336,101140394,CADABRE,SIGNED,Computational design of synthetic antibody rep...,2024-08-01,2029-07-31,2741000,2741000,HORIZON.1.1,ERC-2023-ADG,2024-07-09,HORIZON,ERC-2023-ADG,ERC-2023-ADG,HORIZON-ERC,Synthetic human antibody repertoires are an im...,2024-07-16 15:26:41,264732,10.3030/101140394,"Rosetta, atomistic design, antibody developa..."

In [74]:
from datetime import datetime
filterdate = datetime(2025,9,24)
projects_fil = projects[projects['startDate']>=filterdate]
projects_fil = projects_fil[projects_fil['endDate']<=datetime(2033,9,25)]
projects_fil

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
2,101236710,eRISIKO,SIGNED,AI-Driven Dynamic Fire Risk Assessment for Ele...,2026-01-01,2029-12-31,0,450900,HORIZON.1.2,HORIZON-MSCA-2024-SE-01-01,2025-07-31,HORIZON,HORIZON-MSCA-2024-SE-01,HORIZON-MSCA-2024-SE-01,HORIZON-TMA-MSCA-SE,The eRISIKO project enhances international mob...,2026-01-07 15:11:22,274828,10.3030/101236710,"Electric vehicle fires, fire risk assessment, ..."
10,101211309,SDL-MFHYD,SIGNED,Accelerated quantification of photolytic hydro...,2026-09-01,2028-08-31,0,"260347,92",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-02-27,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,The fossil fuel sector is projected to emit 20...,2026-03-17 09:58:45,269099,10.3030/101211309,"Self-driving laboratories, Automation, clean e..."
17,101227453,ELEVATE,SIGNED,"Event-based LEarning, Vision, And conTrol for ...",2026-01-01,2029-12-31,0,"4522697,28",HORIZON.1.2,HORIZON-MSCA-2024-DN-01-01,2025-07-02,HORIZON,HORIZON-MSCA-2024-DN-01,HORIZON-MSCA-2024-DN-01,HORIZON-TMA-MSCA-DN,"Computing with neuromorphic hardware, learning...",2026-03-24 16:20:15,274448,NaN,"neuromorphic engineering, event cameras, neuro..."
19,101226762,CAFE-BIO,SIGNED,A Coherent Analysis Framework for Emergence in...,2026-02-01,2030-01-31,0,"4541464,08",HORIZON.1.2,HORIZON-MSCA-2024-DN-01-01,2025-07-03,HORIZON,HORIZON-MSCA-2024-DN-01,HORIZON-MSCA-2024-DN-01,HORIZON-TMA-MSCA-DN,This network will provide a rigorous training ...,2026-03-30 11:36:47,274527,NaN,Active matter physics; Biological/living matte...
28,101219872,MAD-TENSOR,SIGNED,Machine-learned Atomic Descriptors combined wi...,2026-01-01,2030-12-31,1498705,1498705,HORIZON.1.1,ERC-2025-STG,2025-10-10,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,"""Metallic alloys form the backbone of modern i...",2025-10-20 17:38:03,277765,10.3030/101219872,Atomistic SimulationsMachine-learning Potentia...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20211,101248363,PhotoSERS,SIGNED,Molecularly Imprinted Photoactive Microswimmer...,2025-11-01,2027-04-30,0,150000,HORIZON.1.1,ERC-2025-POC,2025-07-09,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,"Per- and polyfluoroalkyl substances (PFAS), co...",2025-11-26 11:07:33,274571,NaN,NaN
20215,101217014,ECROS,SIGNED,Empowering Early Career Researchers with new O...,2025-10-01,2028-09-30,2000816,2000816,HORIZON.4.2,HORIZON-WIDERA-2024-ERA-02-03,2025-04-16,HORIZON,HORIZON-WIDERA-2024-ERA-02,HORIZON-WIDERA-2024-ERA-02,HORIZON-CSA,"Driven by a powerful consortium, composed of n...",2025-11-26 10:57:28,272559,10.3030/101217014,"research talent ecosystem, early-career resear..."
20217,101198795,NumAStAI,SIGNED,Numerical Analysis for Stable AI,2026-01-01,2030-12-31,0,2498941,HORIZON.1.1,ERC-2024-ADG,2025-07-15,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,From a numerical analysis perspective I will i...,2025-07-23 10:54:27,274629,10.3030/101198795,Mathematical aspects of Artificial Intelligence
20220,101199253,COLUMNET,SIGNED,Efficient odour representations in the olfacto...,2026-10-01,2031-09-30,0,3453563,HORIZON.1.1,ERC-2024-ADG,2025-07-07,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,How is the percept of a smell generated from t...,2025-07-14 10:30:08,274483,NaN,"olfaction, neural network oscillation, olfacto..."
20290,101201020,BRICMEM,SIGNED,Brain-inspired Computational Memory,2026-01-01,2030-12-31,0,2493073,HORIZON.1.1,ERC-2024-ADG,2025-10-31,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,Deep neural networks (DNNs) have transformed t...,2025-11-14 12:36:44,278545,10.3030/101201020,"In-memory computing, brain-inspired computing,..."

In [75]:
projectIDs = projects_fil['id'].tolist()

In [76]:
orgs

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101131342,6G-ICARUS,989739404,NaN,SAN DIEGO STATE UNIVERSITY FOUNDATION,SDSU,False,OTH,CAMPANILE DRIVE 5520 MC 1931,5520,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-23 07:56:15,2567420,13,associatedPartner,NaN,0.0,0,False,NaN
1,101131342,6G-ICARUS,999848841,NaN,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UFRJ,False,HES,RUA ANTONIO BARROS DE CASTRO 119,21941-853,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-23 07:56:15,2002988,19,associatedPartner,NaN,0.0,0,False,NaN
2,101131342,6G-ICARUS,999895692,EL090049627,ARISTOTELIO PANEPISTIMIO THESSALONIKIS,ARISTOTLE UNIVERSITY OF THESSALONIKI,False,HES,"KEDEA BUILDING, TRITIS SEPTEMVRIOU, ARISTOTLE ...",546 36,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-23 07:56:15,1905662,1,coordinator,138000.0,138000.0,0,False,NaN
3,101131342,6G-ICARUS,999984059,DE129515865,FRAUNHOFER GESELLSCHAFT ZUR FORDERUNG DER ANGE...,Fraunhofer,False,REC,HANSASTRASSE 27C,80686,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-23 07:56:15,1905912,22,associatedPartner,NaN,0.0,0,False,NaN
4,101131342,6G-ICARUS,999907526,GB729856187,THE UNIVERSITY OF BIRMINGHAM,UoB,False,HES,Edgbaston,B15 2TT,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-23 07:56:15,1906227,9,associatedPartner,NaN,0.0,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123255,101052954,SRS,999979306,IL520016858,WEIZMANN INSTITUTE OF SCIENCE,WEIZMANN,False,HES,HERZL STREET 234,7610001,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-07-28 23:54:01,1906414,1,coordinator,2149023.0,2149023.0,2149023,False,NaN
123256,101043003,IMPACT,932462747,IT08820790965,UNIVERSITA HUMANITAS,HUMANITAS UNIVERSITY,False,HES,VIA RITA LEVI MONTALCINI 2/4,20072,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-08 16:24:31,2676796,1,coordinator,1490000.0,1490000.0,1490000,False,NaN
123257,101039524,TIME,999855049,DE154285400,UNIVERSITAET OSNABRUECK,UOS,False,HES,NEUER GRABEN/SCHLOSS 29,49074,...,https://ec.europa.eu/info/funding-tenders/oppo...,2023-04-05 12:11:46,2072929,1,coordinator,1499455.0,1499455.0,1499455,False,NaN
123258,101041799,NEUROGROUP,997770131,DE115314015,DEUTSCHES PRIMATENZENTRUM GMBH,DPZ,False,REC,KELLNERWEG 4,37077,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-07-25 17:49:14,2001981,1,coordinator,1700000.0,1700000.0,1700000,False,NaN
123259,101140394,CADABRE,999979306,IL520016858,WEIZMANN INSTITUTE OF SCIENCE,WEIZMANN,False,HES,HERZL STREET 234,7610001,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-16 15:26:41,1906414,1,coordinator,2741000.0,2741000.0,2741000,False,NaN

In [77]:
orgsinproj = orgs[orgs['projectID'].isin(projectIDs)]
orgsinproj

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
89,101236710,eRISIKO,999650282,NaN,UNIVERSITI PUTRA MALAYSIA,UPM,False,HES,UPM SERDANG,43400,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:22,2146163,4,associatedPartner,NaN,0.00,0,False,NaN
90,101236710,eRISIKO,873474816,NaN,Fire and Rescue Academy of Malaysia,Fire and Rescue Academy of Malaysia,NaN,PRC,NaN,NaN,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:22,1993906,5,associatedPartner,NaN,0.00,0,False,NaN
91,101236710,eRISIKO,999641746,ESR3168001J,UNIVERSIDAD DE NAVARRA,UNIVERSITY OF NAVARRA,False,HES,CAMPUS UNIVERSITARIO EDIFICIO CENTRAL,31080,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:22,1912206,1,coordinator,180360.00,180360.00,0,False,NaN
92,101236710,eRISIKO,999980567,GB673598875,THE UNIVERSITY OF LIVERPOOL,NaN,False,HES,BROWNLOW HILL 765 FOUNDATION BUILDING,L69 7ZX,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:22,1907048,2,participant,245490.00,245490.00,0,False,NaN
93,101236710,eRISIKO,999527092,SI43950019,ZAVOD ZA GRADBENISTVO SLOVENIJE,ZAG LJUBLJANA,False,REC,DIMICEVA ULICA 12,1000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:22,1912593,3,participant,25050.00,25050.00,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122885,101217014,ECROS,903964729,IE3574697EH,TECHNOLOGICAL UNIVERSITY DUBLIN,TU Dublin,False,HES,NORTH CIRCULAR ROAD 191 PARK HOUSE GRANGEGORMAN,D07 EWV4,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 10:57:28,1956566,8,participant,194190.00,194190.00,194190,False,NaN
122886,101217014,ECROS,999868532,BG831917834,TECHNICAL UNIVERSITY OF SOFIA,NaN,False,HES,Kliment Ohridsky Bd 8,1000,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 10:57:28,1905732,9,participant,108998.75,108998.75,"108998,75",False,NaN
122900,101198795,NumAStAI,999974941,GB592950700,THE UNIVERSITY OF EDINBURGH,UEDIN,False,HES,"OLD COLLEGE, SOUTH BRIDGE",EH8 9YL,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-23 10:54:27,1905557,1,coordinator,2498941.00,2498941.00,0,False,NaN
122917,101199253,COLUMNET,999868629,DE811335517,UNIVERSITAET REGENSBURG,UREG,False,HES,UNIVERSITATSSTRASSE 31,93053,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 10:30:08,1906484,1,coordinator,3453563.00,3453563.00,0,False,NaN
123163,101201020,BRICMEM,999987648,DE811225433,RUPRECHT-KARLS-UNIVERSITAET HEIDELBERG,UHEI,False,HES,SEMINARSTRASSE 2,69117,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-14 12:36:44,1907466,1,coordinator,2493073.00,2493073.00,0,False,NaN

In [78]:
print (orgsinproj['country'].unique())

['MY' 'ES' 'UK' 'SI' 'CH' 'BE' 'FR' 'SE' 'DE' 'PT' 'NL' 'PL' 'LU' 'IT'
 'AT' 'TN' 'CZ' 'FI' 'IL' 'EG' 'CY' 'RO' 'EL' 'RS' 'CA' 'HU' 'US' 'DK'
 'IE' 'NO' 'MT' 'BG' 'BR' 'TR' 'EE' 'CO' 'GA' 'AU' 'CM' 'AR' 'MX' 'ST'
 'JM' 'CI' 'DO' 'CR' 'CV' 'CU' 'IS' 'GH' 'TH' 'CL' 'KE' 'ZM' 'ZA' 'HR'
 'MD' 'SK' 'SG' 'BA' 'LT' 'UA' 'JP' 'HK' 'LV' 'NZ' 'LB' 'UZ' 'KG' 'KZ'
 'TM' 'TJ' 'IN' 'CN' 'TW' 'TZ' 'KR' 'GE' 'NG' 'AM' 'AL' 'MK' 'EC' 'MA'
 'DZ' 'VN' 'GL' 'ME' 'FJ' 'KM' 'ET' 'ML' 'SN' 'BF' 'CG' 'BJ' nan 'LK' 'TG'
 'GU' 'MP' 'MG' 'DJ' 'PY' 'MU' 'MZ' 'PE' 'BO' 'PH' 'PG' 'NP' 'PK' 'MV'
 'LA' 'CF' 'ID' 'UG' 'JO' 'UY' 'ZW' 'SZ' 'MW' 'SA' 'CD' 'BW' 'AW']

In [79]:
projectsIDS_with_widening = orgsinproj[orgsinproj['country'].isin(['EL','BG','HR','CZ','EE','HU','LV','LT','MT','PL','PT','RO','SK','SI',
                                                                   'AL','BA','AM','FO','GE','XK','MD','ME','MK','RS','TN','TR','UA','MA',
                                                                   'GP','GF','MQ','YT','CY'])]
projectsIDS_with_widening= projectsIDS_with_widening['projectID'].tolist()

In [80]:
projects_no_widening = projects_fil[~projects_fil['id'].isin(projectsIDS_with_widening)]
projects_no_widening

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
10,101211309,SDL-MFHYD,SIGNED,Accelerated quantification of photolytic hydro...,2026-09-01,2028-08-31,0,"260347,92",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-02-27,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,The fossil fuel sector is projected to emit 20...,2026-03-17 09:58:45,269099,10.3030/101211309,"Self-driving laboratories, Automation, clean e..."
28,101219872,MAD-TENSOR,SIGNED,Machine-learned Atomic Descriptors combined wi...,2026-01-01,2030-12-31,1498705,1498705,HORIZON.1.1,ERC-2025-STG,2025-10-10,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,"""Metallic alloys form the backbone of modern i...",2025-10-20 17:38:03,277765,10.3030/101219872,Atomistic SimulationsMachine-learning Potentia...
30,101169607,Counterfact,SIGNED,Counterfactuals in Minds and Machines,2025-11-01,2030-10-31,1997500,1997500,HORIZON.1.1,ERC-2024-COG,2025-02-22,HORIZON,ERC-2024-COG,ERC-2024-COG,HORIZON-ERC,"Reasoning about what might have been, about al...",2025-08-15 14:07:00,268987,10.3030/101169607,"human aspects of machine learning, human-ai co..."
39,101212401,FoundLatt,SIGNED,A Foundation Model for Lattice QCD: Learning t...,2026-09-01,2031-08-31,1491488,1491488,HORIZON.1.1,ERC-2025-STG,2025-10-17,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,"""Despite describing fundamental physics with s...",2025-10-28 03:12:43,278435,10.3030/101212401,"Machine learning, Generative models, Lattice QCD"
52,101231489,AUQuant,SIGNED,Algorithmic Uncertainty Quantification for Lea...,2026-10-01,2031-09-30,1999757,1999757,HORIZON.1.1,ERC-2025-COG,2026-02-23,HORIZON,ERC-2025-COG,ERC-2025-COG,HORIZON-ERC,Assessing the uncertainty of predictions of mo...,2026-03-25 16:31:29,285311,10.3030/101231489,"machine learning theory, uncertainty quantific..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20209,101248681,3P-EL,SIGNED,Innovation in Hydrogen Production Energy Effic...,2025-11-01,2027-04-30,0,150000,HORIZON.1.1,ERC-2025-POC,2025-08-25,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,The 3P-EL project focuses on developing a thre...,2025-11-26 11:09:09,276119,10.3030/101248681,NaN
20211,101248363,PhotoSERS,SIGNED,Molecularly Imprinted Photoactive Microswimmer...,2025-11-01,2027-04-30,0,150000,HORIZON.1.1,ERC-2025-POC,2025-07-09,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,"Per- and polyfluoroalkyl substances (PFAS), co...",2025-11-26 11:07:33,274571,NaN,NaN
20217,101198795,NumAStAI,SIGNED,Numerical Analysis for Stable AI,2026-01-01,2030-12-31,0,2498941,HORIZON.1.1,ERC-2024-ADG,2025-07-15,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,From a numerical analysis perspective I will i...,2025-07-23 10:54:27,274629,10.3030/101198795,Mathematical aspects of Artificial Intelligence
20220,101199253,COLUMNET,SIGNED,Efficient odour representations in the olfacto...,2026-10-01,2031-09-30,0,3453563,HORIZON.1.1,ERC-2024-ADG,2025-07-07,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,How is the percept of a smell generated from t...,2025-07-14 10:30:08,274483,NaN,"olfaction, neural network oscillation, olfacto..."
20290,101201020,BRICMEM,SIGNED,Brain-inspired Computational Memory,2026-01-01,2030-12-31,0,2493073,HORIZON.1.1,ERC-2024-ADG,2025-10-31,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,Deep neural networks (DNNs) have transformed t...,2025-11-14 12:36:44,278545,10.3030/101201020,"In-memory computing, brain-inspired computing,..."

In [81]:
orgs_no_widening = orgs[orgs['projectID'].isin(projects_no_widening['id'].tolist())]
orgs_no_widening

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
157,101211309,SDL-MFHYD,999980567,GB673598875,THE UNIVERSITY OF LIVERPOOL,NaN,False,HES,BROWNLOW HILL 765 FOUNDATION BUILDING,L69 7ZX,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-17 09:58:45,1907048,1,coordinator,260347.92,260347.92,0,False,NaN
319,101219872,MAD-TENSOR,998806867,ATU47691500,MATERIALS CENTER LEOBEN FORSCHUNG GMBH,MCL,True,REC,VORDERNBERGER STRASSE 12,8700,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-10-20 17:38:03,1917562,1,coordinator,1498705.00,1498705.00,1498705,False,NaN
323,101169607,Counterfact,999990267,DE129517720,MAX-PLANCK-GESELLSCHAFT ZUR FORDERUNG DER WISS...,MPG,False,REC,HOFGARTENSTRASSE 8,80539,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-08-15 14:07:00,1949732,1,coordinator,1997500.00,1997500.00,1997500,False,NaN
392,101212401,FoundLatt,999974941,GB592950700,THE UNIVERSITY OF EDINBURGH,UEDIN,False,HES,"OLD COLLEGE, SOUTH BRIDGE",EH8 9YL,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-10-28 03:12:43,1905557,1,coordinator,1491488.00,1491488.00,1491488,False,NaN
542,101231489,AUQuant,999867077,ESQ5850017D,UNIVERSIDAD POMPEU FABRA,UPF,False,HES,"PLACA DE LA MERCE, 10-12",08002,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-25 16:31:29,1905555,1,coordinator,1999757.00,1999757.00,1999757,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122857,101248681,3P-EL,999897729,DE188369991,TECHNISCHE UNIVERSITAET DRESDEN,TUD,False,HES,HELMHOLTZSTRASSE 10,01069,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:09:09,1905682,1,coordinator,150000.00,150000.00,0,False,NaN
122859,101248363,PhotoSERS,999548044,ESG43619550,FUNDACIO INSTITUT CATALA D'INVESTIGACIO QUIMICA,ICIQ-CERCA,False,REC,AVENIDA PAISSOS CATALANS 16,43007,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-26 11:07:33,1922222,1,coordinator,150000.00,150000.00,0,False,NaN
122900,101198795,NumAStAI,999974941,GB592950700,THE UNIVERSITY OF EDINBURGH,UEDIN,False,HES,"OLD COLLEGE, SOUTH BRIDGE",EH8 9YL,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-23 10:54:27,1905557,1,coordinator,2498941.00,2498941.00,0,False,NaN
122917,101199253,COLUMNET,999868629,DE811335517,UNIVERSITAET REGENSBURG,UREG,False,HES,UNIVERSITATSSTRASSE 31,93053,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-07-14 10:30:08,1906484,1,coordinator,3453563.00,3453563.00,0,False,NaN
123163,101201020,BRICMEM,999987648,DE811225433,RUPRECHT-KARLS-UNIVERSITAET HEIDELBERG,UHEI,False,HES,SEMINARSTRASSE 2,69117,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-11-14 12:36:44,1907466,1,coordinator,2493073.00,2493073.00,0,False,NaN

In [82]:
euroscivoc

,projectID,euroSciVocCode,euroSciVocPath,euroSciVocTitle,euroSciVocDescription
0,101131342,/23/47/297/933,/natural sciences/computer and information sci...,machine learning,NaN
1,101194172,/23/47/305/967,/natural sciences/computer and information sci...,internet of things,NaN
2,101194172,/23/47/301,/natural sciences/computer and information sci...,computational science,NaN
3,101194172,/23/47/297/933,/natural sciences/computer and information sci...,machine learning,NaN
4,101236710,/25/75,/engineering and technology/mechanical enginee...,mechanical engineering,NaN
...,...,...,...,...,...
43280,101125807,/23/43/257/759,/natural sciences/physical sciences/astronomy/...,astrophysics,NaN
43281,101125807,/29/101/553/1355,/social sciences/sociology/demography/census,census,NaN
43282,101125807,/23/51/359/1065,/natural sciences/mathematics/pure mathematics...,geometry,NaN
43283,101069176,/21/35/153/629,/medical and health sciences/basic medicine/ne...,epilepsy,NaN
43284,101069176,/21/39/223,/medical and health sciences/clinical medicine...,surgery,NaN

In [83]:
euroscivoc_proj_no_widening = euroscivoc[euroscivoc['projectID'].isin(projects_no_widening['id'].tolist())]

In [84]:
euroscivoc_proj_no_widening['euroSciVocTitle'].unique()

array(['photocatalysis', 'electrolysis', 'robotics', 'machine learning',
       'energy conversion', 'materials engineering', 'particle physics',
       'quantum physics', 'statistics and probability', 'multiphysics',
       'data science', 'geochronology', 'geophysics',
       'simulation software', 'data protection', 'polymer sciences',
       'signal processing', 'smart sensors', 'computational neuroscience',
       'optical sensors', 'fourier analysis', 'optical networks',
       'laser physics', 'control systems', 'surgery', 'aircraft',
       'soft robotics', 'noble gases', 'mathematical logic', 'DNA',
       'ethnoarchaeology', 'physical anthropology', 'rheumatology',
       'immunotherapy', 'quantum computers', 'superconductivity',
       'genomes', 'topology', 'photons', 'development theories',
       'object detection', 'databases', 'pandemics',
       'social inequalities', 'tuberculosis', 'catalysis', 'enzymes',
       'neurobiology', 'postnatal care', 'obesity', 'fibers',
       'internet of things', 'solar thermal', 'history', 'essays',
       'anthropology', 'ideologies', 'computational science',
       'prostate cancer', 'volcanology', 'pharmaceutical drugs',
       'agriculture', 'metalloids', 'particle accelerator',
       'neutron stars', 'law', 'philosophy', 'cell signaling', 'oncology',
       'personalized medicine', 'manufacturing engineering',
       'computational intelligence', 'employment', 'energy and fuels',
       'epistemology', 'linguistics', 'psychology', 'ethical principles',
       'arts', 'globalization', 'cinematography', 'semiconductivity',
       'data processing', 'ophthalmology', 'implants', 'revolutions',
       'monetary and finances', 'mathematical model',
       'cardiovascular diseases', 'schizophrenia', 'architectural design',
       'animal feed', 'immunology', 'cryptography', 'grains and oilseeds',
       'coating and films', 'stroke', 'planets', 'ecosystems',
       'artificial intelligence', 'mental processes',
       'cognitive neuroscience', 'prehistory', 'fertility',
       'microbiology', 'seismology', 'graph theory', 'spectroscopy',
       'supernova', 'primatology', 'comparative morphology', 'cetology',
       'genetics', 'invertebrate zoology', 'pathophysiology',
       'transplantation', 'gene therapy', 'physiology', 'nano-materials',
       'organ on a chip', 'proteins', 'biochemistry', 'microscopy',
       'super resolution microscopy', 'diabetes', 'homeostasis',
       'cells technologies', 'kidney diseases', 'cardiac arrhythmia',
       'ultrasound', 'anatomy and morphology', 'ecology', 'nutrition',
       'biophysics', 'cell biology', 'mutation', 'chromosomes',
       'evolutionary biology', 'zoology', 'palaeontology', 'mycology',
       'democracy', 'elections', 'social issues', 'sociology',
       'political philosophy', 'demography', 'civil society', 'HIV',
       'governance', 'bureaucracy', 'racial inequality',
       'nongovernmental organizations', 'radar',
       'science and technology studies', 'molecular neuroscience',
       'astronomy', 'sensors', 'two-dimensional nanostructures',
       'digital electronics', 'nanoelectronics', 'computer processors',
       'analogue electronics', 'renewable energy', 'microelectronics',
       'knowledge engineering', 'satellite technology', 'biosensors',
       'biosensing', 'optoelectronics', 'telecommunications', 'mortality',
       'photovoltaic', 'economics', 'desalination', 'distillation',
       'lipids', 'software', 'nanotechnology', 'thermodynamics',
       'quantum optics', 'geometry', 'quantum gases', 'alzheimer',
       'thermodynamic engineering', 'metallurgy', 'developmental biology',
       'embryology', 'epigenetics', 'black holes', 'physical cosmology',
       'productivity', 'tribology', 'quasiparticles',
       'atmospheric sciences', 'thermochemistry',
       'molecular and chemical physics', 'molecular genetics', 'botany',
       'eukaryotic genomes', 'transcriptomes', 'pathology',
       'alkali metals', 'recycling', 'electromagnetism', 'spacecraft',
       'plasma physics', 'radio frequency', 'microfluidics',
       'astrophysics', 'asteroids', 'arteriosclerosis', 'RNA',
       'alkaline earth metals', 'quarks', 'heredity',
       'history of literature', 'mathematics', 'general language studies',
       'entomology', 'colors', 'health sciences', 'literary genres',
       'inorganic compounds', 'biogeochemistry', 'human migrations',
       'archaeology', 'drones', 'seismic loading', 'didactics', 'algebra',
       'biomolecules', 'nanocrystals', 'carbohydrates', 'obstetrics',
       'animal husbandry', 'archaeometry', 'bioarchaeology',
       'christianity', 'ethnology', 'physiotherapy', 'cereals',
       'spintronics', 'entrepreneurship', 'human trafficking',
       'amorphous semiconductors', 'bioremediation', 'vaccines',
       'ancient history', 'political violence', 'political communication',
       'media and communications', 'armed conflicts', 'psycholinguistics',
       'proteomics', 'virology', 'virtual reality', 'nursing', 'forestry',
       'sedimentology', 'mammalogy', 'fodder', 'ketones',
       'pharmacokinetics', 'library sciences', 'terrorism',
       'geochemistry', 'biomaterials', 'census', 'dementia', 'teleology',
       'public policies', 'taxation', 'mineralogy', 'soft matter physics',
       'bacteriology', 'biological interactions', 'pollution',
       'pneumology', 'antibiotics', 'automation', 'marine biology',
       'crystallography', 'solar physics', 'planetary geology',
       'religions', 'family studies', 'islam', 'dairy', 'photochemistry',
       'pharmacology and pharmacy', 'radiation chemistry', 'graphene',
       'fermions', 'composites', 'theoretical physics', 'allergology',
       'amorphous solids', 'atomic physics', 'textiles',
       'wastewater treatment processes', 'melanoma', 'amines',
       'geotechnics', 'reinforcement learning', 'bioreactors',
       'phonetics', 'phonology', 'vegetable growing',
       'climatic change mitigation', 'partial differential equations',
       'electric vehicles', 'wind energy', 'ethnolichenology',
       'psychiatry', 'cultural anthropology', 'popular music studies',
       'ethnomusicology', 'artificial bone', 'electrochemistry',
       'hematology', 'leukemia', 'visual arts', 'natural satellites',
       'geographic information systems', 'journalism', 'acoustics',
       'geology', 'quantum chemistry', 'biofuels',
       'inflammatory diseases', 'transition metals', 'internet',
       'organic amorphous solids', 'nanophotonics',
       'organometallic chemistry', 'organic reactions', 'hepatology',
       'toxicology', 'electrocatalysis', 'hydrogen energy', 'fisheries',
       'giant planets', 'meteorites', 'exoplanetology', 'stem cells',
       'electron microscopy', 'supercomputers', 'parkinson',
       'fruit growing', 'lung cancer', 'glaciology',
       'climate change adaptation', 'optics', 'electrodialysis',
       'criminology', 'meteorology', 'cardiology', 'nanocomposites',
       'social psychology', 'ergonomics', 'medical engineering',
       'computational fluid dynamics', 'control engineering',
       'bioeconomy', 'behavioural psychology', 'multidrug resistance',
       'antibiotic resistance', 'mobile phones', 'fermentation',
       'biomass energy', 'separation technologies',
       'carbon capture engineering', 'bioprocessing technologies',
       'chemical process engineering', 'computer security',
       'medical biotechnology', 'climatic changes', 'influenza',
       'antivirals', 'sustainable building', 'synthetic biology',
       'plant breeding', 'breast cancer', 'immunisation', 'lab on a chip',
       'additive manufacturing', 'colorectal cancer',
       'gamma-ray astronomy', 'alcohols', 'sustainable economy',
       'dermatology', 'structural biology', 'cavity optomechanics',
       'polyurethane', 'biocatalysis', 'numerical analysis',
       'remote sensing', 'transport planning', 'public transport',
       'intelligent transport systems', 'transportation engineering',
       'gluons', 'combinatorics', 'subtractive manufacturing',
       'paleoecology', 'development economics', 'calorimetry',
       'post-colonial theories', 'penology', 'fluid dynamics',
       'gender inequality', 'endocrinology', 'musicology',
       'geothermal energy', 'vascular diseases', 'heat engineering',
       'social developments', 'coronaviruses', 'medieval history',
       'social biomedical sciences', 'speech-language pathology',
       'malaria', 'laboratory samples analysis', 'physical chemistry',
       'mathematical analysis', 'epigenomes', 'hydrology',
       'software applications', 'combined heat and power',
       'macroeconomics', 'dark matter', 'data exchange', 'public health',
       'transport', 'neutrinos', 'biosphera', 'hydrocarbons',
       'international law', 'electrical engineering',
       'business and management', 'mathematical physics',
       'food packaging', 'diagnostic technologies', 'nanomedicine',
       'unemployment', 'analytical chemistry', 'critical care medicine',
       'horticulture', 'biomass', 'neurology', 'astrochemistry',
       'exposomes', 'contemporary philosophy', 'epidemiology',
       'post-transition metals', 'modern and contemporary art',
       'ornithology', 'functional morphology', 'heuristic programming',
       'condensed matter physics', 'electromagnetism and electronics',
       'coal', 'food technology', 'social anthropology',
       'agricultural biotechnology', 'leptons',
       'structural health monitoring', 'literature studies',
       'modern history', 'women’s studies',
       'cultural and economic geography', 'digital humanities',
       'deep learning', 'nonlinear optics', 'oceanography',
       'aliphatic compounds', 'parasitology', 'epilepsy', 'glaucoma',
       'ceramics', 'polylactic acid', 'applied mathematics',
       'economic impact of epidemics', 'synthetic dyes', 'rotorcraft',
       'arboriculture', 'ecological restoration', 'liver cancer',
       'climatology', 'fuel cells', 'autonomous vehicles',
       'glacial geology', 'developmental psychology', 'metaphysics',
       'behavioural ecology', 'molecular biology',
       'computer and information sciences', 'clinical medicine',
       'gender equality', 'multiple sclerosis',
       'magnetic resonance imaging', 'radiochemistry', 'asthma',
       'metabolomes', 'histology', 'educational sciences',
       'languages and literature', 'phycology',
       'duchenne muscular dystrophy', 'medical genetics',
       'piezoelectrics', 'nano-processes',
       'bulk nanostructured materials', 'dramaturgy', 'computer hardware',
       'edge artificial intelligence', 'super-Earths', 'pedagogy',
       'mechanical engineering', 'sexual health', 'foreign policy',
       'corruption', 'political economy', 'plate tectonics',
       'domestic animals', 'flood risk management', 'bladder cancer',
       'cognitive psychology', 'electric power transmission',
       'reproductive medicine', 'synthetic fuels', 'big data',
       'data mining', 'diagnostic imaging', 'nucleotides',
       'aeronautical engineering', 'ebola', 'habitat conservation',
       'air pollution engineering', 'telecommunications networks',
       'quantum field theory', 'physical oceanography', 'cartography',
       'psychoanalysis', 'ontology', 'nuclear engineering',
       'wearable medical technology ', 'irrigation', 'microtechnology',
       'physical geography', 'earth and related environmental sciences',
       'z bosons', 'higgs bosons', 'waste treatment processes',
       'microeconomics', 'molecular evolution', 'tissue engineering',
       'solar astronomy', 'stellar astronomy', 'art history',
       'ethical theories', 'environmental governance', 'econometrics',
       'motion analysis', 'modern philosophy', 'judaism',
       'eastern religions', 'environmental law', 'urban studies',
       'applied mechanics', 'zoonosis', 'paediatrics',
       'isotope geochemistry', 'algebraic geometry',
       'generative artificial intelligence', 'biodiversity conservation',
       'solar energy', 'speleology', 'agroecology', 'paleoclimatology',
       'human rights violations', 'nuclear medicine', 'microbiomes',
       'biocomposites', 'halogens', 'remanufacturing', 'video games',
       'logarithmic functions', 'human rights',
       'global navigation satellite system', 'development studies',
       'galaxy evolution', 'innovation management', 'system software',
       'chemical sciences', 'hydrometeorology', 'WiFi', 'public services',
       'data networks', 'sustainable agriculture', 'ethics',
       'social geography', 'aldehydes', 'petroleum',
       'medieval philosophy', 'supervised learning', 'mobile network',
       'optical astronomy', 'galactic astronomy', 'family planning',
       'software development', 'other social sciences', 'business models',
       'radiology', 'dynamical systems', 'inflammatory bowel disease',
       'gastroenterology', 'crisis management', 'pandemic risks',
       'arithmetics', 'radio technology', 'contemporary history',
       'age inequality'], dtype=object)

In [85]:
scivocpathlist = euroscivoc_proj_no_widening['euroSciVocPath'].tolist()

In [86]:
paths = ",".join(scivocpathlist)
print (paths)

/natural sciences/chemical sciences/catalysis/photocatalysis,/natural sciences/chemical sciences/electrochemistry/electrolysis,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/engineering and technology/environmental engineering/energy and fuels/energy conversion,/engineering and technology/materials engineering,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/physical sciences/theoretical physics/particle physics,/natural sciences/physical sciences/quantum physics,/natural sciences/mathematics/applied mathematics/statistics and probability,/natural sciences/computer and information sciences/computational science/multiphysics,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/data science,/natural sciences/earth and related environmental sciences/geology/geochronology,/natural sciences/earth and related environmental sciences/geophysics,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/software/software applications/simulation software,/natural sciences/computer and information sciences/computer security/data protection,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/natural sciences/chemical sciences/polymer sciences,/natural sciences/computer and information sciences/computational science/multiphysics,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/signal processing,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/smart sensors,/natural sciences/biological sciences/neurobiology/computational neuroscience,/natural sciences/computer and information sciences/artificial intelligence/machine learning,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/sensors/optical sensors,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/signal processing,/natural sciences/mathematics/pure mathematics/mathematical analysis/fourier analysis,/engineering and technology/electrical engineering, electronic engineering, information engineering/information engineering/telecommunications/telecommunications networks/optical networks,/natural sciences/physical sciences/optics/laser physics,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/control systems,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/control systems,/medical and health sciences/clinical medicine/surgery,/engineering and technology/mechanical engineering/vehicle engineering/aerospace engineering/aircraft,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/robotics/soft robotics,/natural sciences/chemical sciences/inorganic chemistry/noble gases,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/control systems,/natural sciences/mathematics/pure mathematics/discrete mathematics/mathematical logic,/natural sciences/earth and related environmental sciences/geology/geochronology,/natural sciences/biological sciences/genetics/DNA,/humanities/history and archaeology/archaeology/ethnoarchaeology,/social sciences/sociology/anthropology/physical anthropology,/medical and health sciences/clinical medicine/rheumatology,/medical and health sciences/basic medicine/immunology/immunotherapy,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/quantum computers,/natural sciences/physical sciences/electromagnetism and electronics/superconductivity,/natural sciences/biological sciences/genetics/genomes,/natural sciences/physical sciences/quantum physics,/natural sciences/mathematics/pure mathematics/topology,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/quantum computers,/natural sciences/physical sciences/theoretical physics/particle physics/photons,/social sciences/other social sciences/development studies/development theories,/natural sciences/computer and information sciences/artificial intelligence/computer vision/object detection,/natural sciences/computer and information sciences/databases,/medical and health sciences/health sciences/public health/epidemiology/pandemics,/social sciences/sociology/social issues/social inequalities,/medical and health sciences/clinical medicine/pneumology/tuberculosis,/natural sciences/chemical sciences/catalysis,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/biological sciences/neurobiology,/medical and health sciences/clinical medicine/obstetrics/postnatal care,/medical and health sciences/health sciences/nutrition/obesity,/engineering and technology/materials engineering/fibers,/natural sciences/computer and information sciences/internet/internet of things,/engineering and technology/environmental engineering/energy and fuels/renewable energy/solar energy/solar thermal,/humanities/history and archaeology/history,/humanities/languages and literature/literature studies/literary genres/essays,/social sciences/sociology/anthropology,/social sciences/sociology/ideologies,/natural sciences/computer and information sciences/computational science,/natural sciences/computer and information sciences/databases,/natural sciences/chemical sciences/catalysis,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/natural sciences/biological sciences/neurobiology,/medical and health sciences/clinical medicine/oncology/prostate cancer,/natural sciences/computer and information sciences/databases,/natural sciences/earth and related environmental sciences/geology/volcanology,/medical and health sciences/basic medicine/pharmacology and pharmacy/pharmaceutical drugs,/agricultural sciences/agriculture, forestry, and fisheries/agriculture,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/natural sciences/physical sciences/theoretical physics/particle physics/particle accelerator,/natural sciences/physical sciences/astronomy/stellar astronomy/neutron stars,/humanities/history and archaeology/history,/social sciences/law,/humanities/philosophy, ethics and religion/philosophy,/natural sciences/biological sciences/cell biology/cell signaling,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/health sciences/personalized medicine,/medical and health sciences/basic medicine/immunology/immunotherapy,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/engineering and technology/mechanical engineering/manufacturing engineering,/natural sciences/computer and information sciences/artificial intelligence/computational intelligence,/social sciences/economics and business/business and management/employment,/engineering and technology/environmental engineering/energy and fuels,/humanities/philosophy, ethics and religion/philosophy/epistemology,/humanities/languages and literature/linguistics,/humanities/history and archaeology/history,/social sciences/psychology,/humanities/languages and literature/linguistics,/humanities/philosophy, ethics and religion/ethics/ethical principles,/humanities/arts,/social sciences/sociology/anthropology,/social sciences/other social sciences/development studies/development theories/global development studies/globalization,/social sciences/law,/humanities/arts/modern and contemporary art/cinematography,/natural sciences/physical sciences/electromagnetism and electronics/semiconductivity,/natural sciences/computer and information sciences/data science/data processing,/medical and health sciences/clinical medicine/ophthalmology,/medical and health sciences/medical biotechnology/implants,/social sciences/political sciences/political transitions/revolutions,/engineering and technology/electrical engineering, electronic engineering, information engineering/electronic engineering/computer hardware/quantum computers,/natural sciences/physical sciences/electromagnetism and electronics/semiconductivity,/natural sciences/chemical sciences/inorganic chemistry/metalloids,/natural sciences/physical sciences/electromagnetism and electronics/superconductivity,/humanities/history and archaeology/history,/social sciences/economics and business/economics/monetary and finances,/social sciences/other social sciences/development studies/development theories/global development studies/globalization,/natural sciences/mathematics/applied mathematics/mathematical model,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases,/medical and health sciences/clinical medicine/psychiatry/schizophrenia,/humanities/arts/architectural design,/humanities/history and archaeology/history,/agricultural sciences/animal and dairy science/domestic animals/animal husbandry/animal feed,/social sciences/psychology,/medical and health sciences/basic medicine/immunology,/natural sciences/computer and information sciences/computer security/cryptography,/agricultural sciences/agriculture, forestry, and fisheries/agriculture/grains and oilseeds,/engineering and technology/materials engineering/coating and films,/medical and health sciences/basic medicine/neurology/stroke,/natural sciences/physical sciences/astronomy/planetary sciences/planets,/natural sciences/biological sciences/ecology/ecosystems,/natural sciences/chemical sciences/electrochemistry/electrolysis,/natural sciences/computer and information sciences/artificial intelligence,/social sciences/psychology/cognitive psychology/mental processes,/natural sciences/biological sciences/neurobiology/cognitive neuroscience,/natural sciences/biological sciences/neurobiology/computational neuroscience,/humanities/history and archaeology/history/prehistory,/natural sciences/biological sciences/genetics/DNA,/natural sciences/physical sciences/astronomy/planetary sciences/planets,/natural sciences/biological sciences/ecology/ecosystems,/humanities/history and archaeology/history,/social sciences/sociology/demography/fertility,/natural sciences/biological sciences/genetics/genomes,/natural sciences/biological sciences/microbiology,/medical and health sciences/clinical medicine/oncology,/natural sciences/computer and information sciences/computer security/cryptography,/natural sciences/earth and related environmental sciences/geology/seismology,/natural sciences/mathematics/pure mathematics/discrete mathematics/graph theory,/natural sciences/mathematics/applied mathematics/statistics and probability,/natural sciences/chemical sciences/catalysis,/natural sciences/physical sciences/optics/spectroscopy,/natural sciences/mathematics/pure mathematics/discrete mathematics/mathematical logic,/natural sciences/physical sciences/astronomy/stellar astronomy/supernova,/natural sciences/biological sciences/zoology/mammalogy/primatology,/natural sciences/biological sciences/biological morphology/comparative morphology,/natural sciences/biological sciences/zoology/mammalogy/cetology,/natural sciences/biological sciences/genetics,/natural sciences/biological sciences/biological morphology/comparative morphology,/natural sciences/biological sciences/zoology/invertebrate zoology,/natural sciences/biological sciences/neurobiology,/medical and health sciences/basic medicine/physiology/pathophysiology,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/medical biotechnology/genetic engineering/gene therapy,/medical and health sciences/basic medicine/physiology,/engineering and technology/nanotechnology/nano-materials,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/basic medicine/physiology,/medical and health sciences/clinical medicine/transplantation,/engineering and technology/other engineering and technologies/microtechnology/organ on a chip,/natural sciences/biological sciences/biochemistry/biomolecules/proteins,/medical and health sciences/clinical medicine/transplantation,/natural sciences/biological sciences/biochemistry,/engineering and technology/materials engineering/fibers,/natural sciences/physical sciences/optics/microscopy,/medical and health sciences/basic medicine/physiology,/medical and health sciences/clinical medicine/transplantation,/natural sciences/physical sciences/optics/microscopy/super resolution microscopy,/medical and health sciences/clinical medicine/endocrinology/diabetes,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/basic medicine/physiology/homeostasis,/natural sciences/biological sciences/biochemistry/biomolecules/proteins/enzymes,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/medical biotechnology/cells technologies,/medical and health sciences/clinical medicine/nephrology/kidney diseases,/engineering and technology/materials engineering/fibers,/medical and health sciences/clinical medicine/cardiology/cardiovascular diseases/cardiac arrhythmia,/medical and health sciences/basic medicine/neurology/stroke,/medical and health sciences/clinical medicine/transplantation,/natural sciences/physical sciences/acoustics/ultrasound,/natural sciences/physical sciences/optics/microscopy,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/clinical medicine/oncology,/medical and health sciences/clinical medicine/transplantation,/medical and health sciences/clinical medicine/transplantation,/natural sciences/biological sciences/biological morphology/comparative morphology,/medical and health sciences/basic medicine/anatomy and morphology,/natural sciences/biological sciences/ecology,/medical and health sciences/health sciences/nutrition,/natural sciences/biological sciences/biophysics,/natural sciences/computer and information sciences/software/software applications/simulation software,/medical and health sciences/clinical medicine/transplantation,/natural sciences/biological sciences/microbiology,/medical and health sciences/health sciences/nutrition/obesity,/natural sciences/biological sciences/neurobiology,/natural sciences/biological sciences/cell biology,/medical and health sciences/clinical medicine/transplantation,/natural sciences/biological sciences/biological morphology/comparative morphology,/humanities/history and archaeology/history,/natural sciences/biological sciences/genetics/DNA,/natural sciences/biological sciences/genetics/mutation,/natural sciences/biological sciences/genetics/chromosomes,/natural sciences/biological sciences/biological morphology/comparative morphology,/natural sciences/biological sciences/evolutionary biology,/natural sciences/biological sciences/genetics/genomes,/natural sciences/biological sciences/zoology/invertebrate zoology,/natural sciences/biological sciences/biological morphology/comparative morphology,/natural sciences/biological sciences/ecology/ecosystems,/natural sciences/biological sciences/biological morphology/comparative morphology,/natural sciences/biological sciences/zoology,/natural sciences/mathematics/pure mathematics/topology,/natural sciences/earth and related environmental sciences/palaeontology,/natural sciences/biological sciences/genetics/genomes,/natural sciences/biological sciences/biological morphology/comparative morphology,/humanities/history and archaeology/history,/natural sciences/biological sciences/biological morphology/comparative morphology,/humanities/history and archaeology/history,/natural sciences/biological sciences/microbiology/mycology,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/humanities/arts,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/political transitions/elections,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/social sciences/sociology/ideologies,/social sciences/political sciences/government systems/democracy,/social sciences/sociology/social issues,/social sciences/political sciences/political transitions/elections,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/political transitions/elections,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/social sciences/law,/humanities/history and archaeology/history,/social sciences/political sciences/political transitions/elections,/social sciences/political sciences/government systems/democracy,/social sciences/sociology,/social sciences/political sciences/government systems/democracy,/humanities/philosophy, ethics and religion/philosophy/political philosophy,/social sciences/political sciences/government systems/democracy,/natural sciences/chemical sciences/catalysis,/humanities/philosophy, ethics and religion/philosophy,/social sciences/political sciences/government systems/democracy,/social sciences/law,/social sciences/sociology/demography,/social sciences/political sciences/political transitions/elections,/social sciences/political sciences/government systems/democracy,/social sciences/psychology,/humanities/languages and literature/literature studies/literary genres/essays,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/political policies/civil society,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/medical and health sciences/health sciences/infectious diseases/RNA viruses/HIV,/social sciences/psychology,/social sciences/political sciences/government systems/democracy,/social sciences/sociology/governance,/social sciences/political sciences/public administration/bureaucracy,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/social sciences/law,/social sciences/sociology/governance,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/government systems/democracy,/humanities/history and archaeology/history,/social sciences/sociology/social issues/social inequalities/racial inequality,/social sciences/political sciences/government systems/democracy,/social sciences/political sciences/political policies/civil society/civil society organisations/nongovernmental organizations,/social sciences/political sciences/government systems/democracy,/engineering and technology/electrical engineer

In [87]:
paths = paths.replace('/',',')
paths = paths.replace(',,',',')

In [88]:
paths

',natural sciences,chemical sciences,catalysis,photocatalysis,natural sciences,chemical sciences,electrochemistry,electrolysis,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,natural sciences,computer and information sciences,artificial intelligence,machine learning,engineering and technology,environmental engineering,energy and fuels,energy conversion,engineering and technology,materials engineering,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,physical sciences,theoretical physics,particle physics,natural sciences,physical sciences,quantum physics,natural sciences,mathematics,applied mathematics,statistics and probability,natural sciences,computer and information sciences,computational science,multiphysics,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,data science,natural sciences,earth and related environmental sciences,geology,geochronology,natural sciences,earth and related environmental sciences,geophysics,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,software,software applications,simulation software,natural sciences,computer and information sciences,computer security,data protection,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,computer and information sciences,artificial intelligence,machine learning,natural sciences,chemical sciences,polymer sciences,natural sciences,computer and information sciences,computational science,multiphysics,natural sciences,computer and information sciences,artificial intelligence,machine learning,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,signal processing,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,smart sensors,natural sciences,biological sciences,neurobiology,computational neuroscience,natural sciences,computer and information sciences,artificial intelligence,machine learning,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,sensors,optical sensors,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,signal processing,natural sciences,mathematics,pure mathematics,mathematical analysis,fourier analysis,engineering and technology,electrical engineering, electronic engineering, information engineering,information engineering,telecommunications,telecommunications networks,optical networks,natural sciences,physical sciences,optics,laser physics,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,control systems,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,control systems,medical and health sciences,clinical medicine,surgery,engineering and technology,mechanical engineering,vehicle engineering,aerospace engineering,aircraft,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,robotics,soft robotics,natural sciences,chemical sciences,inorganic chemistry,noble gases,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,control systems,natural sciences,mathematics,pure mathematics,discrete mathematics,mathematical logic,natural sciences,earth and related environmental sciences,geology,geochronology,natural sciences,biological sciences,genetics,DNA,humanities,history and archaeology,archaeology,ethnoarchaeology,social sciences,sociology,anthropology,physical anthropology,medical and health sciences,clinical medicine,rheumatology,medical and health sciences,basic medicine,immunology,immunotherapy,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,quantum computers,natural sciences,physical sciences,electromagnetism and electronics,superconductivity,natural sciences,biological sciences,genetics,genomes,natural sciences,physical sciences,quantum physics,natural sciences,mathematics,pure mathematics,topology,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,quantum computers,natural sciences,physical sciences,theoretical physics,particle physics,photons,social sciences,other social sciences,development studies,development theories,natural sciences,computer and information sciences,artificial intelligence,computer vision,object detection,natural sciences,computer and information sciences,databases,medical and health sciences,health sciences,public health,epidemiology,pandemics,social sciences,sociology,social issues,social inequalities,medical and health sciences,clinical medicine,pneumology,tuberculosis,natural sciences,chemical sciences,catalysis,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,biological sciences,neurobiology,medical and health sciences,clinical medicine,obstetrics,postnatal care,medical and health sciences,health sciences,nutrition,obesity,engineering and technology,materials engineering,fibers,natural sciences,computer and information sciences,internet,internet of things,engineering and technology,environmental engineering,energy and fuels,renewable energy,solar energy,solar thermal,humanities,history and archaeology,history,humanities,languages and literature,literature studies,literary genres,essays,social sciences,sociology,anthropology,social sciences,sociology,ideologies,natural sciences,computer and information sciences,computational science,natural sciences,computer and information sciences,databases,natural sciences,chemical sciences,catalysis,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,natural sciences,biological sciences,neurobiology,medical and health sciences,clinical medicine,oncology,prostate cancer,natural sciences,computer and information sciences,databases,natural sciences,earth and related environmental sciences,geology,volcanology,medical and health sciences,basic medicine,pharmacology and pharmacy,pharmaceutical drugs,agricultural sciences,agriculture, forestry, and fisheries,agriculture,natural sciences,chemical sciences,inorganic chemistry,metalloids,natural sciences,physical sciences,theoretical physics,particle physics,particle accelerator,natural sciences,physical sciences,astronomy,stellar astronomy,neutron stars,humanities,history and archaeology,history,social sciences,law,humanities,philosophy, ethics and religion,philosophy,natural sciences,biological sciences,cell biology,cell signaling,medical and health sciences,clinical medicine,oncology,medical and health sciences,health sciences,personalized medicine,medical and health sciences,basic medicine,immunology,immunotherapy,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,engineering and technology,mechanical engineering,manufacturing engineering,natural sciences,computer and information sciences,artificial intelligence,computational intelligence,social sciences,economics and business,business and management,employment,engineering and technology,environmental engineering,energy and fuels,humanities,philosophy, ethics and religion,philosophy,epistemology,humanities,languages and literature,linguistics,humanities,history and archaeology,history,social sciences,psychology,humanities,languages and literature,linguistics,humanities,philosophy, ethics and religion,ethics,ethical principles,humanities,arts,social sciences,sociology,anthropology,social sciences,other social sciences,development studies,development theories,global development studies,globalization,social sciences,law,humanities,arts,modern and contemporary art,cinematography,natural sciences,physical sciences,electromagnetism and electronics,semiconductivity,natural sciences,computer and information sciences,data science,data processing,medical and health sciences,clinical medicine,ophthalmology,medical and health sciences,medical biotechnology,implants,social sciences,political sciences,political transitions,revolutions,engineering and technology,electrical engineering, electronic engineering, information engineering,electronic engineering,computer hardware,quantum computers,natural sciences,physical sciences,electromagnetism and electronics,semiconductivity,natural sciences,chemical sciences,inorganic chemistry,metalloids,natural sciences,physical sciences,electromagnetism and electronics,superconductivity,humanities,history and archaeology,history,social sciences,economics and business,economics,monetary and finances,social sciences,other social sciences,development studies,development theories,global development studies,globalization,natural sciences,mathematics,applied mathematics,mathematical model,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,medical and health sciences,clinical medicine,psychiatry,schizophrenia,humanities,arts,architectural design,humanities,history and archaeology,history,agricultural sciences,animal and dairy science,domestic animals,animal husbandry,animal feed,social sciences,psychology,medical and health sciences,basic medicine,immunology,natural sciences,computer and information sciences,computer security,cryptography,agricultural sciences,agriculture, forestry, and fisheries,agriculture,grains and oilseeds,engineering and technology,materials engineering,coating and films,medical and health sciences,basic medicine,neurology,stroke,natural sciences,physical sciences,astronomy,planetary sciences,planets,natural sciences,biological sciences,ecology,ecosystems,natural sciences,chemical sciences,electrochemistry,electrolysis,natural sciences,computer and information sciences,artificial intelligence,social sciences,psychology,cognitive psychology,mental processes,natural sciences,biological sciences,neurobiology,cognitive neuroscience,natural sciences,biological sciences,neurobiology,computational neuroscience,humanities,history and archaeology,history,prehistory,natural sciences,biological sciences,genetics,DNA,natural sciences,physical sciences,astronomy,planetary sciences,planets,natural sciences,biological sciences,ecology,ecosystems,humanities,history and archaeology,history,social sciences,sociology,demography,fertility,natural sciences,biological sciences,genetics,genomes,natural sciences,biological sciences,microbiology,medical and health sciences,clinical medicine,oncology,natural sciences,computer and information sciences,computer security,cryptography,natural sciences,earth and related environmental sciences,geology,seismology,natural sciences,mathematics,pure mathematics,discrete mathematics,graph theory,natural sciences,mathematics,applied mathematics,statistics and probability,natural sciences,chemical sciences,catalysis,natural sciences,physical sciences,optics,spectroscopy,natural sciences,mathematics,pure mathematics,discrete mathematics,mathematical logic,natural sciences,physical sciences,astronomy,stellar astronomy,supernova,natural sciences,biological sciences,zoology,mammalogy,primatology,natural sciences,biological sciences,biological morphology,comparative morphology,natural sciences,biological sciences,zoology,mammalogy,cetology,natural sciences,biological sciences,genetics,natural sciences,biological sciences,biological morphology,comparative morphology,natural sciences,biological sciences,zoology,invertebrate zoology,natural sciences,biological sciences,neurobiology,medical and health sciences,basic medicine,physiology,pathophysiology,medical and health sciences,clinical medicine,transplantation,medical and health sciences,medical biotechnology,genetic engineering,gene therapy,medical and health sciences,basic medicine,physiology,engineering and technology,nanotechnology,nano-materials,medical and health sciences,clinical medicine,transplantation,medical and health sciences,basic medicine,physiology,medical and health sciences,clinical medicine,transplantation,engineering and technology,other engineering and technologies,microtechnology,organ on a chip,natural sciences,biological sciences,biochemistry,biomolecules,proteins,medical and health sciences,clinical medicine,transplantation,natural sciences,biological sciences,biochemistry,engineering and technology,materials engineering,fibers,natural sciences,physical sciences,optics,microscopy,medical and health sciences,basic medicine,physiology,medical and health sciences,clinical medicine,transplantation,natural sciences,physical sciences,optics,microscopy,super resolution microscopy,medical and health sciences,clinical medicine,endocrinology,diabetes,medical and health sciences,clinical medicine,transplantation,medical and health sciences,basic medicine,physiology,homeostasis,natural sciences,biological sciences,biochemistry,biomolecules,proteins,enzymes,medical and health sciences,clinical medicine,transplantation,medical and health sciences,medical biotechnology,cells technologies,medical and health sciences,clinical medicine,nephrology,kidney diseases,engineering and technology,materials engineering,fibers,medical and health sciences,clinical medicine,cardiology,cardiovascular diseases,cardiac arrhythmia,medical and health sciences,basic medicine,neurology,stroke,medical and health sciences,clinical medicine,transplantation,natural sciences,physical sciences,acoustics,ultrasound,natural sciences,physical sciences,optics,microscopy,medical and health sciences,clinical medicine,transplantation,medical and health sciences,clinical medicine,oncology,medical and health sciences,clinical medicine,transplantation,medical and health sciences,clinical medicine,transplantation,natural sciences,biological sciences,biological morphology,comparative morphology,medical and health sciences,basic medicine,anatomy and morphology,natural sciences,biological sciences,ecology,medical and health sciences,health sciences,nutrition,natural sciences,biological sciences,biophysics,natural sciences,computer and information sciences,software,software applications,simulation software,medical and health sciences,clinical medicine,transplantation,natural sciences,biological sciences,microbiology,medical and health sciences,health sciences,nutrition,obesity,natural sciences,biological sciences,neurobiology,natural sciences,biological sciences,cell biology,medical and health sciences,clinical medicine,transplantation,natural sciences,biological sciences,biological morphology,comparative morphology,humanities,history and archaeology,history,natural sciences,biological sciences,genetics,DNA,natural sciences,biological sciences,genetics,mutation,natural sciences,biological sciences,genetics,chromosomes,natural sciences,biological sciences,biological morphology,comparative morphology,natural sciences,biological sciences,evolutionary biology,natural sciences,biological sciences,genetics,genomes,natural sciences,biological sciences,zoology,invertebrate zoology,natural sciences,biological sciences,biological morphology,comparative morphology,natural sciences,biological sciences,ecology,ecosystems,natural sciences,biological sciences,biological morphology,comparative morphology,natural sciences,biological sciences,zoology,natural sciences,mathematics,pure mathematics,topology,natural sciences,earth and related environmental sciences,palaeontology,natural sciences,biological sciences,genetics,genomes,natural sciences,biological sciences,biological morphology,comparative morphology,humanities,history and archaeology,history,natural sciences,biological sciences,biological morphology,comparative morphology,humanities,history and archaeology,history,natural sciences,biological sciences,microbiology,mycology,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,humanities,arts,social sciences,political sciences,government systems,democracy,social sciences,political sciences,political transitions,elections,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,social sciences,sociology,ideologies,social sciences,political sciences,government systems,democracy,social sciences,sociology,social issues,social sciences,political sciences,political transitions,elections,social sciences,political sciences,government systems,democracy,social sciences,political sciences,political transitions,elections,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,social sciences,law,humanities,history and archaeology,history,social sciences,political sciences,political transitions,elections,social sciences,political sciences,government systems,democracy,social sciences,sociology,social sciences,political sciences,government systems,democracy,humanities,philosophy, ethics and religion,philosophy,political philosophy,social sciences,political sciences,government systems,democracy,natural sciences,chemical sciences,catalysis,humanities,philosophy, ethics and religion,philosophy,social sciences,political sciences,government systems,democracy,social sciences,law,social sciences,sociology,demography,social sciences,political sciences,political transitions,elections,social sciences,political sciences,government systems,democracy,social sciences,psychology,humanities,languages and literature,literature studies,literary genres,essays,social sciences,political sciences,government systems,democracy,social sciences,political sciences,political policies,civil society,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,medical and health sciences,health sciences,infectious diseases,RNA viruses,HIV,social sciences,psychology,social sciences,political sciences,government systems,democracy,social sciences,sociology,governance,social sciences,political sciences,public administration,bureaucracy,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,social sciences,law,social sciences,sociology,governance,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,social sciences,political sciences,government systems,democracy,humanities,history and archaeology,history,social sciences,sociology,social issues,social inequalities,racial inequality,social sciences,political sciences,government systems,democracy,social sciences,political sciences,political policies,civil society,civil society organisations,nongovernmental organizations,social sciences,political sciences,government systems,democracy,engineering and technology,electrical engineering, electronic engineering, information engineering,information engineering,telecommunications,radio technology,radar,social sciences,sociology,anthropology,science and technology studies,social sciences,political sciences,political policies,civil society,civil society organisations,

In [89]:
refs = paths.split(',')
refs = set(refs)
refs = [r.strip() for r in refs]
refs

['',
 'soft matter physics',
 'malaria',
 'navigation systems',
 'fourier analysis',
 'combined heat and power',
 'transport planning',
 'environmental biotechnology',
 'cryptography',
 'electrolysis',
 'alkaline earth metals',
 'stellar astronomy',
 'taxation',
 'paleoecology',
 'dermatology',
 'social issues',
 'bacteriology',
 'fluid mechanics',
 'smart sensors',
 'psychoanalysis',
 'electron microscopy',
 'transplantation',
 'animal feed',
 'human rights law',
 'ethnomusicology',
 'neutron stars',
 'armed conflicts',
 'graph theory',
 'genetics',
 'arteriosclerosis',
 'clinical medicine',
 'theoretical physics',
 'machine learning',
 'homeostasis',
 'bioprocessing technologies',
 'crisis management',
 'industrial crops',
 'physiology',
 'palaeontology',
 'climatology',
 'biosphera',
 'laser physics',
 'physical cosmology',
 'inflammatory bowel disease',
 'satellite technology',
 'geometry',
 'control engineering',
 'object detection',
 'thermochemistry',
 'molecular and chemical physics',
 'leukemia',
 'vascular diseases',
 'psychotherapy',
 'drug resistance',
 'public policies',
 'developmental biology',
 'radiochemistry',
 'marine biology',
 'ebola',
 'energy and fuels',
 'soft robotics',
 'environmental governance',
 'particle accelerator',
 'electric power transmission',
 'educational sciences',
 'computer and information sciences',
 'biofuels',
 'colorectal cancer',
 'ecosystems',
 'piezoelectrics',
 'exposomes',
 'art history',
 'polylactic acid',
 'rotorcraft',
 'quantum computers',
 'industrial biotechnology',
 'gluons',
 'medical laboratory technology',
 'natural satellites',
 'transition metals',
 'photocatalysis',
 'carbon capture engineering',
 'ecosystem-based management',
 'proteomics',
 'melanoma',
 'rheumatology',
 'nanocomposites',
 'essays',
 'chemical engineering',
 'electric vehicles',
 'medieval philosophy',
 'particle physics',
 'public services',
 'business models',
 'history and archaeology',
 'ecology',
 'employment',
 'telecommunications networks',
 'classical mechanics',
 'geographic information systems',
 'ethnoarchaeology',
 'discrete mathematics',
 'nanophotonics',
 'robotics',
 'galaxy evolution',
 'ethics',
 'aeronautical engineering',
 'grains and oilseeds',
 'chromosomes',
 'oncology',
 'elections',
 'multiple sclerosis',
 'performing arts',
 'photochemistry',
 'power engineering',
 'meteorology',
 'atomic physics',
 'sedimentology',
 'nuclear medicine',
 'ethics and religion',
 'electromagnetism and electronics',
 'modern philosophy',
 'computer processors',
 'distillation',
 'mobile network',
 'heat engineering',
 'multiphysics',
 'electrocatalysis',
 'gene therapy',
 'statistics and probability',
 'fruit growing',
 'plate tectonics',
 'pure mathematics',
 'radiology',
 'ideologies',
 'biophysics',
 'microtechnology',
 'cultural and economic geography',
 'irrigation',
 'virology',
 'analytical chemistry',
 'condensed matter physics',
 'philosophy',
 'stem cells',
 'dynamical systems',
 'neurobiology',
 'arithmetics',
 'wearable medical technology',
 'hematology',
 'languages and literature',
 'remote sensing',
 'partial differential equations',
 'environmental sciences',
 'environmental engineering',
 'ecological restoration',
 'pandemics',
 'automation',
 'graphene',
 'hydrology',
 'vehicle engineering',
 'z bosons',
 'solar physics',
 'antibiotic resistance',
 'synthetic biology',
 'astronautical engineering',
 'vaccines',
 'ceramics',
 'animal and dairy science',
 'microbiomes',
 'econometrics',
 'galactic astronomy',
 'isotope geochemistry',
 'eukaryotic genomes',
 'development studies',
 'fodder',
 'climatic change mitigation',
 'neutrinos',
 'microelectronics',
 'cartography',
 'phonetics',
 'aerospace engineering',
 'metaphysics',
 'toxicology',
 'pathology',
 'nuclear chemistry',
 'astrochemistry',
 'manufacturing engineering',
 'hepatology',
 'neurology',
 'energy conversion',
 'biological sciences',
 'terrorism',
 'organic amorphous solids',
 'endocrinology',
 'cardiac arrhythmia',
 'earthquake engineering',
 'teleology',
 'aircraft',
 'radar',
 'earth and related environmental sciences',
 'heredity',
 'magnetic resonance imaging',
 'biocomposites',
 'nanoelectronics',
 'inorganic compounds',
 'allergology',
 'immunology',
 'astrophysics',
 'other engineering and technologies',
 'botany',
 'amorphous solids',
 'production economics',
 'penology',
 'spectroscopy',
 'macroeconomics',
 'corruption',
 'general language studies',
 'globalization',
 'black holes',
 'optical astronomy',
 'pathophysiology',
 'biological morphology',
 'basic medicine',
 'biomass',
 'global development studies',
 'business and management',
 'laboratory samples analysis',
 'innovation management',
 'superconductivity',
 'sensors',
 'pharmaceutical drugs',
 'deep learning',
 'gamma-ray astronomy',
 'social anthropology',
 'humanities',
 'biological interactions',
 'amines',
 'political economy',
 'epistemology',
 'influenza',
 'internet of things',
 'international law',
 'fluid dynamics',
 'fossil energy',
 'alkali metals',
 'breast cancer',
 'autonomous vehicles',
 'telecommunications',
 'mechanical engineering',
 'metabolomes',
 'tuberculosis',
 'medieval history',
 'data science',
 'HIV',
 'biomass energy',
 'transportation engineering',
 'quantum physics',
 'materials engineering',
 'super-Earths',
 'speech-language pathology',
 'functional morphology',
 'wastewater treatment processes',
 'public transport',
 'bioremediation',
 'islam',
 'transcriptomes',
 'software applications',
 'visual arts',
 'parkinson',
 'architecture engineering',
 'DNA',
 'prehistory',
 'physical geography',
 'structural biology',
 'women’s studies',
 'civil society',
 'organometallic chemistry',
 'fibers',
 'aldehydes',
 'gastroenterology',
 'pneumology',
 'epigenetics',
 'fermions',
 'stroke',
 'horticulture',
 'meteorites',
 'information engineering',
 'dairy',
 'waste management',
 'virtual reality',
 'mammalogy',
 'vegetable growing',
 'immunisation',
 'applied mathematics',
 'forestry',
 'reproductive medicine',
 'metallurgy',
 'computational fluid dynamics',
 'multidrug resistance',
 'health sciences',
 'forestry',
 'habitat conservation',
 'mutation',
 'mental processes',
 'implants',
 'seismic loading',
 'alzheimer',
 'plasma physics',
 'diabetes',
 'biodiversity conservation',
 'gynaecology',
 'electronic engineering',
 'revolutions',
 'cognitive neuroscience',
 'biosensing',
 'catalysis',
 'halogens',
 'transport',
 'agricultural sciences',
 'pandemic risks',
 'photons',
 'human trafficking',
 'WiFi',
 'behavioural psychology',
 'obstetrics',
 'molecular neuroscience',
 'public administration',
 'anatomy and morphology',
 'sociology',
 'planetary geology',
 'sustainable architecture',
 'natural sciences',
 'composites',
 'leptons',
 'mathematics',
 'food packaging',
 'arboriculture',
 'invertebrate zoology',
 'social sciences',
 'noble gases',
 'fuel cells',
 'psychology',
 'mineralogy',
 'engineering and technology',
 'monetary and finances',
 'democracy',
 'artificial intelligence',
 'video games',
 'bulk nanostructured materials',
 'wind energy',
 'postnatal care',
 'epigenomes',
 'anthropology',
 'satellite navigation system',
 'biomaterials',
 'simulation software',
 'giant planets',
 'national state of emergency',
 'archaeometry',
 'nucleotides',
 'remanufacturing',
 'bioeconomy',
 'supervised learning',
 'oceanography',
 'nanocrystals',
 'synthetic dyes',
 'library sciences',
 'histology',
 'sustainable agriculture',
 'digital electronics',
 'ethology',
 'history of literature',
 'metalloids',
 'cognitive psychology',
 'asteroids',
 'intelligent transport systems',
 'air pollution engineering',
 'solar energy',
 'quantum chemistry',
 'organic reactions',
 'social developments',
 'political sciences',
 'human migrations',
 'demography',
 'development theories',
 'applied mechanics',
 'nephrology',
 'molecular genetics',
 'higgs bosons',
 'computer vision',
 'data processing',
 'entomology',
 'agronomy',
 'hydrocarbons',
 'cardiology',
 'radiation chemistry',
 'nutrition',
 'parasitology',
 'electrodialysis',
 'edge artificial intelligence',
 'climatic changes',
 'bioplastics',
 'internet',
 'thermodynamic engineering',
 'chemical process engineering',
 'inorganic chemistry',
 'geochronology',
 'gender equality',
 'cell biology',
 'quantum optics',
 'geothermal energy',
 'pedagogy',
 'radio frequency',
 'physical anthropology',
 'geology',
 'data exchange',
 'contemporary history',
 'archaeology',
 'bureaucracy',
 'diagnostic imaging',
 'duchenne muscular dystrophy',
 'desalination',
 'nuclear engineering',
 'signal processing',
 'two-dimensional nanostructures',
 'entrepreneurship',
 'speleology',
 'dementia',
 'census',
 'flood risk management',
 'algebraic geometry',
 'heuristic programming',
 'zoonosis',
 'quarks',
 'antivirals',
 'family planning',
 'ergonomics',
 'generative artificial intelligence',
 'muscular dystrophies',
 'nano-processes',
 'bladder cancer',
 'mycology',
 'molecular biology',
 'political philosophy',
 'racial inequality',
 'family studies',
 'acoustics',
 'prostate cancer',
 'artificial bone',
 'algebra',
 'computational science',
 'synthetic fuels',
 'additive manufacturing',
 'autonomous robots',
 'proteins',
 'drones',
 'microeconomics',
 'cultural anthropology',
 'economic impact of epidemics',
 'law',
 'cinematography',
 'thermodynamics',
 'evolutionary biology',
 'geomorphology',
 'history',
 'crystallography',
 'molecular evolution',
 'spintronics',
 'textiles',
 'post-colonial theories',
 'fisheries',
 'embryology',
 'food technology',
 'data protection',
 'public health',
 'ancient history',
 'astronomy',
 'global navigation satellite system',
 'medical biotechnology',
 'digital humanities',
 'angiology',
 'glacial geology',
 'political transitions',
 'motion analysis',
 'computer security',
 'carbohydrates',
 'psycholinguistics',
 'optical sensors',
 'computational intelligence',
 'primatology',
 'genomes',
 'automotive engineering',
 'software',
 'glaciology',
 'computer hardware',
 'coating and films',
 'colors',
 'governance',
 'tribology',
 'economics and business',
 'epilepsy',
 'dramaturgy',
 'biogeochemistry',
 'human rights violations',
 'data networks',
 'schizophrenia',
 'ontology',
 'ornithology',
 'genetic engineering',
 'software development',
 'behavioural ecology',
 'spacecraft',
 'modern and contemporary art',
 'system software',
 'social geography',
 'liver cancer',
 'paediatrics',
 'organic chemistry',
 'water engineering',
 'cereals',
 'journalism',
 'literature studies',
 'bioarchaeology',
 'religions',
 'atmospheric sciences',
 'geophysics',
 'agriculture',
 'musicology',
 'exoplanetology',
 'coronaviruses',
 'sustainable building',
 'skin cancer',
 'electric power generation',
 'subtractive manufacturing',
 'microbiology',
 'electrical engineering',
 'epidemiology',
 'geotechnics',
 'political policies',
 'infectious diseases',
 'biocatalysis',
 'physical oceanography',
 'mathematical physics',
 'big data',
 'environmental law',
 'health economics',
 'RNA viruses',
 'semiconductivity',
 'industrial relations',
 'planets',
 'hydrometeorology',
 'plant breeding',
 'nano-materials',
 'radio technology',
 'ethical principles',
 'electromagnetism',
 'biomolecules',
 'criminology',
 'sustainable economy',
 'asthma',
 'electrochemistry',
 'fermentation',
 'cell signaling',
 'personalized medicine',
 'zoology',
 'mathematical analysis',
 'cells technologies',
 'lab on a chip',
 'paleoclimatology',
 'animal husbandry',
 'mathematical logic',
 'civil engineering',
 'cetology',
 'aliphatic compounds',
 'pharmacology and pharmacy',
 'ethnolichenology',
 'diagnostic technologies',
 'age inequality',
 'government systems',
 'structural health monitoring',
 'quasiparticles',
 'immunotherapy',
 'architectural design',
 'nongovernmental organizations',
 'agricultural biotechnology',
 'mortality',
 'other social sciences',
 'sustainable transport',
 'organ on a chip',
 'biological behavioural sciences',
 'human rights',
 'cardiovascular diseases',
 'obesity',
 'solar thermal',
 'optoelectronics',
 'databases',
 'photovoltaic',
 'medical and health sciences',
 'physical chemistry',
 'mathematical model',
 'christianity',
 'structural engineering',
 'unemployment',
 'climate change adaptation',
 'social inequalities',
 'psychiatry',
 'biosensors',
 'linguistics',
 'nonlinear optics',
 'glaucoma',
 'foreign policy',
 'productivity',
 'petroleum',
 'ophthalmology',
 'sexual health',
 'bioreactors',
 'antibiotics',
 'history of philosophy',
 'media and communications',
 'contemporary philosophy',
 'microscopy',
 'information engineering',
 'cavity optomechanics',
 'optics',
 'data mining',
 'separation technologies',
 'lipids',
 'ketones',
 'recycling',
 'geochemistry',
 'polymer sciences',
 'phycology',
 'optical networks',
 'calorimetry',
 'modern history',
 'post-transition metals',
 'fertility',
 'agroecology',
 'critical care medicine',
 'nursing',
 'nanomedicine',
 'arts',
 'medical engineering',
 'pharmacokinetics',
 'electronic engineering',
 'civil society organisations',
 'polyurethane',
 'differential equations',
 'kidney diseases',
 'seismology',
 'political violence',
 'analogue electronics',
 'ethnology',
 'water treatment processes',
 'RNA',
 'comparative morphology',
 'quantum field theory',
 'biochemistry',
 'mobile phones',
 'volcanology',
 'economics',
 'inflammatory diseases',
 'and fisheries',
 'phonology',
 'development economics',
 'social psychology',
 'supercomputers',
 'political communication',
 'other humanities',
 'didactics',
 'surgery',
 'coal',
 'planetary sciences',
 'literary genres',
 'ultrasound',
 'knowledge engineering',
 'microfluidics',
 'lung cancer',
 'science and technology studies',
 'urban studies',
 'supernova',
 'nanotechnology',
 'solar astronomy',
 'combinatorics',
 'waste treatment processes',
 'chemical sciences',
 'domestic animals',
 'super resolution microscopy',
 'pollution',
 'amorphous semiconductors',
 'gender studies',
 'dark matter',
 'medical genetics',
 'hydrogen energy',
 'ethical theories',
 'observational astronomy',
 'numerical analysis',
 'topology',
 'physiotherapy',
 'social biomedical sciences',
 'developmental psychology',
 'popular music studies',
 'alcohols',
 'eastern religions',
 'physical sciences',
 'computational neuroscience',
 'enzymes',
 'renewable energy',
 'gender inequality',
 'reinforcement learning',
 'tissue engineering',
 'judaism',
 'logarithmic functions',
 'control systems',
 'quantum gases']

In [90]:
print (len(refs))

715

In [91]:
projects_no_widening['fundingScheme'].unique()

array(['HORIZON-TMA-MSCA-PF-EF', 'HORIZON-ERC', 'HORIZON-ERC-POC',
       'HORIZON-ERC-SYG', 'HORIZON-JU-RIA', 'HORIZON-EIC',
       'HORIZON-JU-IA', 'HORIZON-TMA-MSCA-DN', 'HORIZON-TMA-MSCA-PF-GF',
       'HORIZON-IA', 'HORIZON-CSA', 'HORIZON-RIA',
       'HORIZON-TMA-MSCA-Cofund-P', 'HORIZON-EIC-ACC', 'HORIZON-JU-CSA',
       'HORIZON-TMA-MSCA-SE', 'HORIZON-TMA-MSCA-Cofund-D',
       'HORIZON-TMA-MSCA-DN-JD', 'HORIZON-TMA-MSCA-DN-ID',
       'HORIZON-EIT-KIC'], dtype=object)

In [92]:
projects_filt = projects_no_widening[projects_no_widening['fundingScheme'].isin(['HORIZON-RIA','RIA','HORIZON-EIC'])]

In [93]:
projects_filt

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
212,101259018,OutMARCH,SIGNED,OutMARCH-ing cancer: Towards innovative membra...,2026-05-01,2030-04-30,2999050,2999050,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-23,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,The OutMARCH project pioneers a paradigm-shift...,2026-03-09 16:56:02,282695,10.3030/101259018,"Ubiquitination, lysosomal degradation, nanobodies"
228,101257985,SuperICQ,SIGNED,Superconducting Integrated Circuits for Scalab...,2026-03-01,2030-02-28,"2998012,75","2998012,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Superconducting circuits based on Josephson ju...,2026-01-14 10:03:57,282696,10.3030/101257985,"JoFET, 200 mm wafer-scale, graphene, supercond..."
231,101257934,AI-RITMIA,SIGNED,AI-assisted peRsonalized heart-on-chIp as adva...,2026-08-01,2029-07-31,2999935,2999935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Inherited cardiomyopathies (iCMPs) are a major...,2025-12-29 11:31:21,282698,10.3030/101257934,organ-on-chip; artificial intelligence; cardio...
381,101258941,HeartVision,SIGNED,Illuminating new paths in heart failure therapy,2026-07-01,2030-06-30,"3998796,25","3998796,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-19,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"HeartVision is an ambitious high-risk, high-ga...",2026-01-14 10:03:59,282697,10.3030/101258941,In vivo microscopy of live heart with cell-sca...
862,101223249,2D-ADDICT,SIGNED,TWO-Dimensional materials for ADvanced DevIces...,2025-11-01,2028-10-31,0,"3970518,04",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,2025-11-25,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The grand challenge facing the electronics ind...,2026-03-09 14:41:38,282684,NaN,"Low-power electronics, two-dimensional materia..."
882,101223271,CERBERUS,SIGNED,Unlocking the Full Potential of Edge AI throug...,2026-02-01,2030-01-31,0,"3997743,75",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,2025-06-18,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The introduction of the on-device AI paradigm ...,2026-02-27 17:30:13,273210,10.3030/101223271,"In-memory computing, edge AI, MoS2, hBN, graph..."
1590,101223119,STORM,SIGNED,Solar Weather Forecasting Mission,2025-11-01,2028-04-30,0,"3549793,55",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,2025-11-25,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"In STORM, satellite constellation operation in...",2025-12-10 11:02:05,279234,10.3030/101223119,"Space Weather, Solar Storms, Advanced Space Pr..."
1622,101259068,DRIVIN CAR,SIGNED,DRIVIN' CAR: Developing robust in vivo nanomed...,2026-03-01,2030-02-28,"3000347,5",3000346,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-18,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,DRIVIN’ CAR aims to transform immunotherapy by...,2026-01-12 05:35:38,282625,10.3030/101259068,"Nanoparticles, in vivo CAR cell therapy, CAR T..."
2194,101235287,THUNDER,SIGNED,INNOVATION IN E-MEOH PRODUCTION BY ONE-POT TAN...,2025-10-01,2029-09-30,3992190,3992190,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,2025-08-22,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,"THUNDER aims to develop an innovative, modular...",2025-11-26 11:07:05,276090,10.3030/101235287,"e-MeOH, process intensification, 3D-printed re..."
2529,101290742,ELISET,SIGNED,"Emission Lifetimes technology for sorting, Sec...",2026-07-01,2029-06-30,0,"2253153,25",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-17,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Plastic waste is a clear and present danger to...,2026-03-25 17:00:57,285536,10.3030/101290742,"quantum-dots, circular Economy, photochemistry"
2546,101291374,PROMPT,SIGNED,Proficient Robotic Operation for Minimally-inv...,2026-04-01,2029-03-31,0,2486591,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-16,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,PROMPT (Proficient Robotic Operation for Minim...,2026-03-25 15:15:52,285538,10.3030/101291374,"robotic catheterization, modular gripping, int..."
2547,101268729,IONPAP,SIGNED,Ion Conductive Paper-Based Membranes for Flow ...,2026-04-01,2029-03-31,0,"2491903,63",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-09,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,The Grand Challenge in advancing energy storag...,2026-03-25 15:17:59,285692,10.3030/101268729,"paper, membrane, flow battery, fuel cell, elec..."
2550,101257287,ULTRAPURE,SIGNED,INTEGRATED SOURCES FOR ULTRAPURE OSCILLATIONS ...,2026-02-01,2029-01-31,"3054936,25",3054935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Many high-performance photonics applications w...,2026-03-25 11:55:07,281942,10.3030/101257287,"Stimulated Brillouin Scattering, lithium tanta..."
2556,101291635,STEMPhage,SIGNED,Innovative macrophage therapies to transform t...,2026-05-01,2028-10-31,0,"2499935,06",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-11,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,The STEMPhage project at TU Dresden aims to de...,2026-03-25 15:56:07,285541,10.3030/101291635,"cell therapy, cancer therapy, macrophages, ge..."
2559,101288208,TAILOR,SIGNED,Fine-Tuning AI Foundation Models for Client-Ta...,2026-04-01,2028-09-30,0,"2448801,78",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-16,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Beyond Weather is the first to successfully fi...,2026-03-25 15:56:06,285534,10.3030/101288208,AI weather forecasting seasonal-to-subseasonal...
2576,101287726,SpeedAPP,SIGNED,HIGH SPEED AI-DRIVEN ENGINEERING SIMULATIONS F...,2026-04-01,2028-11-30,0,2431625,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-14,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,New product development is crucial for compani...,2026-03-25 11:50:40,285533,10.3030/101287726,"Engineering simulation, neural operator, reduc..."
2608,101223091,C5,SIGNED,Clever Combination of Synthetic Compartmentali...,2025-11-01,2029-10-31,0,"3930291,98",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,2025-05-21,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The C5 Pathfinder project aims to revolutioniz...,2026-03-24 16:09:18,272683,10.3030/101223091,"Synthetic compartmentalization, Metabolic engi..."
3106,101256857,ULYSSES,SIGNED,Ultrasensitive Luminescence-based Yeast Sensor...,2026-05-01,2029-04-30,"2991106,25","2991106,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,ULYSSES is a pioneering project aimed at devel...,2026-01-27 09:55:20,283248,10.3030/101256857,"Biosensor, Cancer Screening, Breast Cancer, Pr..."
3313,101259077,CHEM-SCAN,SIGNED,HIGH-RESOLUTION FUNCTIONAL OPTICAL IMAGING OF ...,2026-03-01,2030-02-28,"2998207,5","2998207,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The development of chemoresistance, i.e. the a...",2025-12-22 15:23:57,281941,10.3030/101259077,"functional fluorescent probes, chemoresistance..."
3519,101221404,AstrAware,SIGNED,An On-board Dynamic Vision Sensor Suite for En...,2025-10-01,2028-09-30,0,"2957757,13",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,2025-07-30,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The current overpopulation of satellites in or...,2025-10-20 17:38:03,274812,10.3030/101221404,"Debris, Detection, Neuromorphic, Startracker, ..."
3526,101257928,NanoFlash,SIGNED,Cell-targeted Biophotonic Nanoparticles for Vi...,2026-05-01,2030-04-30,"2999978,75",2999978,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NanoFlash aims to develop disruptive nano-enab...,2025-12-22 15:23:57,281936,10.3030/101257928,"photoactivable polymer nanoparticles, cell tar..."
3531,101220926,X-SeeO2,SIGNED,Real-time X-ray diffraction and microstructure...,2025-10-01,2029-09-30,0,"4043885,24",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-05-30,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,X-SeeO2 delivers unique tools to the portfolio...,2025-08-18 13:48:30,272885,10.3030/101220926,"synchrotron radiation, Advanced X-ray powder ..."
3774,101257710,GREENDIGO,SIGNED,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",2026-02-23 17:36:55,281931,10.3030/101257710,"enzymatic dyeing, biocatalysis, textile biotec..."
3850,101291297,FALQON,SIGNED,Fast photonic integrated circuits for continuo...,2026-05-01,2029-04-30,0,"2498823,5",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-04,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Cybersecurity is at a crossroads. Across Europ...,2026-03-18 14:08:17,285043,10.3030/101291297,"Quantum key distribution, quantum cryptography"
3929,101258353,PHINDER,SIGNED,Picosecond-scale Photonic Heterogeneous Integr...,2026-04-01,2030-03-31,"3129503,75","3129503,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-21,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Advanced applications—ranging from 5D-imaging ...,2026-02-03 05:45:15,283727,10.3030/101258353,"optoelectronics, heterogeneous integration, co..."
4017,101284471,NEOMAG,SIGNED,UNLOCKING INNOVATION OPPORTUNITIES IN MECHANOB...,2026-03-01,2029-02-28,0,"2394825,7",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-02,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Mechanical forces critically shape processes s...,2026-03-18 14:05:02,284830,10.3030/101284471,"mechanobiology, cell mechanics, magneto-mechan..."
4588,101258189,CarboNcare,SIGNED,CARBON-EFFICIENT BIOPRODUCTION OF CHEMICALS FR...,2026-05-01,2030-04-30,"3135362,35","3135362,35",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,A major challenge in carbon-based bioproductio...,2026-01-08 18:05:13,281935,10.3030/101258189,"Metabolic engineering, Respiro-fermentation, G..."
4631,101258419,INTEGRAL,SIGNED,INTEGRATED PHOTONICS FOR SIGNAL PROCESSING AND...,2026-03-01,2029-02-28,2999500,2999500,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-15,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Optical Coherence Tomography (OCT) is a powerf...,2025-12-22 15:23:57,281943,10.3030/101258419,"lasers, photonics, OCT. biomedical, tunable la..."
5023,101181686,ArcticKnows,SIGNED,Just knowledge co-creation for a regenerative ...,2025-10-01,2028-09-30,0,"2809495,63",HORIZON.2.6,HORIZON-CL6-2024-COMMUNITIES-01-3,2025-08-19,HORIZON,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-RIA,"ArcticKnows will empower Coastal, Local and In...",2025-08-28 16:06:09,276067,10.3030/101181686,"Regenerative economy, Environmental justice, M..."
5125,101216412,HARARA,SIGNED,Co-creating inclusive local climate adaptation...,2026-01-01,2028-12-31,"1999658,75","1999658,75",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,2025-05-07,HORIZON,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,"European societies, especially in urban areas,...",2026-01-07 15:05:24,272926,10.3030/101216412,migration; heat; air temperature; atmospheric ...
5148,101216923,URBAN PROSUMERS,SIGNED,URBAN PROSUMERS – towards a knowledge transfer...,2025-10-01,2028-03-31,"1999847,5","1999847,25",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,2025-05-07,HORIZON,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,The URBAN PROSUMERS project supports the imple...,2026-03-04 13:58:10,272773,10.3030/101216923,"Climate Neutral and Smart Cities, citizen enga..."
6059,101223335,CONCERTO,SIGNED,CarbOn Negative CemEnt fRom ulTra-mafic rOcks,2025-10-01,2029-09-30,0,"4521199,7",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-06-13,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The majority of CO2 emissions associated with ...,2025-11-26 11:04:34,273192,10.3030/101223335,"Silico-magnesia cement, Ultramafic rocks, Low-..."
6133,101221259,ECO-SLAG-CEM,SIGNED,ENVIRONMENTALLY COMPATIBLE OPTIMIZATION OF EAF...,2025-10-01,2029-09-30,0,"3991545,98",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-06-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"""The ECO-SLAG-CEM project aims to develop high...",2026-02-03 17:08:19,273187,10.3030/101221259,"SCM, Cement, EAF-Cement, EAF, Slag, low clinke..."
6264,101259117,REMMIA,SIGNED,REcycling perManent Magnets: an Innovative App...,2026-03-01,2030-02-28,"2991615,75","2991615,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-14,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Rare earth elements (REE) are crucial for mode...,2026-03-03 10:37:30,283247,10.3030/101259117,magnet recycling; magneto-electrochemistry; ra...
6444,101257982,MECH-QUBIT,SIGNED,MECHanical QUBIT With Enhanced Coherence,2026-02-01,2030-01-31,3072590,3072590,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"Condensed-matter qubits, such as transmons and...",2025-12-22 15:23:57,281938,10.3030/101257982,NaN
6508,101257628,AMFactory,SIGNED,Engineering bioreactor mass production of arbu...,2026-05-01,2029-04-30,2993767,2993767,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-18,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Microbial inoculants containing arbuscular myc...,2026-01-05 11:58:05,281932,10.3030/101257628,"lipid biosynthesis, signaling compounds, micro..."
6819,101223193,SUN2CN,SIGNED,Fully-Integrated PV-EC Device for the Producti...,2025-11-01,2029-10-31,0,"3997401,47",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,2025-06-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The SUN2CN project aims to deliver a standalon...,2026-03-17 09:59:42,273191,10.3030/101223193,Photovoltaic–electrochemical device; Organonit...
7865,101257413,HEARTCORE,SIGNED,HUMAN-BASED ADVANCED CARDIAC SAFETY PLATFORM I...,2026-06-01,2030-05-31,"2993436,25",2993436,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Cardiac safety testing still relies on animal ...,2026-03-04 14:18:57,281929,10.3030/101257413,MEA; cardiac organoids; human pluripotent stem...
8653,101259183,NEQIOS,SIGNED,Neuromorphic Quantum-Inspired Optimization and...,2026-03-01,2031-02-28,"3358894,25","3333894,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-17,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NEQIOS introduces a radically new approach to ...,2026-03-10 17:04:33,281944,10.3030/101259183,Neuromorphic Computing; Quantum-Inspired Optim...
8844,101223135,C-SINC,SIGNED,Concrete products through sustainable and inno...,2025-10-01,2029-09-30,0,"3997434,44",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-11-24,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The cement industry is a major contributor to ...,2026-01-12 11:36:02,279240,10.3030/101223135,"CO2 Sequestration,Mineral Carbonation,Accelera..."
9057,101236115,C2FUe-LS,SIGNED,Turning recycled carbon into valuable fuels fo...,2025-10-01,2029-09-30,"4028302,5",4028302,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,2025-09-26,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,+C2Fue-LS aims to develop a direct cold plasma...,2026-02-03 13:56:56,276516,10.3030/101236115,NaN
9318,101221957,MOJITO,SIGNED,Decarbonized liMe PrOduction through enhanced ...,2025-10-01,2028-09-30,0,"2235763,33",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,2025-04-16,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The MOJITO project aims to validate a laborato...,2025-11-26 11:04:01,272918,10.3030/101221957,"lime, microwaves, calcination, machine learnin..."
9823,101259120,FeROS,SIGNED,Prodrugs oF antiparasitic RedOx-active compoundS,2026-03-01,2030-02-28,"3046491,25","3046491,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-14,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"With 600,000 deaths per year, malaria remains ...",2026-01-27 09:55:21,283249,10.3030/101259120,"antiparasitic drugs, malaria, neglected parasi..."
10520,101257530,ALERT,SIGNED,MULTIANALYTE DIGITAL SENSING WITH QR-CODE MICR...,2026-03-01,2029-02-28,"2917386,25","2917386,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2025-12-16,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"""ALERT introduces a groundbreaking leap in med...",2025-12-22 15:23:57,281930,10.3030/101257530,"Digital sensing, digital microneedles, QR code..."
10532,101292269,PARADISE,SIGNED,PlAsma technologies for Remediation of Air for...,2026-03-01,2028-04-30,0,"2494956,16",HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,2026-03-02,HORIZON,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,PARADISE introduces an innovative cold plasma-...,2026-03-18 14:05:10,284838,10.3030/101292269,"Cold plasma reactor, Microwave sintering, Indu..."
10765,101219355,SOLARSPOON,SIGNED,Solar-driven synthesis of proteins and lipids ...,2025-11-01,2029-10-31,0,"3999731,63",HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,2025-06-18,HORIZON,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,Biohybrid systems offer unique energy-efficien...,2025-09-01 23:34:51,273209,10.3030/101219355,"Biohybrid, photoelectrochemistry, proteins, li..."
10770,101258103,PROPANTHERA,SIGNED,Retrograde atrophy induction: a paradigm shift...,2026-03-01,2029-02-28,3140625,3140625,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,2026-01-28,HORIZON,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Pancreatic cancer (PaC) is a leading cause of ...,2026-02-06 13:24:36,283675,10.3030/101258103,"thermal ablation, medical devices, pancreatic ..."
15927,101234842,COMPASS,SIGNED,Comprehensive Offshore Management Platform for...,2025-11-01,2029-10-31,0,"4999786,87",HORIZON.2.5,HORIZON-CL5-2024-D3-02-08,2025-08-22,HORIZON,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,Europe is at the forefront of offshore wind en...,2026-01-07 15:11:33,276087,10.3030/101234842,"Sustainability, Offshore wind farm design, Cum..."

In [94]:
projects_ = projects_filt[['id','acronym','title','startDate','endDate','totalCost','legalBasis','topics','masterCall','subCall','fundingScheme','objective','grantDoi']]

In [95]:
projects_['topics'].tolist()

['HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL6-2024-COMMUNITIES-01-3',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-MISS-2024-CROSS-02-01',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-CL5-2024-D3-02-02',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-EIC-2025-TRANSITIONOPEN',
 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01',
 'HORIZON-EIC-2025-PATHFINDEROPEN',
 'HORIZON-CL5-2024-D3-02-08']

In [96]:
# Define function to assign clusters
def assign_cluster(topic):
    if "CL2" in topic:
        return "Cluster 2"
    elif "CL3" in topic:
        return "Cluster 3"
    elif "CL4" in topic:
        return "Cluster 4"
    elif "CL5" in topic:
        return "Cluster 5"
    elif "CL6" in topic:
        return "Cluster 6"
    elif "HLTH" in topic:
        return "Cluster Health"
    elif "MISS" in topic:
        return "Cluster MISS"
    else:
        return "Other"

# Apply function to create a new column
projects_["cluster"] = projects_["topics"].apply(assign_cluster)

C:\Users\user\AppData\Local\Temp\ipykernel_6008\2163152521.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  projects_["cluster"] = projects_["topics"].apply(assign_cluster)

In [97]:
projects_

,id,acronym,title,startDate,endDate,totalCost,legalBasis,topics,masterCall,subCall,fundingScheme,objective,grantDoi,cluster
212,101259018,OutMARCH,OutMARCH-ing cancer: Towards innovative membra...,2026-05-01,2030-04-30,2999050,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,The OutMARCH project pioneers a paradigm-shift...,10.3030/101259018,Other
228,101257985,SuperICQ,Superconducting Integrated Circuits for Scalab...,2026-03-01,2030-02-28,"2998012,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Superconducting circuits based on Josephson ju...,10.3030/101257985,Other
231,101257934,AI-RITMIA,AI-assisted peRsonalized heart-on-chIp as adva...,2026-08-01,2029-07-31,2999935,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Inherited cardiomyopathies (iCMPs) are a major...,10.3030/101257934,Other
381,101258941,HeartVision,Illuminating new paths in heart failure therapy,2026-07-01,2030-06-30,"3998796,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"HeartVision is an ambitious high-risk, high-ga...",10.3030/101258941,Other
862,101223249,2D-ADDICT,TWO-Dimensional materials for ADvanced DevIces...,2025-11-01,2028-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The grand challenge facing the electronics ind...,NaN,Other
882,101223271,CERBERUS,Unlocking the Full Potential of Edge AI throug...,2026-02-01,2030-01-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The introduction of the on-device AI paradigm ...,10.3030/101223271,Other
1590,101223119,STORM,Solar Weather Forecasting Mission,2025-11-01,2028-04-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"In STORM, satellite constellation operation in...",10.3030/101223119,Other
1622,101259068,DRIVIN CAR,DRIVIN' CAR: Developing robust in vivo nanomed...,2026-03-01,2030-02-28,"3000347,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,DRIVIN’ CAR aims to transform immunotherapy by...,10.3030/101259068,Other
2194,101235287,THUNDER,INNOVATION IN E-MEOH PRODUCTION BY ONE-POT TAN...,2025-10-01,2029-09-30,3992190,HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,"THUNDER aims to develop an innovative, modular...",10.3030/101235287,Cluster 5
2529,101290742,ELISET,"Emission Lifetimes technology for sorting, Sec...",2026-07-01,2029-06-30,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Plastic waste is a clear and present danger to...,10.3030/101290742,Other
2546,101291374,PROMPT,Proficient Robotic Operation for Minimally-inv...,2026-04-01,2029-03-31,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,PROMPT (Proficient Robotic Operation for Minim...,10.3030/101291374,Other
2547,101268729,IONPAP,Ion Conductive Paper-Based Membranes for Flow ...,2026-04-01,2029-03-31,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,The Grand Challenge in advancing energy storag...,10.3030/101268729,Other
2550,101257287,ULTRAPURE,INTEGRATED SOURCES FOR ULTRAPURE OSCILLATIONS ...,2026-02-01,2029-01-31,"3054936,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Many high-performance photonics applications w...,10.3030/101257287,Other
2556,101291635,STEMPhage,Innovative macrophage therapies to transform t...,2026-05-01,2028-10-31,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,The STEMPhage project at TU Dresden aims to de...,10.3030/101291635,Other
2559,101288208,TAILOR,Fine-Tuning AI Foundation Models for Client-Ta...,2026-04-01,2028-09-30,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Beyond Weather is the first to successfully fi...,10.3030/101288208,Other
2576,101287726,SpeedAPP,HIGH SPEED AI-DRIVEN ENGINEERING SIMULATIONS F...,2026-04-01,2028-11-30,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,New product development is crucial for compani...,10.3030/101287726,Other
2608,101223091,C5,Clever Combination of Synthetic Compartmentali...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The C5 Pathfinder project aims to revolutioniz...,10.3030/101223091,Other
3106,101256857,ULYSSES,Ultrasensitive Luminescence-based Yeast Sensor...,2026-05-01,2029-04-30,"2991106,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,ULYSSES is a pioneering project aimed at devel...,10.3030/101256857,Other
3313,101259077,CHEM-SCAN,HIGH-RESOLUTION FUNCTIONAL OPTICAL IMAGING OF ...,2026-03-01,2030-02-28,"2998207,5",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The development of chemoresistance, i.e. the a...",10.3030/101259077,Other
3519,101221404,AstrAware,An On-board Dynamic Vision Sensor Suite for En...,2025-10-01,2028-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The current overpopulation of satellites in or...,10.3030/101221404,Other
3526,101257928,NanoFlash,Cell-targeted Biophotonic Nanoparticles for Vi...,2026-05-01,2030-04-30,"2999978,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NanoFlash aims to develop disruptive nano-enab...,10.3030/101257928,Other
3531,101220926,X-SeeO2,Real-time X-ray diffraction and microstructure...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,X-SeeO2 delivers unique tools to the portfolio...,10.3030/101220926,Other
3774,101257710,GREENDIGO,Biosolutions for Denim Dyeing within the Plane...,2026-04-01,2030-03-31,2999145,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"The global denim industry, producing over 3 bi...",10.3030/101257710,Other
3850,101291297,FALQON,Fast photonic integrated circuits for continuo...,2026-05-01,2029-04-30,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Cybersecurity is at a crossroads. Across Europ...,10.3030/101291297,Other
3929,101258353,PHINDER,Picosecond-scale Photonic Heterogeneous Integr...,2026-04-01,2030-03-31,"3129503,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Advanced applications—ranging from 5D-imaging ...,10.3030/101258353,Other
4017,101284471,NEOMAG,UNLOCKING INNOVATION OPPORTUNITIES IN MECHANOB...,2026-03-01,2029-02-28,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,Mechanical forces critically shape processes s...,10.3030/101284471,Other
4588,101258189,CarboNcare,CARBON-EFFICIENT BIOPRODUCTION OF CHEMICALS FR...,2026-05-01,2030-04-30,"3135362,35",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,A major challenge in carbon-based bioproductio...,10.3030/101258189,Other
4631,101258419,INTEGRAL,INTEGRATED PHOTONICS FOR SIGNAL PROCESSING AND...,2026-03-01,2029-02-28,2999500,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Optical Coherence Tomography (OCT) is a powerf...,10.3030/101258419,Other
5023,101181686,ArcticKnows,Just knowledge co-creation for a regenerative ...,2025-10-01,2028-09-30,0,HORIZON.2.6,HORIZON-CL6-2024-COMMUNITIES-01-3,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-CL6-2024-COMMUNITIES-01,HORIZON-RIA,"ArcticKnows will empower Coastal, Local and In...",10.3030/101181686,Cluster 6
5125,101216412,HARARA,Co-creating inclusive local climate adaptation...,2026-01-01,2028-12-31,"1999658,75",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,"European societies, especially in urban areas,...",10.3030/101216412,Cluster MISS
5148,101216923,URBAN PROSUMERS,URBAN PROSUMERS – towards a knowledge transfer...,2025-10-01,2028-03-31,"1999847,5",HORIZON.2.1,HORIZON-MISS-2024-CROSS-02-01,HORIZON-MISS-2024-CROSS-02,HORIZON-MISS-2024-CROSS-02,HORIZON-RIA,The URBAN PROSUMERS project supports the imple...,10.3030/101216923,Cluster MISS
6059,101223335,CONCERTO,CarbOn Negative CemEnt fRom ulTra-mafic rOcks,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The majority of CO2 emissions associated with ...,10.3030/101223335,Other
6133,101221259,ECO-SLAG-CEM,ENVIRONMENTALLY COMPATIBLE OPTIMIZATION OF EAF...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,"""The ECO-SLAG-CEM project aims to develop high...",10.3030/101221259,Other
6264,101259117,REMMIA,REcycling perManent Magnets: an Innovative App...,2026-03-01,2030-02-28,"2991615,75",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Rare earth elements (REE) are crucial for mode...,10.3030/101259117,Other
6444,101257982,MECH-QUBIT,MECHanical QUBIT With Enhanced Coherence,2026-02-01,2030-01-31,3072590,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"Condensed-matter qubits, such as transmons and...",10.3030/101257982,Other
6508,101257628,AMFactory,Engineering bioreactor mass production of arbu...,2026-05-01,2029-04-30,2993767,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Microbial inoculants containing arbuscular myc...,10.3030/101257628,Other
6819,101223193,SUN2CN,Fully-Integrated PV-EC Device for the Producti...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The SUN2CN project aims to deliver a standalon...,10.3030/101223193,Other
7865,101257413,HEARTCORE,HUMAN-BASED ADVANCED CARDIAC SAFETY PLATFORM I...,2026-06-01,2030-05-31,"2993436,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Cardiac safety testing still relies on animal ...,10.3030/101257413,Other
8653,101259183,NEQIOS,Neuromorphic Quantum-Inspired Optimization and...,2026-03-01,2031-02-28,"3358894,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,NEQIOS introduces a radically new approach to ...,10.3030/101259183,Other
8844,101223135,C-SINC,Concrete products through sustainable and inno...,2025-10-01,2029-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The cement industry is a major contributor to ...,10.3030/101223135,Other
9057,101236115,C2FUe-LS,Turning recycled carbon into valuable fuels fo...,2025-10-01,2029-09-30,"4028302,5",HORIZON.2.5,HORIZON-CL5-2024-D3-02-02,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,+C2Fue-LS aims to develop a direct cold plasma...,10.3030/101236115,Cluster 5
9318,101221957,MOJITO,Decarbonized liMe PrOduction through enhanced ...,2025-10-01,2028-09-30,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,The MOJITO project aims to validate a laborato...,10.3030/101221957,Other
9823,101259120,FeROS,Prodrugs oF antiparasitic RedOx-active compoundS,2026-03-01,2030-02-28,"3046491,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"With 600,000 deaths per year, malaria remains ...",10.3030/101259120,Other
10520,101257530,ALERT,MULTIANALYTE DIGITAL SENSING WITH QR-CODE MICR...,2026-03-01,2029-02-28,"2917386,25",HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,"""ALERT introduces a groundbreaking leap in med...",10.3030/101257530,Other
10532,101292269,PARADISE,PlAsma technologies for Remediation of Air for...,2026-03-01,2028-04-30,0,HORIZON.3.1,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC-2025-TRANSITIONOPEN,HORIZON-EIC,PARADISE introduces an innovative cold plasma-...,10.3030/101292269,Other
10765,101219355,SOLARSPOON,Solar-driven synthesis of proteins and lipids ...,2025-11-01,2029-10-31,0,HORIZON.3.1,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC-2024-PATHFINDERCHALLENGES-01,HORIZON-EIC,Biohybrid systems offer unique energy-efficien...,10.3030/101219355,Other
10770,101258103,PROPANTHERA,Retrograde atrophy induction: a paradigm shift...,2026-03-01,2029-02-28,3140625,HORIZON.3.1,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC-2025-PATHFINDEROPEN,HORIZON-EIC,Pancreatic cancer (PaC) is a leading cause of ...,10.3030/101258103,Other
15927,101234842,COMPASS,Comprehensive Offshore Management Platform for...,2025-11-01,2029-10-31,0,HORIZON.2.5,HORIZON-CL5-2024-D3-02-08,HORIZON-CL5-2024-D3-02,HORIZON-CL5-2024-D3-02,HORIZON-RIA,Europe is at the forefront of offshore wind en...,10.3030/101234842,Cluster 5

In [98]:
projects_.to_csv('projects.csv',index=False,sep='|')

In [99]:
orgs_ = orgs_no_widening[orgs_no_widening['projectID'].isin(projects_['id'].tolist())]

In [100]:
orgs_

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
2038,101259018,OutMARCH,999518362,NL002958697B01,KONINKLIJKE NEDERLANDSE AKADEMIE VAN WETENSCHA...,KNAW,False,REC,KLOVENIERSBURGWAL 29 HET TRIPPENHUIS,1011 JV,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-09 16:56:02,1905735,2,participant,540000.00,540000.00,540000,False,NaN
2039,101259018,OutMARCH,999867465,DE811917555,UNIVERSITATSKLINIKUM BONN,UKB,False,HES,VENUSBERG-CAMPUS 1,53127,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-09 16:56:02,1906474,3,participant,719250.00,719250.00,719250,False,NaN
2040,101259018,OutMARCH,876034937,NL863403505B01,Laigo Bio B.V.,Laigo Bio,True,PRC,Jaarbeursplein 6,3521 AL,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-09 16:56:02,1994900,5,participant,461250.00,461250.00,461250,False,NaN
2041,101259018,OutMARCH,999915189,NL004205315B01,UNIVERSITAIR MEDISCH CENTRUM UTRECHT,UMC UTRECHT,False,HES,HEIDELBERGLAAN 100,3584 CX,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-09 16:56:02,1906267,1,coordinator,829375.00,829375.00,829375,False,NaN
2042,101259018,OutMARCH,999976396,CHE115665634MWST,UNIVERSITAT ZURICH,UZH,False,HES,RAMISTRASSE 71,8006,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-09 16:56:02,1948772,4,participant,449175.00,449175.00,449175,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113599,101234842,COMPASS,881903340,FR59452796436,NATURAL POWER,NaN,False,PRC,15 QUAI ERNEST RENAUD,44100,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1982789,12,participant,125342.75,125342.75,0,False,NaN
113600,101234842,COMPASS,997826585,NO855869942MVA,NORSK INSTITUTT FOR VANNFORSKNING STI,NORWEGIAN INSTITUTE FOR WATER RESEARCH,False,REC,OKERNVEIEN 94,0579,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1907874,9,participant,200477.50,200477.50,0,False,NaN
113601,101234842,COMPASS,999986484,ESQ0818002H,UNIVERSITAT AUTONOMA DE BARCELONA,UAB,False,HES,EDIF A CAMPUS DE LA UAB BELLATERRA CERDANYOLA V,08193,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1909226,4,participant,397062.50,397062.50,0,False,NaN
113602,101234842,COMPASS,897214208,FR50845019231,FRANCE ENERGIES MARINES,NaN,True,PRC,525 AVENUE ALEXIS DE ROCHON BATIMENT CAP OCEAN,29280,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1972531,1,coordinator,897731.25,897731.25,0,False,NaN
113603,101234842,COMPASS,999591209,FI02459042,LAPPEENRANNAN-LAHDEN TEKNILLINEN YLIOPISTO LUT,LUT University,False,HES,YLIOPISTONKATU 34,53850,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-01-07 15:11:33,1918456,6,participant,280442.50,280442.50,0,False,NaN

In [101]:
orgs_ = orgs_[['projectID','name','shortName','SME','activityType','city','country','organizationURL','contactForm','order','role','ecContribution']]

In [102]:
print (orgs_['country'].unique())

['NL' 'DE' 'CH' 'FI' 'UK' 'SE' 'FR' 'IT' 'NO' 'ES' 'AT' 'BE' 'LU' 'DK'
 'IE' 'IS' 'GL' 'US']

In [103]:
orgs_.to_csv('orgs.csv',index=False,sep='|')

In [104]:
projects_fil

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
2,101236710,eRISIKO,SIGNED,AI-Driven Dynamic Fire Risk Assessment for Ele...,2026-01-01,2029-12-31,0,450900,HORIZON.1.2,HORIZON-MSCA-2024-SE-01-01,2025-07-31,HORIZON,HORIZON-MSCA-2024-SE-01,HORIZON-MSCA-2024-SE-01,HORIZON-TMA-MSCA-SE,The eRISIKO project enhances international mob...,2026-01-07 15:11:22,274828,10.3030/101236710,"Electric vehicle fires, fire risk assessment, ..."
10,101211309,SDL-MFHYD,SIGNED,Accelerated quantification of photolytic hydro...,2026-09-01,2028-08-31,0,"260347,92",HORIZON.1.2,HORIZON-MSCA-2024-PF-01-01,2025-02-27,HORIZON,HORIZON-MSCA-2024-PF-01,HORIZON-MSCA-2024-PF-01,HORIZON-TMA-MSCA-PF-EF,The fossil fuel sector is projected to emit 20...,2026-03-17 09:58:45,269099,10.3030/101211309,"Self-driving laboratories, Automation, clean e..."
17,101227453,ELEVATE,SIGNED,"Event-based LEarning, Vision, And conTrol for ...",2026-01-01,2029-12-31,0,"4522697,28",HORIZON.1.2,HORIZON-MSCA-2024-DN-01-01,2025-07-02,HORIZON,HORIZON-MSCA-2024-DN-01,HORIZON-MSCA-2024-DN-01,HORIZON-TMA-MSCA-DN,"Computing with neuromorphic hardware, learning...",2026-03-24 16:20:15,274448,NaN,"neuromorphic engineering, event cameras, neuro..."
19,101226762,CAFE-BIO,SIGNED,A Coherent Analysis Framework for Emergence in...,2026-02-01,2030-01-31,0,"4541464,08",HORIZON.1.2,HORIZON-MSCA-2024-DN-01-01,2025-07-03,HORIZON,HORIZON-MSCA-2024-DN-01,HORIZON-MSCA-2024-DN-01,HORIZON-TMA-MSCA-DN,This network will provide a rigorous training ...,2026-03-30 11:36:47,274527,NaN,Active matter physics; Biological/living matte...
28,101219872,MAD-TENSOR,SIGNED,Machine-learned Atomic Descriptors combined wi...,2026-01-01,2030-12-31,1498705,1498705,HORIZON.1.1,ERC-2025-STG,2025-10-10,HORIZON,ERC-2025-STG,ERC-2025-STG,HORIZON-ERC,"""Metallic alloys form the backbone of modern i...",2025-10-20 17:38:03,277765,10.3030/101219872,Atomistic SimulationsMachine-learning Potentia...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20211,101248363,PhotoSERS,SIGNED,Molecularly Imprinted Photoactive Microswimmer...,2025-11-01,2027-04-30,0,150000,HORIZON.1.1,ERC-2025-POC,2025-07-09,HORIZON,ERC-2025-POC,ERC-2025-POC,HORIZON-ERC-POC,"Per- and polyfluoroalkyl substances (PFAS), co...",2025-11-26 11:07:33,274571,NaN,NaN
20215,101217014,ECROS,SIGNED,Empowering Early Career Researchers with new O...,2025-10-01,2028-09-30,2000816,2000816,HORIZON.4.2,HORIZON-WIDERA-2024-ERA-02-03,2025-04-16,HORIZON,HORIZON-WIDERA-2024-ERA-02,HORIZON-WIDERA-2024-ERA-02,HORIZON-CSA,"Driven by a powerful consortium, composed of n...",2025-11-26 10:57:28,272559,10.3030/101217014,"research talent ecosystem, early-career resear..."
20217,101198795,NumAStAI,SIGNED,Numerical Analysis for Stable AI,2026-01-01,2030-12-31,0,2498941,HORIZON.1.1,ERC-2024-ADG,2025-07-15,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,From a numerical analysis perspective I will i...,2025-07-23 10:54:27,274629,10.3030/101198795,Mathematical aspects of Artificial Intelligence
20220,101199253,COLUMNET,SIGNED,Efficient odour representations in the olfacto...,2026-10-01,2031-09-30,0,3453563,HORIZON.1.1,ERC-2024-ADG,2025-07-07,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,How is the percept of a smell generated from t...,2025-07-14 10:30:08,274483,NaN,"olfaction, neural network oscillation, olfacto..."
20290,101201020,BRICMEM,SIGNED,Brain-inspired Computational Memory,2026-01-01,2030-12-31,0,2493073,HORIZON.1.1,ERC-2024-ADG,2025-10-31,HORIZON,ERC-2024-ADG,ERC-2024-ADG,HORIZON-ERC,Deep neural networks (DNNs) have transformed t...,2025-11-14 12:36:44,278545,10.3030/101201020,"In-memory computing, brain-inspired computing,..."

In [105]:
from collections import Counter

In [106]:
print (Counter(projects_fil['topics']))

Counter({'HORIZON-MSCA-2024-PF-01-01': 902, 'ERC-2025-STG': 454, 'HORIZON-MSCA-2025-PF-01-01': 418, 'ERC-2024-ADG': 254, 'ERC-2025-COG': 240, 'ERC-2025-POC': 185, 'HORIZON-MSCA-2024-DN-01-01': 142, 'HORIZON-MSCA-2024-SE-01-01': 78, 'ERC-2024-COG': 78, 'ERC-2025-SyG': 52, 'HORIZON-EIC-2025-PATHFINDEROPEN': 39, 'HORIZON-WIDERA-2024-TALENTS-02-01': 32, 'HORIZON-MSCA-2025-COFUND-01-01': 28, 'HORIZON-EIC-2025-ACCELERATOR-02-OPEN-01': 28, 'ERC-2024-STG': 21, 'HORIZON-MSCA-2024-COFUND-01-01': 21, 'HORIZON-EIC-2025-TRANSITIONOPEN': 10, 'ERC-2024-POC': 9, 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01': 7, 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-04': 6, 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-03': 6, 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-02': 6, 'HORIZON-CL3-2024-CS-01-01': 6, 'HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-05': 5, 'HORIZON-CL3-2024-CS-01-02': 5, 'HORIZON-MISS-2024-CROSS-02-01': 4, 'HORIZON-MISS-2024-CIT-01-04': 4, 'HORIZON-CL5-2024-D3-02-02': 4, 'HORIZON-JU-IHI-2025-09-02-single-stage': 4, 'HORIZON-CL5-2024-D3-02-10': 4, 'HORIZON-CL5-2024-D3-02-06': 3, 'HORIZON-CL3-2024-DRS-01-02': 3, 'HORIZON-MISS-2024-CIT-01-01': 3, 'ERC-2024-SyG': 3, 'HORIZON-JU-CLEANH2-2025-06-01': 3, 'HORIZON-JU-CLEANH2-2025-01-01': 3, 'HORIZON-EIC-2025-ACCELERATOR-02-CHALLENGES-01': 3, 'HORIZON-MISS-2024-CLIMA-01-07': 3, 'HORIZON-MISS-2024-CIT-01-02': 3, 'HORIZON-WIDERA-2024-ERA-02-03': 3, 'HORIZON-CL5-2024-D3-02-03': 3, 'HORIZON-JU-GH-EDCTP3-2024-01-01-two-stage': 3, 'HORIZON-CL3-2024-SSRI-01-02': 3, 'HORIZON-JU-IHI-2025-09-03-single-stage': 2, 'HORIZON-MISS-2024-CLIMA-01-04': 2, 'HORIZON-CL2-2024-HERITAGE-ECCCH-01-03': 2, 'HORIZON-JU-CLEANH2-2025-01-02': 2, 'HORIZON-CL5-2024-D4-02-05': 2, 'HORIZON-CL5-2024-D4-02-01': 2, 'HORIZON-CL5-2024-D4-02-03': 2, 'HORIZON-CL5-2024-D4-02-02': 2, 'HORIZON-JU-CLEAN-AVIATION-2025-03-ACI-01': 2, 'HORIZON-JU-CLEAN-AVIATION-2025-03-FTA-01': 2, 'HORIZON-CL5-2025-02-D2-11': 2, 'HORIZON-CL5-2024-D3-02-05': 2, 'HORIZON-EIC-2024-ACCELERATOROPEN-01': 2, 'HORIZON-EIC-2025-ACCELERATOR-02-CHALLENGES-03': 2, 'HORIZON-CL2-2024-HERITAGE-ECCCH-01-01': 2, 'HORIZON-CL5-2024-D3-02-09': 2, 'HORIZON-CL3-2024-BM-01-05': 2, 'HORIZON-CL6-2024-CLIMATE-01-6': 2, 'HORIZON-CL6-2024-COMMUNITIES-02-2-two-stage': 2, 'HORIZON-CL6-2024-CircBio-01-10': 2, 'HORIZON-WIDERA-2024-TALENTS-03-01': 2, 'HORIZON-JU-IHI-2025-09-04-single-stage': 2, 'HORIZON-CL5-2024-D3-02-12': 2, 'HORIZON-CL3-2024-FCT-01-06': 2, 'HORIZON-CL5-2024-D3-02-08': 2, 'HORIZON-MISS-2024-SOIL-01-01': 2, 'HORIZON-JU-EUROHPC-2025-AI-01-IBA-01': 2, 'HORIZON-CL2-2024-HERITAGE-ECCCH-01-02': 2, 'HORIZON-CL2-2024-HERITAGE-ECCCH-01-04': 2, 'HORIZON-CL2-2024-HERITAGE-ECCCH-01-05': 2, 'HORIZON-CL5-2024-D3-02-11': 2, 'HORIZON-JU-CLEANH2-2025-01-03': 2, 'ERC-2023-COG': 2, 'HORIZON-CL3-2024-DRS-01-04': 2, 'HORIZON-CL3-2024-SSRI-01-01': 2, 'HORIZON-CL5-2024-D3-02-04': 2, 'HORIZON-MISS-2025-05-SOIL-SGA-02': 1, 'HORIZON-JU-CLEANH2-2025-02-01': 1, 'HORIZON-JU-IHI-2025-09-05-single-stage': 1, 'HORIZON-JU-IHI-2024-08-01-two-stage': 1, 'HORIZON-JU-CLEANH2-2025-05-03': 1, 'HORIZON-JU-CLEANH2-2025-01-04': 1, 'HORIZON-JU-CLEANH2-2025-01-05': 1, 'HORIZON-CL6-2024-GOVERNANCE-01-7': 1, 'HORIZON-JU-EUROHPC-2025-AIFA-01': 1, 'HORIZON-JU-CBE-2024-RIA-04': 1, 'HORIZON-CL5-2024-D4-02-04': 1, 'HORIZON-CL5-2024-D5-01-02': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-FTA-03': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-SMR-02': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-FTA-02': 1, 'HORIZON-CL5-2024-D5-01-08': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-SMR-03': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-REG-02': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-SMR-01': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-REG-03': 1, 'HORIZON-CL5-2025-04-D5-07': 1, 'HORIZON-JU-CLEAN-AVIATION-2025-03-REG-01': 1, 'HORIZON-JU-CLEANH2-2025-05-01': 1, 'HORIZON-JU-CBE-2024-IA-02': 1, 'HORIZON-WIDERA-2025-06-ERA-01': 1, 'HORIZON-JTI-CLEANH2-2024-02-05': 1, 'HORIZON-EIC-2024-PATHFINDEROPEN-01-01': 1, 'HORIZON-CL4-2025-SSA-SST-IBA-SP': 1, 'HORIZON-JU-Chips-2024-1-IA-T1': 1, 'HORIZON-EIC-2024-ACCELERATORCHALLENGES-03B': 1, 'HORIZON-EIC-2025-ACCELERATOR-02-CHALLENGES-05': 1, 'HORIZON-EIC-2024-ACCELERATORCHALLENGES-05': 1, 'HORIZON-EURATOM-2025-REPOSITARY-IBA': 1, 'HORIZON-CL3-2024-FCT-01-02': 1, 'HORIZON-JU-CLEANH2-2025-05-02': 1, 'HORIZON-JU-CHIPS-2025-IA-HPA': 1, 'HORIZON-CL4-2025-SSA-SST-IBA-MS': 1, 'HORIZON-CL4-2025-SSA-SST-IBA-SD': 1, 'HORIZON-CL4-2025-SSA-SST-IBA-AE': 1, 'HORIZON-CL4-2025-SSA-SST-IBA-SB': 1, 'Horizon-EIT-2024-NCP-IBA': 1, 'HORIZON-CL5-2024-D3-02-01': 1, 'HORIZON-CL3-2024-DRS-01-05': 1, 'HORIZON-JU-CHIPS-2025-CSA-1': 1, 'HORIZON-CL6-2024-CLIMATE-02-3': 1, 'HORIZON-MISS-2024-CLIMA-01-01': 1, 'HORIZON-CL6-2024-COMMUNITIES-01-3': 1, 'HORIZON-CL6-2024-CircBio-01-5': 1, 'HORIZON-CL6-2024-CircBio-02-1-two-stage': 1, 'HORIZON-CL6-2024-GOVERNANCE-01-9': 1, 'HORIZON-MISS-2024-CIT-01-03': 1, 'HORIZON-CL6-2024-CircBio-01-2': 1, 'HORIZON-MISS-2024-CLIMA-01-08': 1, 'HORIZON-CL6-2024-GOVERNANCE-01-10': 1, 'HORIZON-CL6-2024-FOOD-SYSTEMS-IBA': 1, 'HORIZON-MISS-2024-SOIL-01-04': 1, 'HORIZON-CL6-2024-CircBio-01-3': 1, 'HORIZON-WIDERA-2025-WIRE2026-IBA': 1, 'HORIZON-INFRA-2025-GAZA-IBA': 1, 'HORIZON-JU-CLEANH2-2025-02-02': 1, 'HORIZON-JU-CHIPS-2025-CSA-JPN': 1, 'HORIZON-CL6-2024-CircBio-02-4-two-stage': 1, 'HORIZON-CL6-2024-ZEROPOLLUTION-02-2-two-stage': 1, 'HORIZON-CL4-2024-HUMAN-03-04': 1, 'HORIZON-JU-IHI-2025-09-01-single-stage': 1, 'HORIZON-CL3-2024-FCT-01-01': 1, 'HORIZON-MISS-2024-SOIL-01-03': 1, 'HORIZON-EUROHPC-JU-2023-QEC-05-01': 1, 'HORIZON-CL5-2024-D2-01-04': 1, 'HORIZON-JU-IHI-2024-08-02-two-stage': 1, 'HORIZON-HLTH-2024-DISEASE-12-01': 1, 'HORIZON-CL4-2025-CONFERENCE-AI-IN-SCIENCE': 1, 'HORIZON-JU-EUROHPC-2025-AI-01-IBA-02': 1, 'HORIZON-CL3-2024-DRS-01-01': 1, 'HORIZON-MISS-2024-OCEAN-01-03': 1, 'HORIZON-WIDERA-2023-ACCESS-01-01-two-stage': 1, 'HORIZON-INFRA-2025-ICRI-IBA': 1, 'HORIZON-ER-JU-2025-FA7-01': 1, 'HORIZON-MISS-2024-CLIMA-01-02': 1, 'HORIZON-CL4-2024-SPACE-01-64': 1, 'HORIZON-JU-CLEANH2-2025-03-03': 1, 'HORIZON-JU-CBE-2024-IA-06': 1, 'HORIZON-MISS-2024-SOIL-01-08': 1, 'HORIZON-CL6-2024-GOVERNANCE-02-01': 1, 'HORIZON-CL5-2024-D1-01-02': 1, 'HORIZON-MISS-2024-SOIL-01-05': 1, 'ERC-2023-POC': 1, 'HORIZON-CL3-2024-INFRA-01-02': 1, 'HORIZON-CL3-2024-BM-01-02': 1, 'HORIZON-JU-CLEANH2-2025-01-06': 1, 'HORIZON-JU-CLEANH2-2025-03-01': 1, 'HORIZON-JU-CLEANH2-2025-01-07': 1, 'HORIZON-JU-CLEANH2-2025-04-01': 1, 'HORIZON-JU-CLEANH2-2025-03-02': 1, 'HORIZON-EIT-2025-KIC-IBA-UM': 1, 'HORIZON-JU-CLEANH2-2025-02-03': 1, 'HORIZON-JU-GH-EDCTP3-2024-01-06-two-stage': 1, 'HORIZON-EIE-2024-CONNECT-02-02': 1, 'ERC-2025-VICECHAIRS-IBA': 1, 'HORIZON-CL3-2024-INFRA-01-01': 1, 'HORIZON-JU-GH-EDCTP3-2025-05-AFRICA-01-IBA': 1, 'HORIZON-HLTH-2025-06-PCYP-01-IBA': 1, 'HORIZON-JU-GH-EDCTP3-2023-01-02': 1, 'HORIZON-JU-GH-EDCTP3-2024-01-04-two-stage': 1, 'HORIZON-JU-IHI-2024-08-03-two-stage': 1, 'HORIZON-HLTH-2025-01-CARE-01': 1, 'HORIZON-HLTH-2025-05-EMBL-01-IBA': 1, 'HORIZON-JU-GH-EDCTP3-2024-01-02-two-stage': 1, 'HORIZON-JU-IHI-2024-08-04-two-stage': 1, 'HORIZON-CL3-2024-BM-01-01': 1, 'HORIZON-EIT-2025-KIC-IBA-HEI': 1, 'HORIZON-CL3-2024-FCT-01-04': 1, 'HORIZON-CL5-2024-D3-01-08': 1, 'HORIZON-CL5-2025-04-D5-18': 1, 'ERC-2023-ADG': 1, 'HORIZON-MSCA-2023-PF-01-01': 1, 'HORIZON-WIDERA-2024-ERA-02-01': 1, 'HORIZON-EURATOM-2025-EGE': 1, 'HORIZON-EURATOM-2025-EIPP': 1})

In [116]:
CL2 = (projects_fil[projects_fil['topics'].str.contains('HLTH')])

In [117]:
CL2

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords
9978,101226682,BE READY NOW,SIGNED,BE READY NOW - EUROPEAN PARTNERSHIP FOR PANDEM...,2026-01-01,2032-12-31,"118328575,79","57281202,18",HORIZON.2.1,HORIZON-HLTH-2024-DISEASE-12-01,2025-07-28,HORIZON,HORIZON-HLTH-2024-DISEASE-12,HORIZON-HLTH-2024-DISEASE-12,HORIZON-COFUND,"""BE READY NOW aims to implement the European P...",2026-03-17 11:10:43,274752,10.3030/101226682,"Medical countermeasures, One Health, Pandemic,..."
14815,101297283,CY26-RARE,SIGNED,CYPRUS 2026 EU CONFERENCE: ADVANCEMENT OF TREA...,2025-11-01,2026-04-30,0,300000,HORIZON.2.1,HORIZON-HLTH-2025-06-PCYP-01-IBA,2025-12-10,HORIZON,HORIZON-HLTH-2025-06-IBA,HORIZON-HLTH-2025-06-IBA,HORIZON-CSA,"Rare Diseases (RDs), often called orphan disea...",2026-02-03 05:45:15,280824,10.3030/101297283,"Rare Diseases, Advancement of Treatements, EU ..."
14847,101261864,GACD4,SIGNED,Global Alliance for Chronic Disease Secretariat,2026-01-01,2028-12-31,0,635477,HORIZON.2.1,HORIZON-HLTH-2025-01-CARE-01,2025-12-04,HORIZON,HORIZON-HLTH-2025-04-IBA,HORIZON-HLTH-2025-04-IBA,HORIZON-CSA,The Global Alliance for Chronic Diseases (GACD...,2025-12-12 10:11:01,279552,10.3030/101261864,"chronic noncommunicable disease, underserved p..."
14850,101260366,GBC 2026-2030,SIGNED,The Global Biodata Coalition 2026-2030,2025-12-01,2030-11-30,0,5000000,HORIZON.2.1,HORIZON-HLTH-2025-05-EMBL-01-IBA,2025-11-28,HORIZON,HORIZON-HLTH-2025-05-IBA,HORIZON-HLTH-2025-05-IBA,HORIZON-CSA,Life science research is increasingly data-int...,2025-12-10 10:58:20,279268,10.3030/101260366,"Database, data resource, sustainability, gover..."